FROM mcr.microsoft.com/playwright:v1.19.2-focal

WORKDIR /baseui

# Install zhCn fonts
RUN apt update --allow-releaseinfo-change && apt install fonts-wqy-zenhei
# Copy manifests and install dependencies.
# Doing this before a build step can more effectively leverage Docker caching.
COPY package.json yarn.lock /baseui/
RUN yarn
RUN yarn playwright install --with-deps

# Copy the current files to the docker image.
COPY . .

RUN yarn e2e:build
