// flow-typed signature: b77d4e622fbdef4bf52c2d6778251be3
// flow-typed version: <<STUB>>/card-validator_v^6.2.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'card-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'card-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'card-validator/src/card-number' {
  declare module.exports: any;
}

declare module 'card-validator/src/cvv' {
  declare module.exports: any;
}

declare module 'card-validator/src/expiration-date' {
  declare module.exports: any;
}

declare module 'card-validator/src/expiration-month' {
  declare module.exports: any;
}

declare module 'card-validator/src/expiration-year' {
  declare module.exports: any;
}

declare module 'card-validator/src/lib/is-array' {
  declare module.exports: any;
}

declare module 'card-validator/src/luhn-10' {
  declare module.exports: any;
}

declare module 'card-validator/src/parse-date' {
  declare module.exports: any;
}

declare module 'card-validator/src/postal-code' {
  declare module.exports: any;
}

// Filename aliases
declare module 'card-validator/index' {
  declare module.exports: $Exports<'card-validator'>;
}
declare module 'card-validator/index.js' {
  declare module.exports: $Exports<'card-validator'>;
}
declare module 'card-validator/src/card-number.js' {
  declare module.exports: $Exports<'card-validator/src/card-number'>;
}
declare module 'card-validator/src/cvv.js' {
  declare module.exports: $Exports<'card-validator/src/cvv'>;
}
declare module 'card-validator/src/expiration-date.js' {
  declare module.exports: $Exports<'card-validator/src/expiration-date'>;
}
declare module 'card-validator/src/expiration-month.js' {
  declare module.exports: $Exports<'card-validator/src/expiration-month'>;
}
declare module 'card-validator/src/expiration-year.js' {
  declare module.exports: $Exports<'card-validator/src/expiration-year'>;
}
declare module 'card-validator/src/lib/is-array.js' {
  declare module.exports: $Exports<'card-validator/src/lib/is-array'>;
}
declare module 'card-validator/src/luhn-10.js' {
  declare module.exports: $Exports<'card-validator/src/luhn-10'>;
}
declare module 'card-validator/src/parse-date.js' {
  declare module.exports: $Exports<'card-validator/src/parse-date'>;
}
declare module 'card-validator/src/postal-code.js' {
  declare module.exports: $Exports<'card-validator/src/postal-code'>;
}
