// flow-typed signature: e2d3e31738bf1d8d6ee9e97f12503406
// flow-typed version: <<STUB>>/dayjs_v^1.8.14/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dayjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dayjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dayjs/dayjs.min' {
  declare module.exports: any;
}

declare module 'dayjs/esm/constant' {
  declare module.exports: any;
}

declare module 'dayjs/esm/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/af' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ar-dz' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ar-kw' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ar-ly' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ar-ma' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ar-sa' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ar-tn' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ar' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/az' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/be' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/bg' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/bm' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/bn' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/bo' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/br' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/bs' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ca' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/cs' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/cv' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/cy' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/da' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/de-at' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/de-ch' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/de' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/dv' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/el' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/en-au' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/en-ca' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/en-gb' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/en-ie' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/en-il' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/en-nz' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/en-SG' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/en' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/eo' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/es-do' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/es-us' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/es' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/et' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/eu' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/fa' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/fi' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/fo' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/fr-ca' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/fr-ch' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/fr' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/fy' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ga' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/gd' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/gl' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/gom-latn' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/gu' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/he' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/hi' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/hr' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/hu' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/hy-am' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/id' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/is' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/it-ch' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/it' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ja' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/jv' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ka' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/kk' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/km' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/kn' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ko' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ku' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ky' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/lb' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/lo' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/lt' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/lv' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/me' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/mi' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/mk' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ml' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/mn' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/mr' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ms-my' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ms' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/mt' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/my' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/nb' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ne' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/nl-be' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/nl' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/nn' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/oc-lnc' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/pa-in' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/pl' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/pt-br' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/pt' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ro' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ru' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/sd' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/se' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/si' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/sk' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/sl' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/sq' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/sr-cyrl' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/sr' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ss' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/sv' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/sw' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ta' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/te' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/tet' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/tg' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/th' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/tl-ph' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/tlh' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/tr' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/tzl' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/tzm-latn' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/tzm' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ug-cn' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/uk' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/ur' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/uz-latn' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/uz' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/vi' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/x-pseudo' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/yo' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/zh-cn' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/zh-hk' {
  declare module.exports: any;
}

declare module 'dayjs/esm/locale/zh-tw' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/advancedFormat/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/badMutable/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/buddhistEra/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/calendar/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/customParseFormat/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/dayOfYear/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/isBetween/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/isLeapYear/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/isMoment/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/isoWeeksInYear/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/isSameOrAfter/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/isSameOrBefore/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/localeData/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/localizedFormat/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/minMax/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/quarterOfYear/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/relativeTime/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/toArray/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/toObject/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/utc/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/weekday/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/weekOfYear/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/plugin/weekYear/index' {
  declare module.exports: any;
}

declare module 'dayjs/esm/utils' {
  declare module.exports: any;
}

declare module 'dayjs/locale/af' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ar-dz' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ar-kw' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ar-ly' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ar-ma' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ar-sa' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ar-tn' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ar' {
  declare module.exports: any;
}

declare module 'dayjs/locale/az' {
  declare module.exports: any;
}

declare module 'dayjs/locale/be' {
  declare module.exports: any;
}

declare module 'dayjs/locale/bg' {
  declare module.exports: any;
}

declare module 'dayjs/locale/bm' {
  declare module.exports: any;
}

declare module 'dayjs/locale/bn' {
  declare module.exports: any;
}

declare module 'dayjs/locale/bo' {
  declare module.exports: any;
}

declare module 'dayjs/locale/br' {
  declare module.exports: any;
}

declare module 'dayjs/locale/bs' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ca' {
  declare module.exports: any;
}

declare module 'dayjs/locale/cs' {
  declare module.exports: any;
}

declare module 'dayjs/locale/cv' {
  declare module.exports: any;
}

declare module 'dayjs/locale/cy' {
  declare module.exports: any;
}

declare module 'dayjs/locale/da' {
  declare module.exports: any;
}

declare module 'dayjs/locale/de-at' {
  declare module.exports: any;
}

declare module 'dayjs/locale/de-ch' {
  declare module.exports: any;
}

declare module 'dayjs/locale/de' {
  declare module.exports: any;
}

declare module 'dayjs/locale/dv' {
  declare module.exports: any;
}

declare module 'dayjs/locale/el' {
  declare module.exports: any;
}

declare module 'dayjs/locale/en-au' {
  declare module.exports: any;
}

declare module 'dayjs/locale/en-ca' {
  declare module.exports: any;
}

declare module 'dayjs/locale/en-gb' {
  declare module.exports: any;
}

declare module 'dayjs/locale/en-ie' {
  declare module.exports: any;
}

declare module 'dayjs/locale/en-il' {
  declare module.exports: any;
}

declare module 'dayjs/locale/en-nz' {
  declare module.exports: any;
}

declare module 'dayjs/locale/en-SG' {
  declare module.exports: any;
}

declare module 'dayjs/locale/en' {
  declare module.exports: any;
}

declare module 'dayjs/locale/eo' {
  declare module.exports: any;
}

declare module 'dayjs/locale/es-do' {
  declare module.exports: any;
}

declare module 'dayjs/locale/es-us' {
  declare module.exports: any;
}

declare module 'dayjs/locale/es' {
  declare module.exports: any;
}

declare module 'dayjs/locale/et' {
  declare module.exports: any;
}

declare module 'dayjs/locale/eu' {
  declare module.exports: any;
}

declare module 'dayjs/locale/fa' {
  declare module.exports: any;
}

declare module 'dayjs/locale/fi' {
  declare module.exports: any;
}

declare module 'dayjs/locale/fo' {
  declare module.exports: any;
}

declare module 'dayjs/locale/fr-ca' {
  declare module.exports: any;
}

declare module 'dayjs/locale/fr-ch' {
  declare module.exports: any;
}

declare module 'dayjs/locale/fr' {
  declare module.exports: any;
}

declare module 'dayjs/locale/fy' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ga' {
  declare module.exports: any;
}

declare module 'dayjs/locale/gd' {
  declare module.exports: any;
}

declare module 'dayjs/locale/gl' {
  declare module.exports: any;
}

declare module 'dayjs/locale/gom-latn' {
  declare module.exports: any;
}

declare module 'dayjs/locale/gu' {
  declare module.exports: any;
}

declare module 'dayjs/locale/he' {
  declare module.exports: any;
}

declare module 'dayjs/locale/hi' {
  declare module.exports: any;
}

declare module 'dayjs/locale/hr' {
  declare module.exports: any;
}

declare module 'dayjs/locale/hu' {
  declare module.exports: any;
}

declare module 'dayjs/locale/hy-am' {
  declare module.exports: any;
}

declare module 'dayjs/locale/id' {
  declare module.exports: any;
}

declare module 'dayjs/locale/is' {
  declare module.exports: any;
}

declare module 'dayjs/locale/it-ch' {
  declare module.exports: any;
}

declare module 'dayjs/locale/it' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ja' {
  declare module.exports: any;
}

declare module 'dayjs/locale/jv' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ka' {
  declare module.exports: any;
}

declare module 'dayjs/locale/kk' {
  declare module.exports: any;
}

declare module 'dayjs/locale/km' {
  declare module.exports: any;
}

declare module 'dayjs/locale/kn' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ko' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ku' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ky' {
  declare module.exports: any;
}

declare module 'dayjs/locale/lb' {
  declare module.exports: any;
}

declare module 'dayjs/locale/lo' {
  declare module.exports: any;
}

declare module 'dayjs/locale/lt' {
  declare module.exports: any;
}

declare module 'dayjs/locale/lv' {
  declare module.exports: any;
}

declare module 'dayjs/locale/me' {
  declare module.exports: any;
}

declare module 'dayjs/locale/mi' {
  declare module.exports: any;
}

declare module 'dayjs/locale/mk' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ml' {
  declare module.exports: any;
}

declare module 'dayjs/locale/mn' {
  declare module.exports: any;
}

declare module 'dayjs/locale/mr' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ms-my' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ms' {
  declare module.exports: any;
}

declare module 'dayjs/locale/mt' {
  declare module.exports: any;
}

declare module 'dayjs/locale/my' {
  declare module.exports: any;
}

declare module 'dayjs/locale/nb' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ne' {
  declare module.exports: any;
}

declare module 'dayjs/locale/nl-be' {
  declare module.exports: any;
}

declare module 'dayjs/locale/nl' {
  declare module.exports: any;
}

declare module 'dayjs/locale/nn' {
  declare module.exports: any;
}

declare module 'dayjs/locale/oc-lnc' {
  declare module.exports: any;
}

declare module 'dayjs/locale/pa-in' {
  declare module.exports: any;
}

declare module 'dayjs/locale/pl' {
  declare module.exports: any;
}

declare module 'dayjs/locale/pt-br' {
  declare module.exports: any;
}

declare module 'dayjs/locale/pt' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ro' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ru' {
  declare module.exports: any;
}

declare module 'dayjs/locale/sd' {
  declare module.exports: any;
}

declare module 'dayjs/locale/se' {
  declare module.exports: any;
}

declare module 'dayjs/locale/si' {
  declare module.exports: any;
}

declare module 'dayjs/locale/sk' {
  declare module.exports: any;
}

declare module 'dayjs/locale/sl' {
  declare module.exports: any;
}

declare module 'dayjs/locale/sq' {
  declare module.exports: any;
}

declare module 'dayjs/locale/sr-cyrl' {
  declare module.exports: any;
}

declare module 'dayjs/locale/sr' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ss' {
  declare module.exports: any;
}

declare module 'dayjs/locale/sv' {
  declare module.exports: any;
}

declare module 'dayjs/locale/sw' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ta' {
  declare module.exports: any;
}

declare module 'dayjs/locale/te' {
  declare module.exports: any;
}

declare module 'dayjs/locale/tet' {
  declare module.exports: any;
}

declare module 'dayjs/locale/tg' {
  declare module.exports: any;
}

declare module 'dayjs/locale/th' {
  declare module.exports: any;
}

declare module 'dayjs/locale/tl-ph' {
  declare module.exports: any;
}

declare module 'dayjs/locale/tlh' {
  declare module.exports: any;
}

declare module 'dayjs/locale/tr' {
  declare module.exports: any;
}

declare module 'dayjs/locale/tzl' {
  declare module.exports: any;
}

declare module 'dayjs/locale/tzm-latn' {
  declare module.exports: any;
}

declare module 'dayjs/locale/tzm' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ug-cn' {
  declare module.exports: any;
}

declare module 'dayjs/locale/uk' {
  declare module.exports: any;
}

declare module 'dayjs/locale/ur' {
  declare module.exports: any;
}

declare module 'dayjs/locale/uz-latn' {
  declare module.exports: any;
}

declare module 'dayjs/locale/uz' {
  declare module.exports: any;
}

declare module 'dayjs/locale/vi' {
  declare module.exports: any;
}

declare module 'dayjs/locale/x-pseudo' {
  declare module.exports: any;
}

declare module 'dayjs/locale/yo' {
  declare module.exports: any;
}

declare module 'dayjs/locale/zh-cn' {
  declare module.exports: any;
}

declare module 'dayjs/locale/zh-hk' {
  declare module.exports: any;
}

declare module 'dayjs/locale/zh-tw' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/advancedFormat' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/badMutable' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/buddhistEra' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/calendar' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/customParseFormat' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/dayOfYear' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/isBetween' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/isLeapYear' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/isMoment' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/isoWeeksInYear' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/isSameOrAfter' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/isSameOrBefore' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/localeData' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/localizedFormat' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/minMax' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/quarterOfYear' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/relativeTime' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/toArray' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/toObject' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/utc' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/weekday' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/weekOfYear' {
  declare module.exports: any;
}

declare module 'dayjs/plugin/weekYear' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dayjs/dayjs.min.js' {
  declare module.exports: $Exports<'dayjs/dayjs.min'>;
}
declare module 'dayjs/esm/constant.js' {
  declare module.exports: $Exports<'dayjs/esm/constant'>;
}
declare module 'dayjs/esm/index.js' {
  declare module.exports: $Exports<'dayjs/esm/index'>;
}
declare module 'dayjs/esm/locale/af.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/af'>;
}
declare module 'dayjs/esm/locale/ar-dz.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ar-dz'>;
}
declare module 'dayjs/esm/locale/ar-kw.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ar-kw'>;
}
declare module 'dayjs/esm/locale/ar-ly.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ar-ly'>;
}
declare module 'dayjs/esm/locale/ar-ma.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ar-ma'>;
}
declare module 'dayjs/esm/locale/ar-sa.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ar-sa'>;
}
declare module 'dayjs/esm/locale/ar-tn.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ar-tn'>;
}
declare module 'dayjs/esm/locale/ar.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ar'>;
}
declare module 'dayjs/esm/locale/az.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/az'>;
}
declare module 'dayjs/esm/locale/be.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/be'>;
}
declare module 'dayjs/esm/locale/bg.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/bg'>;
}
declare module 'dayjs/esm/locale/bm.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/bm'>;
}
declare module 'dayjs/esm/locale/bn.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/bn'>;
}
declare module 'dayjs/esm/locale/bo.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/bo'>;
}
declare module 'dayjs/esm/locale/br.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/br'>;
}
declare module 'dayjs/esm/locale/bs.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/bs'>;
}
declare module 'dayjs/esm/locale/ca.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ca'>;
}
declare module 'dayjs/esm/locale/cs.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/cs'>;
}
declare module 'dayjs/esm/locale/cv.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/cv'>;
}
declare module 'dayjs/esm/locale/cy.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/cy'>;
}
declare module 'dayjs/esm/locale/da.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/da'>;
}
declare module 'dayjs/esm/locale/de-at.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/de-at'>;
}
declare module 'dayjs/esm/locale/de-ch.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/de-ch'>;
}
declare module 'dayjs/esm/locale/de.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/de'>;
}
declare module 'dayjs/esm/locale/dv.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/dv'>;
}
declare module 'dayjs/esm/locale/el.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/el'>;
}
declare module 'dayjs/esm/locale/en-au.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/en-au'>;
}
declare module 'dayjs/esm/locale/en-ca.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/en-ca'>;
}
declare module 'dayjs/esm/locale/en-gb.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/en-gb'>;
}
declare module 'dayjs/esm/locale/en-ie.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/en-ie'>;
}
declare module 'dayjs/esm/locale/en-il.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/en-il'>;
}
declare module 'dayjs/esm/locale/en-nz.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/en-nz'>;
}
declare module 'dayjs/esm/locale/en-SG.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/en-SG'>;
}
declare module 'dayjs/esm/locale/en.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/en'>;
}
declare module 'dayjs/esm/locale/eo.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/eo'>;
}
declare module 'dayjs/esm/locale/es-do.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/es-do'>;
}
declare module 'dayjs/esm/locale/es-us.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/es-us'>;
}
declare module 'dayjs/esm/locale/es.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/es'>;
}
declare module 'dayjs/esm/locale/et.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/et'>;
}
declare module 'dayjs/esm/locale/eu.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/eu'>;
}
declare module 'dayjs/esm/locale/fa.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/fa'>;
}
declare module 'dayjs/esm/locale/fi.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/fi'>;
}
declare module 'dayjs/esm/locale/fo.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/fo'>;
}
declare module 'dayjs/esm/locale/fr-ca.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/fr-ca'>;
}
declare module 'dayjs/esm/locale/fr-ch.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/fr-ch'>;
}
declare module 'dayjs/esm/locale/fr.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/fr'>;
}
declare module 'dayjs/esm/locale/fy.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/fy'>;
}
declare module 'dayjs/esm/locale/ga.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ga'>;
}
declare module 'dayjs/esm/locale/gd.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/gd'>;
}
declare module 'dayjs/esm/locale/gl.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/gl'>;
}
declare module 'dayjs/esm/locale/gom-latn.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/gom-latn'>;
}
declare module 'dayjs/esm/locale/gu.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/gu'>;
}
declare module 'dayjs/esm/locale/he.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/he'>;
}
declare module 'dayjs/esm/locale/hi.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/hi'>;
}
declare module 'dayjs/esm/locale/hr.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/hr'>;
}
declare module 'dayjs/esm/locale/hu.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/hu'>;
}
declare module 'dayjs/esm/locale/hy-am.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/hy-am'>;
}
declare module 'dayjs/esm/locale/id.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/id'>;
}
declare module 'dayjs/esm/locale/is.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/is'>;
}
declare module 'dayjs/esm/locale/it-ch.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/it-ch'>;
}
declare module 'dayjs/esm/locale/it.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/it'>;
}
declare module 'dayjs/esm/locale/ja.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ja'>;
}
declare module 'dayjs/esm/locale/jv.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/jv'>;
}
declare module 'dayjs/esm/locale/ka.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ka'>;
}
declare module 'dayjs/esm/locale/kk.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/kk'>;
}
declare module 'dayjs/esm/locale/km.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/km'>;
}
declare module 'dayjs/esm/locale/kn.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/kn'>;
}
declare module 'dayjs/esm/locale/ko.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ko'>;
}
declare module 'dayjs/esm/locale/ku.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ku'>;
}
declare module 'dayjs/esm/locale/ky.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ky'>;
}
declare module 'dayjs/esm/locale/lb.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/lb'>;
}
declare module 'dayjs/esm/locale/lo.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/lo'>;
}
declare module 'dayjs/esm/locale/lt.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/lt'>;
}
declare module 'dayjs/esm/locale/lv.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/lv'>;
}
declare module 'dayjs/esm/locale/me.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/me'>;
}
declare module 'dayjs/esm/locale/mi.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/mi'>;
}
declare module 'dayjs/esm/locale/mk.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/mk'>;
}
declare module 'dayjs/esm/locale/ml.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ml'>;
}
declare module 'dayjs/esm/locale/mn.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/mn'>;
}
declare module 'dayjs/esm/locale/mr.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/mr'>;
}
declare module 'dayjs/esm/locale/ms-my.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ms-my'>;
}
declare module 'dayjs/esm/locale/ms.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ms'>;
}
declare module 'dayjs/esm/locale/mt.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/mt'>;
}
declare module 'dayjs/esm/locale/my.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/my'>;
}
declare module 'dayjs/esm/locale/nb.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/nb'>;
}
declare module 'dayjs/esm/locale/ne.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ne'>;
}
declare module 'dayjs/esm/locale/nl-be.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/nl-be'>;
}
declare module 'dayjs/esm/locale/nl.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/nl'>;
}
declare module 'dayjs/esm/locale/nn.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/nn'>;
}
declare module 'dayjs/esm/locale/oc-lnc.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/oc-lnc'>;
}
declare module 'dayjs/esm/locale/pa-in.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/pa-in'>;
}
declare module 'dayjs/esm/locale/pl.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/pl'>;
}
declare module 'dayjs/esm/locale/pt-br.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/pt-br'>;
}
declare module 'dayjs/esm/locale/pt.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/pt'>;
}
declare module 'dayjs/esm/locale/ro.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ro'>;
}
declare module 'dayjs/esm/locale/ru.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ru'>;
}
declare module 'dayjs/esm/locale/sd.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/sd'>;
}
declare module 'dayjs/esm/locale/se.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/se'>;
}
declare module 'dayjs/esm/locale/si.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/si'>;
}
declare module 'dayjs/esm/locale/sk.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/sk'>;
}
declare module 'dayjs/esm/locale/sl.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/sl'>;
}
declare module 'dayjs/esm/locale/sq.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/sq'>;
}
declare module 'dayjs/esm/locale/sr-cyrl.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/sr-cyrl'>;
}
declare module 'dayjs/esm/locale/sr.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/sr'>;
}
declare module 'dayjs/esm/locale/ss.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ss'>;
}
declare module 'dayjs/esm/locale/sv.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/sv'>;
}
declare module 'dayjs/esm/locale/sw.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/sw'>;
}
declare module 'dayjs/esm/locale/ta.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ta'>;
}
declare module 'dayjs/esm/locale/te.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/te'>;
}
declare module 'dayjs/esm/locale/tet.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/tet'>;
}
declare module 'dayjs/esm/locale/tg.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/tg'>;
}
declare module 'dayjs/esm/locale/th.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/th'>;
}
declare module 'dayjs/esm/locale/tl-ph.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/tl-ph'>;
}
declare module 'dayjs/esm/locale/tlh.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/tlh'>;
}
declare module 'dayjs/esm/locale/tr.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/tr'>;
}
declare module 'dayjs/esm/locale/tzl.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/tzl'>;
}
declare module 'dayjs/esm/locale/tzm-latn.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/tzm-latn'>;
}
declare module 'dayjs/esm/locale/tzm.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/tzm'>;
}
declare module 'dayjs/esm/locale/ug-cn.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ug-cn'>;
}
declare module 'dayjs/esm/locale/uk.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/uk'>;
}
declare module 'dayjs/esm/locale/ur.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/ur'>;
}
declare module 'dayjs/esm/locale/uz-latn.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/uz-latn'>;
}
declare module 'dayjs/esm/locale/uz.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/uz'>;
}
declare module 'dayjs/esm/locale/vi.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/vi'>;
}
declare module 'dayjs/esm/locale/x-pseudo.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/x-pseudo'>;
}
declare module 'dayjs/esm/locale/yo.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/yo'>;
}
declare module 'dayjs/esm/locale/zh-cn.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/zh-cn'>;
}
declare module 'dayjs/esm/locale/zh-hk.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/zh-hk'>;
}
declare module 'dayjs/esm/locale/zh-tw.js' {
  declare module.exports: $Exports<'dayjs/esm/locale/zh-tw'>;
}
declare module 'dayjs/esm/plugin/advancedFormat/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/advancedFormat/index'>;
}
declare module 'dayjs/esm/plugin/badMutable/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/badMutable/index'>;
}
declare module 'dayjs/esm/plugin/buddhistEra/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/buddhistEra/index'>;
}
declare module 'dayjs/esm/plugin/calendar/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/calendar/index'>;
}
declare module 'dayjs/esm/plugin/customParseFormat/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/customParseFormat/index'>;
}
declare module 'dayjs/esm/plugin/dayOfYear/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/dayOfYear/index'>;
}
declare module 'dayjs/esm/plugin/isBetween/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/isBetween/index'>;
}
declare module 'dayjs/esm/plugin/isLeapYear/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/isLeapYear/index'>;
}
declare module 'dayjs/esm/plugin/isMoment/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/isMoment/index'>;
}
declare module 'dayjs/esm/plugin/isoWeeksInYear/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/isoWeeksInYear/index'>;
}
declare module 'dayjs/esm/plugin/isSameOrAfter/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/isSameOrAfter/index'>;
}
declare module 'dayjs/esm/plugin/isSameOrBefore/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/isSameOrBefore/index'>;
}
declare module 'dayjs/esm/plugin/localeData/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/localeData/index'>;
}
declare module 'dayjs/esm/plugin/localizedFormat/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/localizedFormat/index'>;
}
declare module 'dayjs/esm/plugin/minMax/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/minMax/index'>;
}
declare module 'dayjs/esm/plugin/quarterOfYear/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/quarterOfYear/index'>;
}
declare module 'dayjs/esm/plugin/relativeTime/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/relativeTime/index'>;
}
declare module 'dayjs/esm/plugin/toArray/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/toArray/index'>;
}
declare module 'dayjs/esm/plugin/toObject/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/toObject/index'>;
}
declare module 'dayjs/esm/plugin/utc/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/utc/index'>;
}
declare module 'dayjs/esm/plugin/weekday/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/weekday/index'>;
}
declare module 'dayjs/esm/plugin/weekOfYear/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/weekOfYear/index'>;
}
declare module 'dayjs/esm/plugin/weekYear/index.js' {
  declare module.exports: $Exports<'dayjs/esm/plugin/weekYear/index'>;
}
declare module 'dayjs/esm/utils.js' {
  declare module.exports: $Exports<'dayjs/esm/utils'>;
}
declare module 'dayjs/locale/af.js' {
  declare module.exports: $Exports<'dayjs/locale/af'>;
}
declare module 'dayjs/locale/ar-dz.js' {
  declare module.exports: $Exports<'dayjs/locale/ar-dz'>;
}
declare module 'dayjs/locale/ar-kw.js' {
  declare module.exports: $Exports<'dayjs/locale/ar-kw'>;
}
declare module 'dayjs/locale/ar-ly.js' {
  declare module.exports: $Exports<'dayjs/locale/ar-ly'>;
}
declare module 'dayjs/locale/ar-ma.js' {
  declare module.exports: $Exports<'dayjs/locale/ar-ma'>;
}
declare module 'dayjs/locale/ar-sa.js' {
  declare module.exports: $Exports<'dayjs/locale/ar-sa'>;
}
declare module 'dayjs/locale/ar-tn.js' {
  declare module.exports: $Exports<'dayjs/locale/ar-tn'>;
}
declare module 'dayjs/locale/ar.js' {
  declare module.exports: $Exports<'dayjs/locale/ar'>;
}
declare module 'dayjs/locale/az.js' {
  declare module.exports: $Exports<'dayjs/locale/az'>;
}
declare module 'dayjs/locale/be.js' {
  declare module.exports: $Exports<'dayjs/locale/be'>;
}
declare module 'dayjs/locale/bg.js' {
  declare module.exports: $Exports<'dayjs/locale/bg'>;
}
declare module 'dayjs/locale/bm.js' {
  declare module.exports: $Exports<'dayjs/locale/bm'>;
}
declare module 'dayjs/locale/bn.js' {
  declare module.exports: $Exports<'dayjs/locale/bn'>;
}
declare module 'dayjs/locale/bo.js' {
  declare module.exports: $Exports<'dayjs/locale/bo'>;
}
declare module 'dayjs/locale/br.js' {
  declare module.exports: $Exports<'dayjs/locale/br'>;
}
declare module 'dayjs/locale/bs.js' {
  declare module.exports: $Exports<'dayjs/locale/bs'>;
}
declare module 'dayjs/locale/ca.js' {
  declare module.exports: $Exports<'dayjs/locale/ca'>;
}
declare module 'dayjs/locale/cs.js' {
  declare module.exports: $Exports<'dayjs/locale/cs'>;
}
declare module 'dayjs/locale/cv.js' {
  declare module.exports: $Exports<'dayjs/locale/cv'>;
}
declare module 'dayjs/locale/cy.js' {
  declare module.exports: $Exports<'dayjs/locale/cy'>;
}
declare module 'dayjs/locale/da.js' {
  declare module.exports: $Exports<'dayjs/locale/da'>;
}
declare module 'dayjs/locale/de-at.js' {
  declare module.exports: $Exports<'dayjs/locale/de-at'>;
}
declare module 'dayjs/locale/de-ch.js' {
  declare module.exports: $Exports<'dayjs/locale/de-ch'>;
}
declare module 'dayjs/locale/de.js' {
  declare module.exports: $Exports<'dayjs/locale/de'>;
}
declare module 'dayjs/locale/dv.js' {
  declare module.exports: $Exports<'dayjs/locale/dv'>;
}
declare module 'dayjs/locale/el.js' {
  declare module.exports: $Exports<'dayjs/locale/el'>;
}
declare module 'dayjs/locale/en-au.js' {
  declare module.exports: $Exports<'dayjs/locale/en-au'>;
}
declare module 'dayjs/locale/en-ca.js' {
  declare module.exports: $Exports<'dayjs/locale/en-ca'>;
}
declare module 'dayjs/locale/en-gb.js' {
  declare module.exports: $Exports<'dayjs/locale/en-gb'>;
}
declare module 'dayjs/locale/en-ie.js' {
  declare module.exports: $Exports<'dayjs/locale/en-ie'>;
}
declare module 'dayjs/locale/en-il.js' {
  declare module.exports: $Exports<'dayjs/locale/en-il'>;
}
declare module 'dayjs/locale/en-nz.js' {
  declare module.exports: $Exports<'dayjs/locale/en-nz'>;
}
declare module 'dayjs/locale/en-SG.js' {
  declare module.exports: $Exports<'dayjs/locale/en-SG'>;
}
declare module 'dayjs/locale/en.js' {
  declare module.exports: $Exports<'dayjs/locale/en'>;
}
declare module 'dayjs/locale/eo.js' {
  declare module.exports: $Exports<'dayjs/locale/eo'>;
}
declare module 'dayjs/locale/es-do.js' {
  declare module.exports: $Exports<'dayjs/locale/es-do'>;
}
declare module 'dayjs/locale/es-us.js' {
  declare module.exports: $Exports<'dayjs/locale/es-us'>;
}
declare module 'dayjs/locale/es.js' {
  declare module.exports: $Exports<'dayjs/locale/es'>;
}
declare module 'dayjs/locale/et.js' {
  declare module.exports: $Exports<'dayjs/locale/et'>;
}
declare module 'dayjs/locale/eu.js' {
  declare module.exports: $Exports<'dayjs/locale/eu'>;
}
declare module 'dayjs/locale/fa.js' {
  declare module.exports: $Exports<'dayjs/locale/fa'>;
}
declare module 'dayjs/locale/fi.js' {
  declare module.exports: $Exports<'dayjs/locale/fi'>;
}
declare module 'dayjs/locale/fo.js' {
  declare module.exports: $Exports<'dayjs/locale/fo'>;
}
declare module 'dayjs/locale/fr-ca.js' {
  declare module.exports: $Exports<'dayjs/locale/fr-ca'>;
}
declare module 'dayjs/locale/fr-ch.js' {
  declare module.exports: $Exports<'dayjs/locale/fr-ch'>;
}
declare module 'dayjs/locale/fr.js' {
  declare module.exports: $Exports<'dayjs/locale/fr'>;
}
declare module 'dayjs/locale/fy.js' {
  declare module.exports: $Exports<'dayjs/locale/fy'>;
}
declare module 'dayjs/locale/ga.js' {
  declare module.exports: $Exports<'dayjs/locale/ga'>;
}
declare module 'dayjs/locale/gd.js' {
  declare module.exports: $Exports<'dayjs/locale/gd'>;
}
declare module 'dayjs/locale/gl.js' {
  declare module.exports: $Exports<'dayjs/locale/gl'>;
}
declare module 'dayjs/locale/gom-latn.js' {
  declare module.exports: $Exports<'dayjs/locale/gom-latn'>;
}
declare module 'dayjs/locale/gu.js' {
  declare module.exports: $Exports<'dayjs/locale/gu'>;
}
declare module 'dayjs/locale/he.js' {
  declare module.exports: $Exports<'dayjs/locale/he'>;
}
declare module 'dayjs/locale/hi.js' {
  declare module.exports: $Exports<'dayjs/locale/hi'>;
}
declare module 'dayjs/locale/hr.js' {
  declare module.exports: $Exports<'dayjs/locale/hr'>;
}
declare module 'dayjs/locale/hu.js' {
  declare module.exports: $Exports<'dayjs/locale/hu'>;
}
declare module 'dayjs/locale/hy-am.js' {
  declare module.exports: $Exports<'dayjs/locale/hy-am'>;
}
declare module 'dayjs/locale/id.js' {
  declare module.exports: $Exports<'dayjs/locale/id'>;
}
declare module 'dayjs/locale/is.js' {
  declare module.exports: $Exports<'dayjs/locale/is'>;
}
declare module 'dayjs/locale/it-ch.js' {
  declare module.exports: $Exports<'dayjs/locale/it-ch'>;
}
declare module 'dayjs/locale/it.js' {
  declare module.exports: $Exports<'dayjs/locale/it'>;
}
declare module 'dayjs/locale/ja.js' {
  declare module.exports: $Exports<'dayjs/locale/ja'>;
}
declare module 'dayjs/locale/jv.js' {
  declare module.exports: $Exports<'dayjs/locale/jv'>;
}
declare module 'dayjs/locale/ka.js' {
  declare module.exports: $Exports<'dayjs/locale/ka'>;
}
declare module 'dayjs/locale/kk.js' {
  declare module.exports: $Exports<'dayjs/locale/kk'>;
}
declare module 'dayjs/locale/km.js' {
  declare module.exports: $Exports<'dayjs/locale/km'>;
}
declare module 'dayjs/locale/kn.js' {
  declare module.exports: $Exports<'dayjs/locale/kn'>;
}
declare module 'dayjs/locale/ko.js' {
  declare module.exports: $Exports<'dayjs/locale/ko'>;
}
declare module 'dayjs/locale/ku.js' {
  declare module.exports: $Exports<'dayjs/locale/ku'>;
}
declare module 'dayjs/locale/ky.js' {
  declare module.exports: $Exports<'dayjs/locale/ky'>;
}
declare module 'dayjs/locale/lb.js' {
  declare module.exports: $Exports<'dayjs/locale/lb'>;
}
declare module 'dayjs/locale/lo.js' {
  declare module.exports: $Exports<'dayjs/locale/lo'>;
}
declare module 'dayjs/locale/lt.js' {
  declare module.exports: $Exports<'dayjs/locale/lt'>;
}
declare module 'dayjs/locale/lv.js' {
  declare module.exports: $Exports<'dayjs/locale/lv'>;
}
declare module 'dayjs/locale/me.js' {
  declare module.exports: $Exports<'dayjs/locale/me'>;
}
declare module 'dayjs/locale/mi.js' {
  declare module.exports: $Exports<'dayjs/locale/mi'>;
}
declare module 'dayjs/locale/mk.js' {
  declare module.exports: $Exports<'dayjs/locale/mk'>;
}
declare module 'dayjs/locale/ml.js' {
  declare module.exports: $Exports<'dayjs/locale/ml'>;
}
declare module 'dayjs/locale/mn.js' {
  declare module.exports: $Exports<'dayjs/locale/mn'>;
}
declare module 'dayjs/locale/mr.js' {
  declare module.exports: $Exports<'dayjs/locale/mr'>;
}
declare module 'dayjs/locale/ms-my.js' {
  declare module.exports: $Exports<'dayjs/locale/ms-my'>;
}
declare module 'dayjs/locale/ms.js' {
  declare module.exports: $Exports<'dayjs/locale/ms'>;
}
declare module 'dayjs/locale/mt.js' {
  declare module.exports: $Exports<'dayjs/locale/mt'>;
}
declare module 'dayjs/locale/my.js' {
  declare module.exports: $Exports<'dayjs/locale/my'>;
}
declare module 'dayjs/locale/nb.js' {
  declare module.exports: $Exports<'dayjs/locale/nb'>;
}
declare module 'dayjs/locale/ne.js' {
  declare module.exports: $Exports<'dayjs/locale/ne'>;
}
declare module 'dayjs/locale/nl-be.js' {
  declare module.exports: $Exports<'dayjs/locale/nl-be'>;
}
declare module 'dayjs/locale/nl.js' {
  declare module.exports: $Exports<'dayjs/locale/nl'>;
}
declare module 'dayjs/locale/nn.js' {
  declare module.exports: $Exports<'dayjs/locale/nn'>;
}
declare module 'dayjs/locale/oc-lnc.js' {
  declare module.exports: $Exports<'dayjs/locale/oc-lnc'>;
}
declare module 'dayjs/locale/pa-in.js' {
  declare module.exports: $Exports<'dayjs/locale/pa-in'>;
}
declare module 'dayjs/locale/pl.js' {
  declare module.exports: $Exports<'dayjs/locale/pl'>;
}
declare module 'dayjs/locale/pt-br.js' {
  declare module.exports: $Exports<'dayjs/locale/pt-br'>;
}
declare module 'dayjs/locale/pt.js' {
  declare module.exports: $Exports<'dayjs/locale/pt'>;
}
declare module 'dayjs/locale/ro.js' {
  declare module.exports: $Exports<'dayjs/locale/ro'>;
}
declare module 'dayjs/locale/ru.js' {
  declare module.exports: $Exports<'dayjs/locale/ru'>;
}
declare module 'dayjs/locale/sd.js' {
  declare module.exports: $Exports<'dayjs/locale/sd'>;
}
declare module 'dayjs/locale/se.js' {
  declare module.exports: $Exports<'dayjs/locale/se'>;
}
declare module 'dayjs/locale/si.js' {
  declare module.exports: $Exports<'dayjs/locale/si'>;
}
declare module 'dayjs/locale/sk.js' {
  declare module.exports: $Exports<'dayjs/locale/sk'>;
}
declare module 'dayjs/locale/sl.js' {
  declare module.exports: $Exports<'dayjs/locale/sl'>;
}
declare module 'dayjs/locale/sq.js' {
  declare module.exports: $Exports<'dayjs/locale/sq'>;
}
declare module 'dayjs/locale/sr-cyrl.js' {
  declare module.exports: $Exports<'dayjs/locale/sr-cyrl'>;
}
declare module 'dayjs/locale/sr.js' {
  declare module.exports: $Exports<'dayjs/locale/sr'>;
}
declare module 'dayjs/locale/ss.js' {
  declare module.exports: $Exports<'dayjs/locale/ss'>;
}
declare module 'dayjs/locale/sv.js' {
  declare module.exports: $Exports<'dayjs/locale/sv'>;
}
declare module 'dayjs/locale/sw.js' {
  declare module.exports: $Exports<'dayjs/locale/sw'>;
}
declare module 'dayjs/locale/ta.js' {
  declare module.exports: $Exports<'dayjs/locale/ta'>;
}
declare module 'dayjs/locale/te.js' {
  declare module.exports: $Exports<'dayjs/locale/te'>;
}
declare module 'dayjs/locale/tet.js' {
  declare module.exports: $Exports<'dayjs/locale/tet'>;
}
declare module 'dayjs/locale/tg.js' {
  declare module.exports: $Exports<'dayjs/locale/tg'>;
}
declare module 'dayjs/locale/th.js' {
  declare module.exports: $Exports<'dayjs/locale/th'>;
}
declare module 'dayjs/locale/tl-ph.js' {
  declare module.exports: $Exports<'dayjs/locale/tl-ph'>;
}
declare module 'dayjs/locale/tlh.js' {
  declare module.exports: $Exports<'dayjs/locale/tlh'>;
}
declare module 'dayjs/locale/tr.js' {
  declare module.exports: $Exports<'dayjs/locale/tr'>;
}
declare module 'dayjs/locale/tzl.js' {
  declare module.exports: $Exports<'dayjs/locale/tzl'>;
}
declare module 'dayjs/locale/tzm-latn.js' {
  declare module.exports: $Exports<'dayjs/locale/tzm-latn'>;
}
declare module 'dayjs/locale/tzm.js' {
  declare module.exports: $Exports<'dayjs/locale/tzm'>;
}
declare module 'dayjs/locale/ug-cn.js' {
  declare module.exports: $Exports<'dayjs/locale/ug-cn'>;
}
declare module 'dayjs/locale/uk.js' {
  declare module.exports: $Exports<'dayjs/locale/uk'>;
}
declare module 'dayjs/locale/ur.js' {
  declare module.exports: $Exports<'dayjs/locale/ur'>;
}
declare module 'dayjs/locale/uz-latn.js' {
  declare module.exports: $Exports<'dayjs/locale/uz-latn'>;
}
declare module 'dayjs/locale/uz.js' {
  declare module.exports: $Exports<'dayjs/locale/uz'>;
}
declare module 'dayjs/locale/vi.js' {
  declare module.exports: $Exports<'dayjs/locale/vi'>;
}
declare module 'dayjs/locale/x-pseudo.js' {
  declare module.exports: $Exports<'dayjs/locale/x-pseudo'>;
}
declare module 'dayjs/locale/yo.js' {
  declare module.exports: $Exports<'dayjs/locale/yo'>;
}
declare module 'dayjs/locale/zh-cn.js' {
  declare module.exports: $Exports<'dayjs/locale/zh-cn'>;
}
declare module 'dayjs/locale/zh-hk.js' {
  declare module.exports: $Exports<'dayjs/locale/zh-hk'>;
}
declare module 'dayjs/locale/zh-tw.js' {
  declare module.exports: $Exports<'dayjs/locale/zh-tw'>;
}
declare module 'dayjs/plugin/advancedFormat.js' {
  declare module.exports: $Exports<'dayjs/plugin/advancedFormat'>;
}
declare module 'dayjs/plugin/badMutable.js' {
  declare module.exports: $Exports<'dayjs/plugin/badMutable'>;
}
declare module 'dayjs/plugin/buddhistEra.js' {
  declare module.exports: $Exports<'dayjs/plugin/buddhistEra'>;
}
declare module 'dayjs/plugin/calendar.js' {
  declare module.exports: $Exports<'dayjs/plugin/calendar'>;
}
declare module 'dayjs/plugin/customParseFormat.js' {
  declare module.exports: $Exports<'dayjs/plugin/customParseFormat'>;
}
declare module 'dayjs/plugin/dayOfYear.js' {
  declare module.exports: $Exports<'dayjs/plugin/dayOfYear'>;
}
declare module 'dayjs/plugin/isBetween.js' {
  declare module.exports: $Exports<'dayjs/plugin/isBetween'>;
}
declare module 'dayjs/plugin/isLeapYear.js' {
  declare module.exports: $Exports<'dayjs/plugin/isLeapYear'>;
}
declare module 'dayjs/plugin/isMoment.js' {
  declare module.exports: $Exports<'dayjs/plugin/isMoment'>;
}
declare module 'dayjs/plugin/isoWeeksInYear.js' {
  declare module.exports: $Exports<'dayjs/plugin/isoWeeksInYear'>;
}
declare module 'dayjs/plugin/isSameOrAfter.js' {
  declare module.exports: $Exports<'dayjs/plugin/isSameOrAfter'>;
}
declare module 'dayjs/plugin/isSameOrBefore.js' {
  declare module.exports: $Exports<'dayjs/plugin/isSameOrBefore'>;
}
declare module 'dayjs/plugin/localeData.js' {
  declare module.exports: $Exports<'dayjs/plugin/localeData'>;
}
declare module 'dayjs/plugin/localizedFormat.js' {
  declare module.exports: $Exports<'dayjs/plugin/localizedFormat'>;
}
declare module 'dayjs/plugin/minMax.js' {
  declare module.exports: $Exports<'dayjs/plugin/minMax'>;
}
declare module 'dayjs/plugin/quarterOfYear.js' {
  declare module.exports: $Exports<'dayjs/plugin/quarterOfYear'>;
}
declare module 'dayjs/plugin/relativeTime.js' {
  declare module.exports: $Exports<'dayjs/plugin/relativeTime'>;
}
declare module 'dayjs/plugin/toArray.js' {
  declare module.exports: $Exports<'dayjs/plugin/toArray'>;
}
declare module 'dayjs/plugin/toObject.js' {
  declare module.exports: $Exports<'dayjs/plugin/toObject'>;
}
declare module 'dayjs/plugin/utc.js' {
  declare module.exports: $Exports<'dayjs/plugin/utc'>;
}
declare module 'dayjs/plugin/weekday.js' {
  declare module.exports: $Exports<'dayjs/plugin/weekday'>;
}
declare module 'dayjs/plugin/weekOfYear.js' {
  declare module.exports: $Exports<'dayjs/plugin/weekOfYear'>;
}
declare module 'dayjs/plugin/weekYear.js' {
  declare module.exports: $Exports<'dayjs/plugin/weekYear'>;
}
