// flow-typed signature: 34695ff5cb21d453bcba32c425dd9681
// flow-typed version: <<STUB>>/eslint-config-uber-universal-stage-3_v^1.0.0-rc.7/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-uber-universal-stage-3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-uber-universal-stage-3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'eslint-config-uber-universal-stage-3/index' {
  declare module.exports: $Exports<'eslint-config-uber-universal-stage-3'>;
}
declare module 'eslint-config-uber-universal-stage-3/index.js' {
  declare module.exports: $Exports<'eslint-config-uber-universal-stage-3'>;
}
