// flow-typed signature: 565b1a9a1a4ab969a6e11dc1ea26403e
// flow-typed version: <<STUB>>/focus-trap-react_v^6.0.0/flow_v0.101.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'focus-trap-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'focus-trap-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'focus-trap-react/dist/focus-trap-react' {
  declare module.exports: any;
}

declare module 'focus-trap-react/src/focus-trap-react' {
  declare module.exports: any;
}

// Filename aliases
declare module 'focus-trap-react/dist/focus-trap-react.js' {
  declare module.exports: $Exports<'focus-trap-react/dist/focus-trap-react'>;
}
declare module 'focus-trap-react/src/focus-trap-react.js' {
  declare module.exports: $Exports<'focus-trap-react/src/focus-trap-react'>;
}
