// flow-typed signature: b1c4fcbe9bc81959a433026527b871db
// flow-typed version: <<STUB>>/just-extend_v^4.0.2/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'just-extend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'just-extend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'just-extend/index' {
  declare module.exports: $Exports<'just-extend'>;
}
declare module 'just-extend/index.js' {
  declare module.exports: $Exports<'just-extend'>;
}
