// flow-typed signature: 00f597580819bf39ddf5c21886ba32e3
// flow-typed version: <<STUB>>/pretty-quick_v^1.4.1/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-quick'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-quick' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pretty-quick/bin/pretty-quick' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/createIgnorer' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/formatFiles' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/index' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/isSupportedExtension' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/scms/git' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/scms/hg' {
  declare module.exports: any;
}

declare module 'pretty-quick/dist/scms/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pretty-quick/bin/pretty-quick.js' {
  declare module.exports: $Exports<'pretty-quick/bin/pretty-quick'>;
}
declare module 'pretty-quick/dist/createIgnorer.js' {
  declare module.exports: $Exports<'pretty-quick/dist/createIgnorer'>;
}
declare module 'pretty-quick/dist/formatFiles.js' {
  declare module.exports: $Exports<'pretty-quick/dist/formatFiles'>;
}
declare module 'pretty-quick/dist/index.js' {
  declare module.exports: $Exports<'pretty-quick/dist/index'>;
}
declare module 'pretty-quick/dist/isSupportedExtension.js' {
  declare module.exports: $Exports<'pretty-quick/dist/isSupportedExtension'>;
}
declare module 'pretty-quick/dist/scms/git.js' {
  declare module.exports: $Exports<'pretty-quick/dist/scms/git'>;
}
declare module 'pretty-quick/dist/scms/hg.js' {
  declare module.exports: $Exports<'pretty-quick/dist/scms/hg'>;
}
declare module 'pretty-quick/dist/scms/index.js' {
  declare module.exports: $Exports<'pretty-quick/dist/scms/index'>;
}
