// flow-typed signature: 0016c5ccc71e9bdbd430585f35fad3df
// flow-typed version: <<STUB>>/react-range_v^1.0.5/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-range'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-range' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-range/lib/index' {
  declare module.exports: any;
}

declare module 'react-range/lib/Range.flow' {
  declare module.exports: any;
}

declare module 'react-range/lib/Range' {
  declare module.exports: any;
}

declare module 'react-range/lib/types' {
  declare module.exports: any;
}

declare module 'react-range/lib/utils.flow' {
  declare module.exports: any;
}

declare module 'react-range/lib/utils' {
  declare module.exports: any;
}

declare module 'react-range/lib/utils.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-range/lib/index.js' {
  declare module.exports: $Exports<'react-range/lib/index'>;
}
declare module 'react-range/lib/Range.flow.js' {
  declare module.exports: $Exports<'react-range/lib/Range.flow'>;
}
declare module 'react-range/lib/Range.js' {
  declare module.exports: $Exports<'react-range/lib/Range'>;
}
declare module 'react-range/lib/types.js' {
  declare module.exports: $Exports<'react-range/lib/types'>;
}
declare module 'react-range/lib/utils.flow.js' {
  declare module.exports: $Exports<'react-range/lib/utils.flow'>;
}
declare module 'react-range/lib/utils.js' {
  declare module.exports: $Exports<'react-range/lib/utils'>;
}
declare module 'react-range/lib/utils.test.js' {
  declare module.exports: $Exports<'react-range/lib/utils.test'>;
}
