// flow-typed signature: 8a70e4d8bdf64c4260b074d12148d2d9
// flow-typed version: <<STUB>>/react-uid_v2.3.0/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-uid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-uid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-uid/dist/es2015/context' {
  declare module.exports: any;
}

declare module 'react-uid/dist/es2015/Control' {
  declare module.exports: any;
}

declare module 'react-uid/dist/es2015/hooks' {
  declare module.exports: any;
}

declare module 'react-uid/dist/es2015' {
  declare module.exports: any;
}

declare module 'react-uid/dist/es2015/uid' {
  declare module.exports: any;
}

declare module 'react-uid/dist/es2015/UIDComponent' {
  declare module.exports: any;
}

declare module 'react-uid/dist/es5/context' {
  declare module.exports: any;
}

declare module 'react-uid/dist/es5/Control' {
  declare module.exports: any;
}

declare module 'react-uid/dist/es5/hooks' {
  declare module.exports: any;
}

declare module 'react-uid/dist/es5' {
  declare module.exports: any;
}

declare module 'react-uid/dist/es5/uid' {
  declare module.exports: any;
}

declare module 'react-uid/dist/es5/UIDComponent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-uid/dist/es2015/context.js' {
  declare module.exports: $Exports<'react-uid/dist/es2015/context'>;
}
declare module 'react-uid/dist/es2015/Control.js' {
  declare module.exports: $Exports<'react-uid/dist/es2015/Control'>;
}
declare module 'react-uid/dist/es2015/hooks.js' {
  declare module.exports: $Exports<'react-uid/dist/es2015/hooks'>;
}
declare module 'react-uid/dist/es2015/index' {
  declare module.exports: $Exports<'react-uid/dist/es2015'>;
}
declare module 'react-uid/dist/es2015/index.js' {
  declare module.exports: $Exports<'react-uid/dist/es2015'>;
}
declare module 'react-uid/dist/es2015/uid.js' {
  declare module.exports: $Exports<'react-uid/dist/es2015/uid'>;
}
declare module 'react-uid/dist/es2015/UIDComponent.js' {
  declare module.exports: $Exports<'react-uid/dist/es2015/UIDComponent'>;
}
declare module 'react-uid/dist/es5/context.js' {
  declare module.exports: $Exports<'react-uid/dist/es5/context'>;
}
declare module 'react-uid/dist/es5/Control.js' {
  declare module.exports: $Exports<'react-uid/dist/es5/Control'>;
}
declare module 'react-uid/dist/es5/hooks.js' {
  declare module.exports: $Exports<'react-uid/dist/es5/hooks'>;
}
declare module 'react-uid/dist/es5/index' {
  declare module.exports: $Exports<'react-uid/dist/es5'>;
}
declare module 'react-uid/dist/es5/index.js' {
  declare module.exports: $Exports<'react-uid/dist/es5'>;
}
declare module 'react-uid/dist/es5/uid.js' {
  declare module.exports: $Exports<'react-uid/dist/es5/uid'>;
}
declare module 'react-uid/dist/es5/UIDComponent.js' {
  declare module.exports: $Exports<'react-uid/dist/es5/UIDComponent'>;
}
