// flow-typed signature: c29679a989993a6d622ea5c6d7ae21a1
// flow-typed version: <<STUB>>/react-focus-lock_v2.7.1/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-focus-lock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-focus-lock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-focus-lock/dist/cjs/AutoFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/clientSideEffect' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/Combination' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/FocusGuard' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/FreeFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/Lock' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/medium' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/MoveFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/sidecar' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/Trap' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/UI' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/cjs/util' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/AutoFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/clientSideEffect' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/Combination' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/FocusGuard' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/FreeFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/Lock' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/medium' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/MoveFocusInside' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/sidecar' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/Trap' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/UI' {
  declare module.exports: any;
}

declare module 'react-focus-lock/dist/es2015/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-focus-lock/dist/cjs/AutoFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/AutoFocusInside'>;
}
declare module 'react-focus-lock/dist/cjs/clientSideEffect.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/clientSideEffect'>;
}
declare module 'react-focus-lock/dist/cjs/Combination.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/Combination'>;
}
declare module 'react-focus-lock/dist/cjs/FocusGuard.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/FocusGuard'>;
}
declare module 'react-focus-lock/dist/cjs/FreeFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/FreeFocusInside'>;
}
declare module 'react-focus-lock/dist/cjs/index' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs'>;
}
declare module 'react-focus-lock/dist/cjs/index.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs'>;
}
declare module 'react-focus-lock/dist/cjs/Lock.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/Lock'>;
}
declare module 'react-focus-lock/dist/cjs/medium.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/medium'>;
}
declare module 'react-focus-lock/dist/cjs/MoveFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/MoveFocusInside'>;
}
declare module 'react-focus-lock/dist/cjs/sidecar.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/sidecar'>;
}
declare module 'react-focus-lock/dist/cjs/Trap.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/Trap'>;
}
declare module 'react-focus-lock/dist/cjs/UI.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/UI'>;
}
declare module 'react-focus-lock/dist/cjs/util.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/cjs/util'>;
}
declare module 'react-focus-lock/dist/es2015/AutoFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/AutoFocusInside'>;
}
declare module 'react-focus-lock/dist/es2015/clientSideEffect.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/clientSideEffect'>;
}
declare module 'react-focus-lock/dist/es2015/Combination.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/Combination'>;
}
declare module 'react-focus-lock/dist/es2015/FocusGuard.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/FocusGuard'>;
}
declare module 'react-focus-lock/dist/es2015/FreeFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/FreeFocusInside'>;
}
declare module 'react-focus-lock/dist/es2015/index' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015'>;
}
declare module 'react-focus-lock/dist/es2015/index.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015'>;
}
declare module 'react-focus-lock/dist/es2015/Lock.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/Lock'>;
}
declare module 'react-focus-lock/dist/es2015/medium.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/medium'>;
}
declare module 'react-focus-lock/dist/es2015/MoveFocusInside.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/MoveFocusInside'>;
}
declare module 'react-focus-lock/dist/es2015/sidecar.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/sidecar'>;
}
declare module 'react-focus-lock/dist/es2015/Trap.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/Trap'>;
}
declare module 'react-focus-lock/dist/es2015/UI.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/UI'>;
}
declare module 'react-focus-lock/dist/es2015/util.js' {
  declare module.exports: $Exports<'react-focus-lock/dist/es2015/util'>;
}
