// flow-typed signature: 649bace722b56a4b5a25c27c4d58ab68
// flow-typed version: <<STUB>>/react-view_v2.3.3/flow_v0.131.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-view'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-view' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-view/dist/es/actions' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/ast' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/code-generator' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/const' {
  declare module.exports: any;
}

declare module 'react-view/dist/es' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/light-theme' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/reducer' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/snippets/__tests__/vscode-snippet.test' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/snippets/vscode-snippet' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/types' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/ui/action-buttons' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/ui/compiler' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/ui/editor' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/ui/error' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/ui/knob' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/ui/knobs' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/ui/placeholder' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/ui/view' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/use-view' {
  declare module.exports: any;
}

declare module 'react-view/dist/es/utils' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/actions' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/ast' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/code-generator' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/const' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/light-theme' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/reducer' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/snippets/__tests__/vscode-snippet.test' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/snippets/vscode-snippet' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/types' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/ui/action-buttons' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/ui/compiler' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/ui/editor' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/ui/error' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/ui/knob' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/ui/knobs' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/ui/placeholder' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/ui/view' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/use-view' {
  declare module.exports: any;
}

declare module 'react-view/dist/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-view/dist/es/actions.js' {
  declare module.exports: $Exports<'react-view/dist/es/actions'>;
}
declare module 'react-view/dist/es/ast.js' {
  declare module.exports: $Exports<'react-view/dist/es/ast'>;
}
declare module 'react-view/dist/es/code-generator.js' {
  declare module.exports: $Exports<'react-view/dist/es/code-generator'>;
}
declare module 'react-view/dist/es/const.js' {
  declare module.exports: $Exports<'react-view/dist/es/const'>;
}
declare module 'react-view/dist/es/index' {
  declare module.exports: $Exports<'react-view/dist/es'>;
}
declare module 'react-view/dist/es/index.js' {
  declare module.exports: $Exports<'react-view/dist/es'>;
}
declare module 'react-view/dist/es/light-theme.js' {
  declare module.exports: $Exports<'react-view/dist/es/light-theme'>;
}
declare module 'react-view/dist/es/reducer.js' {
  declare module.exports: $Exports<'react-view/dist/es/reducer'>;
}
declare module 'react-view/dist/es/snippets/__tests__/vscode-snippet.test.js' {
  declare module.exports: $Exports<'react-view/dist/es/snippets/__tests__/vscode-snippet.test'>;
}
declare module 'react-view/dist/es/snippets/vscode-snippet.js' {
  declare module.exports: $Exports<'react-view/dist/es/snippets/vscode-snippet'>;
}
declare module 'react-view/dist/es/types.js' {
  declare module.exports: $Exports<'react-view/dist/es/types'>;
}
declare module 'react-view/dist/es/ui/action-buttons.js' {
  declare module.exports: $Exports<'react-view/dist/es/ui/action-buttons'>;
}
declare module 'react-view/dist/es/ui/compiler.js' {
  declare module.exports: $Exports<'react-view/dist/es/ui/compiler'>;
}
declare module 'react-view/dist/es/ui/editor.js' {
  declare module.exports: $Exports<'react-view/dist/es/ui/editor'>;
}
declare module 'react-view/dist/es/ui/error.js' {
  declare module.exports: $Exports<'react-view/dist/es/ui/error'>;
}
declare module 'react-view/dist/es/ui/knob.js' {
  declare module.exports: $Exports<'react-view/dist/es/ui/knob'>;
}
declare module 'react-view/dist/es/ui/knobs.js' {
  declare module.exports: $Exports<'react-view/dist/es/ui/knobs'>;
}
declare module 'react-view/dist/es/ui/placeholder.js' {
  declare module.exports: $Exports<'react-view/dist/es/ui/placeholder'>;
}
declare module 'react-view/dist/es/ui/view.js' {
  declare module.exports: $Exports<'react-view/dist/es/ui/view'>;
}
declare module 'react-view/dist/es/use-view.js' {
  declare module.exports: $Exports<'react-view/dist/es/use-view'>;
}
declare module 'react-view/dist/es/utils.js' {
  declare module.exports: $Exports<'react-view/dist/es/utils'>;
}
declare module 'react-view/dist/lib/actions.js' {
  declare module.exports: $Exports<'react-view/dist/lib/actions'>;
}
declare module 'react-view/dist/lib/ast.js' {
  declare module.exports: $Exports<'react-view/dist/lib/ast'>;
}
declare module 'react-view/dist/lib/code-generator.js' {
  declare module.exports: $Exports<'react-view/dist/lib/code-generator'>;
}
declare module 'react-view/dist/lib/const.js' {
  declare module.exports: $Exports<'react-view/dist/lib/const'>;
}
declare module 'react-view/dist/lib/index' {
  declare module.exports: $Exports<'react-view/dist/lib'>;
}
declare module 'react-view/dist/lib/index.js' {
  declare module.exports: $Exports<'react-view/dist/lib'>;
}
declare module 'react-view/dist/lib/light-theme.js' {
  declare module.exports: $Exports<'react-view/dist/lib/light-theme'>;
}
declare module 'react-view/dist/lib/reducer.js' {
  declare module.exports: $Exports<'react-view/dist/lib/reducer'>;
}
declare module 'react-view/dist/lib/snippets/__tests__/vscode-snippet.test.js' {
  declare module.exports: $Exports<'react-view/dist/lib/snippets/__tests__/vscode-snippet.test'>;
}
declare module 'react-view/dist/lib/snippets/vscode-snippet.js' {
  declare module.exports: $Exports<'react-view/dist/lib/snippets/vscode-snippet'>;
}
declare module 'react-view/dist/lib/types.js' {
  declare module.exports: $Exports<'react-view/dist/lib/types'>;
}
declare module 'react-view/dist/lib/ui/action-buttons.js' {
  declare module.exports: $Exports<'react-view/dist/lib/ui/action-buttons'>;
}
declare module 'react-view/dist/lib/ui/compiler.js' {
  declare module.exports: $Exports<'react-view/dist/lib/ui/compiler'>;
}
declare module 'react-view/dist/lib/ui/editor.js' {
  declare module.exports: $Exports<'react-view/dist/lib/ui/editor'>;
}
declare module 'react-view/dist/lib/ui/error.js' {
  declare module.exports: $Exports<'react-view/dist/lib/ui/error'>;
}
declare module 'react-view/dist/lib/ui/knob.js' {
  declare module.exports: $Exports<'react-view/dist/lib/ui/knob'>;
}
declare module 'react-view/dist/lib/ui/knobs.js' {
  declare module.exports: $Exports<'react-view/dist/lib/ui/knobs'>;
}
declare module 'react-view/dist/lib/ui/placeholder.js' {
  declare module.exports: $Exports<'react-view/dist/lib/ui/placeholder'>;
}
declare module 'react-view/dist/lib/ui/view.js' {
  declare module.exports: $Exports<'react-view/dist/lib/ui/view'>;
}
declare module 'react-view/dist/lib/use-view.js' {
  declare module.exports: $Exports<'react-view/dist/lib/use-view'>;
}
declare module 'react-view/dist/lib/utils.js' {
  declare module.exports: $Exports<'react-view/dist/lib/utils'>;
}
