// flow-typed signature: e2c96a74ed4325f2a21256cbe3190ab5
// flow-typed version: <<STUB>>/react-input-mask_v^2.0.4/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-input-mask'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-input-mask' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-input-mask/dist/react-input-mask' {
  declare module.exports: any;
}

declare module 'react-input-mask/dist/react-input-mask.min' {
  declare module.exports: any;
}

declare module 'react-input-mask/lib/react-input-mask.development' {
  declare module.exports: any;
}

declare module 'react-input-mask/lib/react-input-mask.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-input-mask/dist/react-input-mask.js' {
  declare module.exports: $Exports<'react-input-mask/dist/react-input-mask'>;
}
declare module 'react-input-mask/dist/react-input-mask.min.js' {
  declare module.exports: $Exports<
    'react-input-mask/dist/react-input-mask.min',
  >;
}
declare module 'react-input-mask/index' {
  declare module.exports: $Exports<'react-input-mask'>;
}
declare module 'react-input-mask/index.js' {
  declare module.exports: $Exports<'react-input-mask'>;
}
declare module 'react-input-mask/lib/react-input-mask.development.js' {
  declare module.exports: $Exports<
    'react-input-mask/lib/react-input-mask.development',
  >;
}
declare module 'react-input-mask/lib/react-input-mask.production.min.js' {
  declare module.exports: $Exports<
    'react-input-mask/lib/react-input-mask.production.min',
  >;
}
