// flow-typed signature: e8747534cae579e4caa99b6e19a93db2
// flow-typed version: <<STUB>>/react-markdown_v^4.0.3/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-markdown/lib/ast-to-react' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/get-definitions' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/plugins/disallow-node' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/plugins/html-parser' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/plugins/naive-html' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/react-markdown' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/renderers' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/symbols' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/uri-transformer' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/with-html' {
  declare module.exports: any;
}

declare module 'react-markdown/lib/wrap-table-rows' {
  declare module.exports: any;
}

declare module 'react-markdown/plugins/html-parser' {
  declare module.exports: any;
}

declare module 'react-markdown/umd/react-markdown' {
  declare module.exports: any;
}

declare module 'react-markdown/with-html' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-markdown/lib/ast-to-react.js' {
  declare module.exports: $Exports<'react-markdown/lib/ast-to-react'>;
}
declare module 'react-markdown/lib/get-definitions.js' {
  declare module.exports: $Exports<'react-markdown/lib/get-definitions'>;
}
declare module 'react-markdown/lib/plugins/disallow-node.js' {
  declare module.exports: $Exports<'react-markdown/lib/plugins/disallow-node'>;
}
declare module 'react-markdown/lib/plugins/html-parser.js' {
  declare module.exports: $Exports<'react-markdown/lib/plugins/html-parser'>;
}
declare module 'react-markdown/lib/plugins/naive-html.js' {
  declare module.exports: $Exports<'react-markdown/lib/plugins/naive-html'>;
}
declare module 'react-markdown/lib/react-markdown.js' {
  declare module.exports: $Exports<'react-markdown/lib/react-markdown'>;
}
declare module 'react-markdown/lib/renderers.js' {
  declare module.exports: $Exports<'react-markdown/lib/renderers'>;
}
declare module 'react-markdown/lib/symbols.js' {
  declare module.exports: $Exports<'react-markdown/lib/symbols'>;
}
declare module 'react-markdown/lib/uri-transformer.js' {
  declare module.exports: $Exports<'react-markdown/lib/uri-transformer'>;
}
declare module 'react-markdown/lib/with-html.js' {
  declare module.exports: $Exports<'react-markdown/lib/with-html'>;
}
declare module 'react-markdown/lib/wrap-table-rows.js' {
  declare module.exports: $Exports<'react-markdown/lib/wrap-table-rows'>;
}
declare module 'react-markdown/plugins/html-parser.js' {
  declare module.exports: $Exports<'react-markdown/plugins/html-parser'>;
}
declare module 'react-markdown/umd/react-markdown.js' {
  declare module.exports: $Exports<'react-markdown/umd/react-markdown'>;
}
declare module 'react-markdown/with-html.js' {
  declare module.exports: $Exports<'react-markdown/with-html'>;
}
