// flow-typed signature: 79167e33e6b1fea96c66406f94109c28
// flow-typed version: <<STUB>>/screener-storybook_v^0.17.6/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'screener-storybook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'screener-storybook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'screener-storybook/bin/screener-storybook' {
  declare module.exports: any;
}

declare module 'screener-storybook/src/check' {
  declare module.exports: any;
}

declare module 'screener-storybook/src/cli' {
  declare module.exports: any;
}

declare module 'screener-storybook/src/index' {
  declare module.exports: any;
}

declare module 'screener-storybook/src/runner' {
  declare module.exports: any;
}

declare module 'screener-storybook/src/screener' {
  declare module.exports: any;
}

declare module 'screener-storybook/src/scripts/story-steps' {
  declare module.exports: any;
}

declare module 'screener-storybook/src/storybook' {
  declare module.exports: any;
}

declare module 'screener-storybook/src/validate' {
  declare module.exports: any;
}

declare module 'screener-storybook/test/check.spec' {
  declare module.exports: any;
}

declare module 'screener-storybook/test/runner.spec' {
  declare module.exports: any;
}

declare module 'screener-storybook/test/story-steps.spec' {
  declare module.exports: any;
}

declare module 'screener-storybook/test/validate.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'screener-storybook/bin/screener-storybook.js' {
  declare module.exports: $Exports<'screener-storybook/bin/screener-storybook'>;
}
declare module 'screener-storybook/index' {
  declare module.exports: $Exports<'screener-storybook'>;
}
declare module 'screener-storybook/index.js' {
  declare module.exports: $Exports<'screener-storybook'>;
}
declare module 'screener-storybook/src/check.js' {
  declare module.exports: $Exports<'screener-storybook/src/check'>;
}
declare module 'screener-storybook/src/cli.js' {
  declare module.exports: $Exports<'screener-storybook/src/cli'>;
}
declare module 'screener-storybook/src/index.js' {
  declare module.exports: $Exports<'screener-storybook/src/index'>;
}
declare module 'screener-storybook/src/runner.js' {
  declare module.exports: $Exports<'screener-storybook/src/runner'>;
}
declare module 'screener-storybook/src/screener.js' {
  declare module.exports: $Exports<'screener-storybook/src/screener'>;
}
declare module 'screener-storybook/src/scripts/story-steps.js' {
  declare module.exports: $Exports<
    'screener-storybook/src/scripts/story-steps',
  >;
}
declare module 'screener-storybook/src/storybook.js' {
  declare module.exports: $Exports<'screener-storybook/src/storybook'>;
}
declare module 'screener-storybook/src/validate.js' {
  declare module.exports: $Exports<'screener-storybook/src/validate'>;
}
declare module 'screener-storybook/test/check.spec.js' {
  declare module.exports: $Exports<'screener-storybook/test/check.spec'>;
}
declare module 'screener-storybook/test/runner.spec.js' {
  declare module.exports: $Exports<'screener-storybook/test/runner.spec'>;
}
declare module 'screener-storybook/test/story-steps.spec.js' {
  declare module.exports: $Exports<'screener-storybook/test/story-steps.spec'>;
}
declare module 'screener-storybook/test/validate.spec.js' {
  declare module.exports: $Exports<'screener-storybook/test/validate.spec'>;
}
