// flow-typed signature: 98e6735b891506e56e3c7981492c341c
// flow-typed version: <<STUB>>/tar_v^4.4.8/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tar/lib/buffer' {
  declare module.exports: any;
}

declare module 'tar/lib/create' {
  declare module.exports: any;
}

declare module 'tar/lib/extract' {
  declare module.exports: any;
}

declare module 'tar/lib/header' {
  declare module.exports: any;
}

declare module 'tar/lib/high-level-opt' {
  declare module.exports: any;
}

declare module 'tar/lib/large-numbers' {
  declare module.exports: any;
}

declare module 'tar/lib/list' {
  declare module.exports: any;
}

declare module 'tar/lib/mkdir' {
  declare module.exports: any;
}

declare module 'tar/lib/mode-fix' {
  declare module.exports: any;
}

declare module 'tar/lib/pack' {
  declare module.exports: any;
}

declare module 'tar/lib/parse' {
  declare module.exports: any;
}

declare module 'tar/lib/pax' {
  declare module.exports: any;
}

declare module 'tar/lib/read-entry' {
  declare module.exports: any;
}

declare module 'tar/lib/replace' {
  declare module.exports: any;
}

declare module 'tar/lib/types' {
  declare module.exports: any;
}

declare module 'tar/lib/unpack' {
  declare module.exports: any;
}

declare module 'tar/lib/update' {
  declare module.exports: any;
}

declare module 'tar/lib/warn-mixin' {
  declare module.exports: any;
}

declare module 'tar/lib/winchars' {
  declare module.exports: any;
}

declare module 'tar/lib/write-entry' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tar/index' {
  declare module.exports: $Exports<'tar'>;
}
declare module 'tar/index.js' {
  declare module.exports: $Exports<'tar'>;
}
declare module 'tar/lib/buffer.js' {
  declare module.exports: $Exports<'tar/lib/buffer'>;
}
declare module 'tar/lib/create.js' {
  declare module.exports: $Exports<'tar/lib/create'>;
}
declare module 'tar/lib/extract.js' {
  declare module.exports: $Exports<'tar/lib/extract'>;
}
declare module 'tar/lib/header.js' {
  declare module.exports: $Exports<'tar/lib/header'>;
}
declare module 'tar/lib/high-level-opt.js' {
  declare module.exports: $Exports<'tar/lib/high-level-opt'>;
}
declare module 'tar/lib/large-numbers.js' {
  declare module.exports: $Exports<'tar/lib/large-numbers'>;
}
declare module 'tar/lib/list.js' {
  declare module.exports: $Exports<'tar/lib/list'>;
}
declare module 'tar/lib/mkdir.js' {
  declare module.exports: $Exports<'tar/lib/mkdir'>;
}
declare module 'tar/lib/mode-fix.js' {
  declare module.exports: $Exports<'tar/lib/mode-fix'>;
}
declare module 'tar/lib/pack.js' {
  declare module.exports: $Exports<'tar/lib/pack'>;
}
declare module 'tar/lib/parse.js' {
  declare module.exports: $Exports<'tar/lib/parse'>;
}
declare module 'tar/lib/pax.js' {
  declare module.exports: $Exports<'tar/lib/pax'>;
}
declare module 'tar/lib/read-entry.js' {
  declare module.exports: $Exports<'tar/lib/read-entry'>;
}
declare module 'tar/lib/replace.js' {
  declare module.exports: $Exports<'tar/lib/replace'>;
}
declare module 'tar/lib/types.js' {
  declare module.exports: $Exports<'tar/lib/types'>;
}
declare module 'tar/lib/unpack.js' {
  declare module.exports: $Exports<'tar/lib/unpack'>;
}
declare module 'tar/lib/update.js' {
  declare module.exports: $Exports<'tar/lib/update'>;
}
declare module 'tar/lib/warn-mixin.js' {
  declare module.exports: $Exports<'tar/lib/warn-mixin'>;
}
declare module 'tar/lib/winchars.js' {
  declare module.exports: $Exports<'tar/lib/winchars'>;
}
declare module 'tar/lib/write-entry.js' {
  declare module.exports: $Exports<'tar/lib/write-entry'>;
}
