steps:
  # Build the image in a single place for all parallel steps to leverage the same image.
  - name: ':docker: :package: build web-base-image'
    plugins:
      'docker-compose#v3.0.3':
        build:
          - baseui
          - e2e-server
          - e2e-server-healthy
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
        env: DOCKER_BUILDKIT=1
    agents:
      queue: builders

  - name: ':docker: :package: build playwright'
    plugins:
      'docker-compose#v3.0.3':
        build:
          - e2e-test
        image-repository: 027047743804.dkr.ecr.us-east-2.amazonaws.com/uber
        env: DOCKER_BUILDKIT=1
    agents:
      queue: builders

  # Wait until all images are built.
  # This way we can download the built image from a registry instead of building each for each test task.
  - wait

  # All of the commands after the wait are run in parallel.
  - name: validate-examples
    command: yarn validate:examples
    plugins:
      'docker-compose#v3.0.3':
        run: baseui
    agents:
      queue: workers

  - name: ':typescript:'
    command: yarn tsc
    plugins:
      'docker-compose#v3.0.3':
        run: baseui
    agents:
      queue: workers

  - name: ':eslint:'
    command: yarn lint
    plugins:
      'docker-compose#v3.0.3':
        run: baseui
    agents:
      queue: workers

  - name: ':flowtype:'
    command: yarn flow
    plugins:
      'docker-compose#v3.0.3':
        run: baseui
    agents:
      queue: workers

  - name: ':jest:'
    command: yarn unit-test
    plugins:
      'docker-compose#v3.0.3':
        run: baseui
    agents:
      queue: workers

  - name: ':react: react@18 unit-test'
    command: yarn upgrade react@^18.0.0 react-dom@^18.0.0 @testing-library/react@alpha && yarn unit-test
    plugins:
      'docker-compose#v3.0.3':
        run: baseui
    agents:
      queue: workers

  - name: fossa
    command: 'curl https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash && fossa'
    plugins:
      'docker-compose#v3.0.3':
        run: baseui
    agents:
      queue: workers

  - name: deploy-npm-latest
    command: 'node scripts/publish-stable-release.js'
    if: build.branch == "master" && build.message =~ /^Release v[0-9]+\.[0-9]+\.[0-9]+/
    plugins:
      'docker-compose#v3.0.3':
        run: baseui
    agents:
      queue: workers

  - name: deploy-npm-next
    command: 'node scripts/publish-bleeding-edge.js'
    if: build.branch == "master" && build.message !~ /^Release v[0-9]+\.[0-9]+\.[0-9]+/
    plugins:
      'docker-compose#v3.0.3':
        run: baseui
    agents:
      queue: workers

  # vscode extension deployment disabled until we can refresh the azure token
  # - name: deploy-vscode
  #   command: './deploy-vscode.sh'
  #   if: build.branch == "master" && build.message =~ /^Release v[0-9]+\.[0-9]+\.[0-9]+/
  #   plugins:
  #     'docker-compose#v3.0.3':
  #       run: baseui
  #   agents:
  #     queue: workers

  - name: create-github-release
    command: './scripts/github-release.js'
    if: build.branch == "master" && build.message =~ /^Release v[0-9]+\.[0-9]+\.[0-9]+/
    plugins:
      'docker-compose#v3.0.3':
        run: baseui
    agents:
      queue: workers

  - name: e2e
    command: yarn e2e:test:ci
    artifact_paths:
      - 'test-results/**/*'
    plugins:
      'docker-compose#v3.0.3':
        run: e2e-test
        pull:
          - e2e-server
          - e2e-server-healthy
    agents:
      queue: workers

  - name: ':react: react@18 e2e'
    command: yarn upgrade react@^18.0.0 react-dom@^18.0.0 && yarn e2e:test:ci
    artifact_paths:
      - 'test-results/**/*'
    plugins:
      'docker-compose#v3.0.3':
        run: e2e-test
        pull:
          - e2e-server
          - e2e-server-healthy
    agents:
      queue: workers

  - name: vrt
    command: yarn vrt:ci
    artifact_paths:
      - 'test-results/**/*'
    plugins:
      'docker-compose#v3.0.3':
        run: e2e-test
        pull:
          - e2e-server
          - e2e-server-healthy
    agents:
      queue: workers

  - name: 'bundle size'
    command: 'node --unhandled-rejections=strict scripts/collect-bundle-sizes.js'
    artifact_paths:
      - '__artifacts__/bundle-size/*'
    soft_fail:
      - exit_status: 2
    plugins:
      'docker-compose#v3.0.3':
        run: e2e-test
    agents:
      queue: workers

  - block: 'Alpha test'
    blocked_state: 'passed'

  - name: alpha-test-web-code
    command: 'node --unhandled-rejections=strict scripts/alpha-test-web-code.js'
    plugins:
      'docker-compose#v3.0.3':
        run: baseui
    agents:
      queue: workers
