import * as React from 'react';
import {BlockProps} from '../block';

export const DisplayLarge: React.FC<BlockProps>;
export const DisplayMedium: React.FC<BlockProps>;
export const DisplaySmall: React.FC<BlockProps>;
export const DisplayXSmall: React.FC<BlockProps>;
export const HeadingXXLarge: React.FC<BlockProps>;
export const HeadingXLarge: React.FC<BlockProps>;
export const HeadingLarge: React.FC<BlockProps>;
export const HeadingMedium: React.FC<BlockProps>;
export const HeadingSmall: React.FC<BlockProps>;
export const HeadingXSmall: React.FC<BlockProps>;
export const LabelLarge: React.FC<BlockProps>;
export const LabelMedium: React.FC<BlockProps>;
export const LabelSmall: React.FC<BlockProps>;
export const LabelXSmall: React.FC<BlockProps>;
export const ParagraphLarge: React.FC<BlockProps>;
export const ParagraphMedium: React.FC<BlockProps>;
export const ParagraphSmall: React.FC<BlockProps>;
export const ParagraphXSmall: React.FC<BlockProps>;

// TODO(v10): remove
export const Caption1: React.FC<BlockProps>;
export const Caption2: React.FC<BlockProps>;
export const Display: React.FC<BlockProps>;
export const Display1: React.FC<BlockProps>;
export const Display2: React.FC<BlockProps>;
export const Display3: React.FC<BlockProps>;
export const Display4: React.FC<BlockProps>;
export const H1: React.FC<BlockProps>;
export const H2: React.FC<BlockProps>;
export const H3: React.FC<BlockProps>;
export const H4: React.FC<BlockProps>;
export const H5: React.FC<BlockProps>;
export const H6: React.FC<BlockProps>;
export const Label1: React.FC<BlockProps>;
export const Label2: React.FC<BlockProps>;
export const Label3: React.FC<BlockProps>;
export const Label4: React.FC<BlockProps>;
export const Paragraph1: React.FC<BlockProps>;
export const Paragraph2: React.FC<BlockProps>;
export const Paragraph3: React.FC<BlockProps>;
export const Paragraph4: React.FC<BlockProps>;
