import * as React from 'react';
import {BlockProps} from '../block';

export const Caption1: React.FC<BlockProps>;
export const Caption2: React.FC<BlockProps>;
export const Display: React.FC<BlockProps>;
export const Display1: React.FC<BlockProps>;
export const Display2: React.FC<BlockProps>;
export const Display3: React.FC<BlockProps>;
export const Display4: React.FC<BlockProps>;
export const H1: React.FC<BlockProps>;
export const H2: React.FC<BlockProps>;
export const H3: React.FC<BlockProps>;
export const H4: React.FC<BlockProps>;
export const H5: React.FC<BlockProps>;
export const H6: React.FC<BlockProps>;
export const Label1: React.FC<BlockProps>;
export const Label2: React.FC<BlockProps>;
export const Label3: React.FC<BlockProps>;
export const Label4: React.FC<BlockProps>;
export const Paragraph1: React.FC<BlockProps>;
export const Paragraph2: React.FC<BlockProps>;
export const Paragraph3: React.FC<BlockProps>;
export const Paragraph4: React.FC<BlockProps>;
