/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
export {SIZE} from '../input/constants.js';

// List originally from [jackocnr/intl-tel-input](https://github.com/jackocnr/intl-tel-input)
export const countries = {
  AF: {name: 'Afghanistan (‫افغانستان‬‎)', iso2: 'AF', dialCode: '93'},
  AL: {name: 'Albania (Shqipëri)', iso2: 'AL', dialCode: '355'},
  DZ: {name: 'Algeria (‫الجزائر‬‎)', iso2: 'DZ', dialCode: '213'},
  AS: {name: 'American Samoa', iso2: 'AS', dialCode: '1684'},
  AD: {name: 'Andorra', iso2: 'AD', dialCode: '376'},
  AO: {name: 'Angola', iso2: 'AO', dialCode: '244'},
  AI: {name: 'Anguilla', iso2: 'AI', dialCode: '1264'},
  AG: {name: 'Antigua and Barbuda', iso2: 'AG', dialCode: '1268'},
  AR: {name: 'Argentina', iso2: 'AR', dialCode: '54'},
  AM: {name: 'Armenia (Հայաստան)', iso2: 'AM', dialCode: '374'},
  AW: {name: 'Aruba', iso2: 'AW', dialCode: '297'},
  AU: {name: 'Australia', iso2: 'AU', dialCode: '61'},
  AT: {name: 'Austria (Österreich)', iso2: 'AT', dialCode: '43'},
  AZ: {name: 'Azerbaijan (Azərbaycan)', iso2: 'AZ', dialCode: '994'},
  BS: {name: 'Bahamas', iso2: 'BS', dialCode: '1242'},
  BH: {name: 'Bahrain (‫البحرين‬‎)', iso2: 'BH', dialCode: '973'},
  BD: {name: 'Bangladesh (বাংলাদেশ)', iso2: 'BD', dialCode: '880'},
  BB: {name: 'Barbados', iso2: 'BB', dialCode: '1246'},
  BY: {name: 'Belarus (Беларусь)', iso2: 'BY', dialCode: '375'},
  BE: {name: 'Belgium (België)', iso2: 'BE', dialCode: '32'},
  BZ: {name: 'Belize', iso2: 'BZ', dialCode: '501'},
  BJ: {name: 'Benin (Bénin)', iso2: 'BJ', dialCode: '229'},
  BM: {name: 'Bermuda', iso2: 'BM', dialCode: '1441'},
  BT: {name: 'Bhutan (འབྲུག)', iso2: 'BT', dialCode: '975'},
  BO: {name: 'Bolivia', iso2: 'BO', dialCode: '591'},
  BA: {
    name: 'Bosnia and Herzegovina (Босна и Херцеговина)',
    iso2: 'BA',
    dialCode: '387',
  },
  BW: {name: 'Botswana', iso2: 'BW', dialCode: '267'},
  BR: {name: 'Brazil (Brasil)', iso2: 'BR', dialCode: '55'},
  IO: {name: 'British Indian Ocean Territory', iso2: 'IO', dialCode: '246'},
  VG: {name: 'British Virgin Islands', iso2: 'VG', dialCode: '1284'},
  BN: {name: 'Brunei', iso2: 'BN', dialCode: '673'},
  BG: {name: 'Bulgaria (България)', iso2: 'BG', dialCode: '359'},
  BF: {name: 'Burkina Faso', iso2: 'BF', dialCode: '226'},
  BI: {name: 'Burundi (Uburundi)', iso2: 'BI', dialCode: '257'},
  KH: {name: 'Cambodia (កម្ពុជា)', iso2: 'KH', dialCode: '855'},
  CM: {name: 'Cameroon (Cameroun)', iso2: 'CM', dialCode: '237'},
  CA: {name: 'Canada', iso2: 'CA', dialCode: '1'},
  CV: {name: 'Cape Verde (Kabu Verdi)', iso2: 'CV', dialCode: '238'},
  KY: {name: 'Cayman Islands', iso2: 'KY', dialCode: '1345'},
  CF: {
    name: 'Central African Republic (République centrafricaine)',
    iso2: 'CF',
    dialCode: '236',
  },
  TD: {name: 'Chad (Tchad)', iso2: 'TD', dialCode: '235'},
  CL: {name: 'Chile', iso2: 'CL', dialCode: '56'},
  CN: {name: 'China (中国)', iso2: 'CN', dialCode: '86'},
  CX: {name: 'Christmas Island', iso2: 'CX', dialCode: '61'},
  CC: {name: 'Cocos (Keeling) Islands', iso2: 'CC', dialCode: '61'},
  CO: {name: 'Colombia', iso2: 'CO', dialCode: '57'},
  KM: {name: 'Comoros (‫جزر القمر‬‎)', iso2: 'KM', dialCode: '269'},
  CD: {
    name: 'Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)',
    iso2: 'CD',
    dialCode: '243',
  },
  CG: {
    name: 'Congo (Republic) (Congo-Brazzaville)',
    iso2: 'CG',
    dialCode: '242',
  },
  CK: {name: 'Cook Islands', iso2: 'CK', dialCode: '682'},
  CR: {name: 'Costa Rica', iso2: 'CR', dialCode: '506'},
  CI: {name: 'Côte d’Ivoire', iso2: 'CI', dialCode: '225'},
  HR: {name: 'Croatia (Hrvatska)', iso2: 'HR', dialCode: '385'},
  CU: {name: 'Cuba', iso2: 'CU', dialCode: '53'},
  CW: {name: 'Curaçao', iso2: 'CW', dialCode: '599'},
  CY: {name: 'Cyprus (Κύπρος)', iso2: 'CY', dialCode: '357'},
  CZ: {name: 'Czech Republic (Česká republika)', iso2: 'CZ', dialCode: '420'},
  DK: {name: 'Denmark (Danmark)', iso2: 'DK', dialCode: '45'},
  DJ: {name: 'Djibouti', iso2: 'DJ', dialCode: '253'},
  DM: {name: 'Dominica', iso2: 'DM', dialCode: '1767'},
  DO: {
    name: 'Dominican Republic (República Dominicana)',
    iso2: 'DO',
    dialCode: '1',
  },
  EC: {name: 'Ecuador', iso2: 'EC', dialCode: '593'},
  EG: {name: 'Egypt (‫مصر‬‎)', iso2: 'EG', dialCode: '20'},
  SV: {name: 'El Salvador', iso2: 'SV', dialCode: '503'},
  GQ: {
    name: 'Equatorial Guinea (Guinea Ecuatorial)',
    iso2: 'GQ',
    dialCode: '240',
  },
  ER: {name: 'Eritrea', iso2: 'ER', dialCode: '291'},
  EE: {name: 'Estonia (Eesti)', iso2: 'EE', dialCode: '372'},
  ET: {name: 'Ethiopia', iso2: 'ET', dialCode: '251'},
  FK: {name: 'Falkland Islands (Islas Malvinas)', iso2: 'FK', dialCode: '500'},
  FO: {name: 'Faroe Islands (Føroyar)', iso2: 'FO', dialCode: '298'},
  FJ: {name: 'Fiji', iso2: 'FJ', dialCode: '679'},
  FI: {name: 'Finland (Suomi)', iso2: 'FI', dialCode: '358'},
  FR: {name: 'France', iso2: 'FR', dialCode: '33'},
  GF: {name: 'French Guiana (Guyane française)', iso2: 'GF', dialCode: '594'},
  PF: {
    name: 'French Polynesia (Polynésie française)',
    iso2: 'PF',
    dialCode: '689',
  },
  GA: {name: 'Gabon', iso2: 'GA', dialCode: '241'},
  GM: {name: 'Gambia', iso2: 'GM', dialCode: '220'},
  GE: {name: 'Georgia (საქართველო)', iso2: 'GE', dialCode: '995'},
  DE: {name: 'Germany (Deutschland)', iso2: 'DE', dialCode: '49'},
  GH: {name: 'Ghana (Gaana)', iso2: 'GH', dialCode: '233'},
  GI: {name: 'Gibraltar', iso2: 'GI', dialCode: '350'},
  GR: {name: 'Greece (Ελλάδα)', iso2: 'GR', dialCode: '30'},
  GL: {name: 'Greenland (Kalaallit Nunaat)', iso2: 'GL', dialCode: '299'},
  GD: {name: 'Grenada', iso2: 'GD', dialCode: '1473'},
  GP: {name: 'Guadeloupe', iso2: 'GP', dialCode: '590'},
  GU: {name: 'Guam', iso2: 'GU', dialCode: '1671'},
  GT: {name: 'Guatemala', iso2: 'GT', dialCode: '502'},
  GG: {name: 'Guernsey', iso2: 'GG', dialCode: '44'},
  GN: {name: 'Guinea (Guinée)', iso2: 'GN', dialCode: '224'},
  GW: {name: 'Guinea-Bissau (Guiné Bissau)', iso2: 'GW', dialCode: '245'},
  GY: {name: 'Guyana', iso2: 'GY', dialCode: '592'},
  HT: {name: 'Haiti', iso2: 'HT', dialCode: '509'},
  HN: {name: 'Honduras', iso2: 'HN', dialCode: '504'},
  HK: {name: 'Hong Kong (香港)', iso2: 'HK', dialCode: '852'},
  HU: {name: 'Hungary (Magyarország)', iso2: 'HU', dialCode: '36'},
  IS: {name: 'Iceland (Ísland)', iso2: 'IS', dialCode: '354'},
  IN: {name: 'India (भारत)', iso2: 'IN', dialCode: '91'},
  ID: {name: 'Indonesia', iso2: 'ID', dialCode: '62'},
  IR: {name: 'Iran (‫ایران‬‎)', iso2: 'IR', dialCode: '98'},
  IQ: {name: 'Iraq (‫العراق‬‎)', iso2: 'IQ', dialCode: '964'},
  IE: {name: 'Ireland', iso2: 'IE', dialCode: '353'},
  IM: {name: 'Isle of Man', iso2: 'IM', dialCode: '44'},
  IL: {name: 'Israel (‫ישראל‬‎)', iso2: 'IL', dialCode: '972'},
  IT: {name: 'Italy (Italia)', iso2: 'IT', dialCode: '39'},
  JM: {name: 'Jamaica', iso2: 'JM', dialCode: '1'},
  JP: {name: 'Japan (日本)', iso2: 'JP', dialCode: '81'},
  JE: {name: 'Jersey', iso2: 'JE', dialCode: '44'},
  JO: {name: 'Jordan (‫الأردن‬‎)', iso2: 'JO', dialCode: '962'},
  KZ: {name: 'Kazakhstan (Казахстан)', iso2: 'KZ', dialCode: '7'},
  KE: {name: 'Kenya', iso2: 'KE', dialCode: '254'},
  KI: {name: 'Kiribati', iso2: 'KI', dialCode: '686'},
  XK: {name: 'Kosovo', iso2: 'XK', dialCode: '383'},
  KW: {name: 'Kuwait (‫الكويت‬‎)', iso2: 'KW', dialCode: '965'},
  KG: {name: 'Kyrgyzstan (Кыргызстан)', iso2: 'KG', dialCode: '996'},
  LA: {name: 'Laos (ລາວ)', iso2: 'LA', dialCode: '856'},
  LV: {name: 'Latvia (Latvija)', iso2: 'LV', dialCode: '371'},
  LB: {name: 'Lebanon (‫لبنان‬‎)', iso2: 'LB', dialCode: '961'},
  LS: {name: 'Lesotho', iso2: 'LS', dialCode: '266'},
  LR: {name: 'Liberia', iso2: 'LR', dialCode: '231'},
  LY: {name: 'Libya (‫ليبيا‬‎)', iso2: 'LY', dialCode: '218'},
  LI: {name: 'Liechtenstein', iso2: 'LI', dialCode: '423'},
  LT: {name: 'Lithuania (Lietuva)', iso2: 'LT', dialCode: '370'},
  LU: {name: 'Luxembourg', iso2: 'LU', dialCode: '352'},
  MO: {name: 'Macau (澳門)', iso2: 'MO', dialCode: '853'},
  MK: {name: 'Macedonia (FYROM) (Македонија)', iso2: 'MK', dialCode: '389'},
  MG: {name: 'Madagascar (Madagasikara)', iso2: 'MG', dialCode: '261'},
  MW: {name: 'Malawi', iso2: 'MW', dialCode: '265'},
  MY: {name: 'Malaysia', iso2: 'MY', dialCode: '60'},
  MV: {name: 'Maldives', iso2: 'MV', dialCode: '960'},
  ML: {name: 'Mali', iso2: 'ML', dialCode: '223'},
  MT: {name: 'Malta', iso2: 'MT', dialCode: '356'},
  MH: {name: 'Marshall Islands', iso2: 'MH', dialCode: '692'},
  MQ: {name: 'Martinique', iso2: 'MQ', dialCode: '596'},
  MR: {name: 'Mauritania (‫موريتانيا‬‎)', iso2: 'MR', dialCode: '222'},
  MU: {name: 'Mauritius (Moris)', iso2: 'MU', dialCode: '230'},
  YT: {name: 'Mayotte', iso2: 'YT', dialCode: '262'},
  MX: {name: 'Mexico (México)', iso2: 'MX', dialCode: '52'},
  FM: {name: 'Micronesia', iso2: 'FM', dialCode: '691'},
  MD: {name: 'Moldova (Republica Moldova)', iso2: 'MD', dialCode: '373'},
  MC: {name: 'Monaco', iso2: 'MC', dialCode: '377'},
  MN: {name: 'Mongolia (Монгол)', iso2: 'MN', dialCode: '976'},
  ME: {name: 'Montenegro (Crna Gora)', iso2: 'ME', dialCode: '382'},
  MS: {name: 'Montserrat', iso2: 'MS', dialCode: '1664'},
  MA: {name: 'Morocco (‫المغرب‬‎)', iso2: 'MA', dialCode: '212'},
  MZ: {name: 'Mozambique (Moçambique)', iso2: 'MZ', dialCode: '258'},
  MM: {name: 'Myanmar (Burma) (မြန်မာ)', iso2: 'MM', dialCode: '95'},
  NA: {name: 'Namibia (Namibië)', iso2: 'NA', dialCode: '264'},
  NR: {name: 'Nauru', iso2: 'NR', dialCode: '674'},
  NP: {name: 'Nepal (नेपाल)', iso2: 'NP', dialCode: '977'},
  NL: {name: 'Netherlands (Nederland)', iso2: 'NL', dialCode: '31'},
  NC: {name: 'New Caledonia (Nouvelle-Calédonie)', iso2: 'NC', dialCode: '687'},
  NZ: {name: 'New Zealand', iso2: 'NZ', dialCode: '64'},
  NI: {name: 'Nicaragua', iso2: 'NI', dialCode: '505'},
  NE: {name: 'Niger (Nijar)', iso2: 'NE', dialCode: '227'},
  NG: {name: 'Nigeria', iso2: 'NG', dialCode: '234'},
  NU: {name: 'Niue', iso2: 'NU', dialCode: '683'},
  NF: {name: 'Norfolk Island', iso2: 'NF', dialCode: '672'},
  KP: {
    name: 'North Korea (조선 민주주의 인민 공화국)',
    iso2: 'KP',
    dialCode: '850',
  },
  MP: {name: 'Northern Mariana Islands', iso2: 'MP', dialCode: '1670'},
  NO: {name: 'Norway (Norge)', iso2: 'NO', dialCode: '47'},
  OM: {name: 'Oman (‫عُمان‬‎)', iso2: 'OM', dialCode: '968'},
  PK: {name: 'Pakistan (‫پاکستان‬‎)', iso2: 'PK', dialCode: '92'},
  PW: {name: 'Palau', iso2: 'PW', dialCode: '680'},
  PS: {name: 'Palestine (‫فلسطين‬‎)', iso2: 'PS', dialCode: '970'},
  PA: {name: 'Panama (Panamá)', iso2: 'PA', dialCode: '507'},
  PG: {name: 'Papua New Guinea', iso2: 'PG', dialCode: '675'},
  PY: {name: 'Paraguay', iso2: 'PY', dialCode: '595'},
  PE: {name: 'Peru (Perú)', iso2: 'PE', dialCode: '51'},
  PH: {name: 'Philippines', iso2: 'PH', dialCode: '63'},
  PL: {name: 'Poland (Polska)', iso2: 'PL', dialCode: '48'},
  PT: {name: 'Portugal', iso2: 'PT', dialCode: '351'},
  PR: {name: 'Puerto Rico', iso2: 'PR', dialCode: '1'},
  QA: {name: 'Qatar (‫قطر‬‎)', iso2: 'QA', dialCode: '974'},
  RE: {name: 'Réunion (La Réunion)', iso2: 'RE', dialCode: '262'},
  RO: {name: 'Romania (România)', iso2: 'RO', dialCode: '40'},
  RU: {name: 'Russia (Россия)', iso2: 'RU', dialCode: '7'},
  RW: {name: 'Rwanda', iso2: 'RW', dialCode: '250'},
  BL: {name: 'Saint Barthélemy', iso2: 'BL', dialCode: '590'},
  SH: {name: 'Saint Helena', iso2: 'SH', dialCode: '290'},
  KN: {name: 'Saint Kitts and Nevis', iso2: 'KN', dialCode: '1869'},
  LC: {name: 'Saint Lucia', iso2: 'LC', dialCode: '1758'},
  MF: {
    name: 'Saint Martin (Saint-Martin (partie française))',
    iso2: 'MF',
    dialCode: '590',
  },
  PM: {
    name: 'Saint Pierre and Miquelon (Saint-Pierre-et-Miquelon)',
    iso2: 'PM',
    dialCode: '508',
  },
  VC: {name: 'Saint Vincent and the Grenadines', iso2: 'VC', dialCode: '1784'},
  WS: {name: 'Samoa', iso2: 'WS', dialCode: '685'},
  SM: {name: 'San Marino', iso2: 'SM', dialCode: '378'},
  ST: {
    name: 'São Tomé and Príncipe (São Tomé e Príncipe)',
    iso2: 'ST',
    dialCode: '239',
  },
  SA: {
    name: 'Saudi Arabia (‫المملكة العربية السعودية‬‎)',
    iso2: 'SA',
    dialCode: '966',
  },
  SN: {name: 'Senegal (Sénégal)', iso2: 'SN', dialCode: '221'},
  RS: {name: 'Serbia (Србија)', iso2: 'RS', dialCode: '381'},
  SC: {name: 'Seychelles', iso2: 'SC', dialCode: '248'},
  SL: {name: 'Sierra Leone', iso2: 'SL', dialCode: '232'},
  SG: {name: 'Singapore', iso2: 'SG', dialCode: '65'},
  SX: {name: 'Sint Maarten', iso2: 'SX', dialCode: '1721'},
  SK: {name: 'Slovakia (Slovensko)', iso2: 'SK', dialCode: '421'},
  SI: {name: 'Slovenia (Slovenija)', iso2: 'SI', dialCode: '386'},
  SB: {name: 'Solomon Islands', iso2: 'SB', dialCode: '677'},
  SO: {name: 'Somalia (Soomaaliya)', iso2: 'SO', dialCode: '252'},
  ZA: {name: 'South Africa', iso2: 'ZA', dialCode: '27'},
  KR: {name: 'South Korea (대한민국)', iso2: 'KR', dialCode: '82'},
  SS: {name: 'South Sudan (‫جنوب السودان‬‎)', iso2: 'SS', dialCode: '211'},
  ES: {name: 'Spain (España)', iso2: 'ES', dialCode: '34'},
  LK: {name: 'Sri Lanka (ශ්‍රී ලංකාව)', iso2: 'LK', dialCode: '94'},
  SD: {name: 'Sudan (‫السودان‬‎)', iso2: 'SD', dialCode: '249'},
  SR: {name: 'Suriname', iso2: 'SR', dialCode: '597'},
  SJ: {name: 'Svalbard and Jan Mayen', iso2: 'SJ', dialCode: '47'},
  SZ: {name: 'Swaziland', iso2: 'SZ', dialCode: '268'},
  SE: {name: 'Sweden (Sverige)', iso2: 'SE', dialCode: '46'},
  CH: {name: 'Switzerland (Schweiz)', iso2: 'CH', dialCode: '41'},
  SY: {name: 'Syria (‫سوريا‬‎)', iso2: 'SY', dialCode: '963'},
  TW: {name: 'Taiwan (台灣)', iso2: 'TW', dialCode: '886'},
  TJ: {name: 'Tajikistan', iso2: 'TJ', dialCode: '992'},
  TZ: {name: 'Tanzania', iso2: 'TZ', dialCode: '255'},
  TH: {name: 'Thailand (ไทย)', iso2: 'TH', dialCode: '66'},
  TL: {name: 'Timor-Leste', iso2: 'TL', dialCode: '670'},
  TG: {name: 'Togo', iso2: 'TG', dialCode: '228'},
  TK: {name: 'Tokelau', iso2: 'TK', dialCode: '690'},
  TO: {name: 'Tonga', iso2: 'TO', dialCode: '676'},
  TT: {name: 'Trinidad and Tobago', iso2: 'TT', dialCode: '1868'},
  TN: {name: 'Tunisia (‫تونس‬‎)', iso2: 'TN', dialCode: '216'},
  TR: {name: 'Turkey (Türkiye)', iso2: 'TR', dialCode: '90'},
  TM: {name: 'Turkmenistan', iso2: 'TM', dialCode: '993'},
  TC: {name: 'Turks and Caicos Islands', iso2: 'TC', dialCode: '1649'},
  TV: {name: 'Tuvalu', iso2: 'TV', dialCode: '688'},
  VI: {name: 'U.S. Virgin Islands', iso2: 'VI', dialCode: '1340'},
  UG: {name: 'Uganda', iso2: 'UG', dialCode: '256'},
  UA: {name: 'Ukraine (Україна)', iso2: 'UA', dialCode: '380'},
  AE: {
    name: 'United Arab Emirates (‫الإمارات العربية المتحدة‬‎)',
    iso2: 'AE',
    dialCode: '971',
  },
  GB: {name: 'United Kingdom', iso2: 'GB', dialCode: '44'},
  US: {name: 'United States', iso2: 'US', dialCode: '1'},
  UY: {name: 'Uruguay', iso2: 'UY', dialCode: '598'},
  UZ: {name: 'Uzbekistan (Oʻzbekiston)', iso2: 'UZ', dialCode: '998'},
  VU: {name: 'Vanuatu', iso2: 'VU', dialCode: '678'},
  VA: {name: 'Vatican City (Città del Vaticano)', iso2: 'VA', dialCode: '39'},
  VE: {name: 'Venezuela', iso2: 'VE', dialCode: '58'},
  VN: {name: 'Vietnam (Việt Nam)', iso2: 'VN', dialCode: '84'},
  WF: {
    name: 'Wallis and Futuna (Wallis-et-Futuna)',
    iso2: 'WF',
    dialCode: '681',
  },
  YE: {name: 'Yemen (‫اليمن‬‎)', iso2: 'YE', dialCode: '967'},
  ZM: {name: 'Zambia', iso2: 'ZM', dialCode: '260'},
  ZW: {name: 'Zimbabwe', iso2: 'ZW', dialCode: '263'},
  AX: {name: 'Åland Islands', iso2: 'AX', dialCode: '358'},
};
