/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagAG(props: {width: string}) {
  return (
    <svg
      xmlnsXlink="http://www.w3.org/1999/xlink"
      viewBox="0 0 21 15"
      width={props.width}
    >
      <defs>
        <linearGradient id="AGa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="AGb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#E2243B" />
          <stop offset="100%" stopColor="#CC162C" />
        </linearGradient>
        <linearGradient id="AGd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#262626" />
          <stop offset="100%" stopColor="#0D0D0D" />
        </linearGradient>
        <path id="AGc" d="M0 0h21L10.5 15z" />
        <linearGradient id="AGe" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFCF3C" />
          <stop offset="100%" stopColor="#FECB2F" />
        </linearGradient>
        <linearGradient id="AGg" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#1984D8" />
          <stop offset="100%" stopColor="#1175C4" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#AGa)" d="M0 0h21v15H0z" />
        <path
          d="M8.5 7a2 2 0 0 0 .998 1.731m2.078-.045c.556-.355.924-.978.924-1.686"
          opacity=".75"
        />
        <ellipse
          cx="10.5"
          cy="6.5"
          fill="#FFF"
          fillOpacity=".5"
          rx="1"
          ry="1.5"
        />
        <path fill="url(#AGb)" d="M0 0h21v15H0z" />
        <mask id="AGf" fill="#fff">
          <use xlinkHref="#AGc" />
        </mask>
        <use fill="url(#AGd)" xlinkHref="#AGc" />
        <path
          fill="url(#AGe)"
          d="M10.5 8.25l-1.722 1.907.131-2.566-2.566.131L8.25 6 6 4l2.909.5-.409-3 2 2.5 2-2.5-.409 3L15 4l-2.25 2 1.907 1.722-2.566-.131.131 2.566z"
          mask="url(#AGf)"
        />
        <path fill="url(#AGg)" d="M0 6h21v4H0z" mask="url(#AGf)" />
        <path fill="url(#AGa)" d="M0 10h21v5H0z" mask="url(#AGf)" />
      </g>
    </svg>
  );
}
