/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagAM(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="AMa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="AMb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#1047B9" />
          <stop offset="100%" stopColor="#06379D" />
        </linearGradient>
        <linearGradient id="AMc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#F01C31" />
          <stop offset="100%" stopColor="#D70A1F" />
        </linearGradient>
        <linearGradient id="AMd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#F5B23E" />
          <stop offset="100%" stopColor="#F0A728" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#AMa)" d="M0 0h21v15H0z" />
        <path fill="url(#AMb)" d="M0 5h21v5H0z" />
        <path fill="url(#AMc)" d="M0 0h21v5H0z" />
        <path fill="url(#AMd)" d="M0 10h21v5H0z" />
      </g>
    </svg>
  );
}
