/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagAO(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="AOa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="AOb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FF323E" />
          <stop offset="100%" stopColor="#FD0D1B" />
        </linearGradient>
        <linearGradient id="AOc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#262626" />
          <stop offset="100%" stopColor="#0D0D0D" />
        </linearGradient>
        <linearGradient id="AOd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#DD2137" />
          <stop offset="100%" stopColor="#CC162C" />
        </linearGradient>
        <linearGradient id="AOe" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#F8D84B" />
          <stop offset="100%" stopColor="#F9D536" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#AOa)" d="M0 0h21v15H0z" />
        <path fill="url(#AOb)" d="M0 0h21v15H0z" />
        <path fill="url(#AOc)" d="M0 8h21v7H0z" />
        <path fill="url(#AOd)" d="M0 0h21v8H0z" />
        <path
          fill="url(#AOe)"
          fillRule="nonzero"
          d="M10.63 8.855l-1.407-.939a.5.5 0 0 1 .554-.832l1.536 1.024a2 2 0 0 0-1.253-2.863.5.5 0 1 1 .259-.966 3 3 0 0 1 1.83 4.386l.628.419a.5.5 0 0 1-.554.832l-.713-.475c-.727.631-1.744.901-2.744.633a.5.5 0 0 1 .259-.966c.57.153 1.147.044 1.606-.253zM9.5 6.5a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1z"
        />
      </g>
    </svg>
  );
}
