/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagBR(props: {width: string}) {
  return (
    <svg
      xmlnsXlink="http://www.w3.org/1999/xlink"
      viewBox="0 0 21 15"
      width={props.width}
    >
      <defs>
        <linearGradient id="BRa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="BRb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#05AB41" />
          <stop offset="100%" stopColor="#019C39" />
        </linearGradient>
        <linearGradient id="BRd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#053087" />
          <stop offset="100%" stopColor="#012877" />
        </linearGradient>
        <circle id="BRc" cx="3.5" cy="3.5" r="3.5" />
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#BRa)" d="M0 0h21v15H0z" />
        <path fill="url(#BRb)" d="M0 0h21v15H0z" />
        <path
          fill="#FDD216"
          d="M2.422 7.773c-.233-.15-.228-.398 0-.546l7.656-4.954a.85.85 0 0 1 .844 0l7.656 4.954c.233.15.228.398 0 .546l-7.656 4.954a.85.85 0 0 1-.844 0L2.422 7.773z"
        />
        <g transform="translate(7 4)">
          <mask id="BRe" fill="#fff">
            <use xlinkHref="#BRc" />
          </mask>
          <use fill="url(#BRd)" xlinkHref="#BRc" />
          <path
            fill="#FFF"
            fillRule="nonzero"
            d="M-.1 2.974c.265-.215 1.463-.04 3.534.512 1.474.394 3.173 1.262 3.562 1.742l.314.388.778-.629-.315-.388c-.55-.68-2.421-1.636-4.081-2.079-2.586-.69-3.758-.86-4.422-.323l-.388.314.629.777.389-.314z"
            mask="url(#BRe)"
          />
        </g>
      </g>
    </svg>
  );
}
