/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagCR(props: {width: string}) {
  const {width, ...restProps} = props;
  return (
    <svg viewBox="0 0 21 15" width={width} {...restProps}>
      <defs>
        <linearGradient id="CRa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="CRb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#06358F" />
          <stop offset="100%" stopColor="#042E7D" />
        </linearGradient>
        <linearGradient id="CRc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#E61F37" />
          <stop offset="100%" stopColor="#CC162C" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#CRa)" d="M0 0h21v15H0z" />
        <path fill="url(#CRb)" d="M0 0h21v3H0zM0 12h21v3H0z" />
        <path fill="url(#CRa)" d="M0 3h21v9H0z" />
        <path fill="url(#CRc)" d="M0 5h21v5H0z" />
      </g>
    </svg>
  );
}
