/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagDM(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="DMa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="DMb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#108753" />
          <stop offset="100%" stopColor="#0B6B41" />
        </linearGradient>
        <linearGradient id="DMc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#262626" />
          <stop offset="100%" stopColor="#0D0D0D" />
        </linearGradient>
        <linearGradient id="DMd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FCD449" />
          <stop offset="100%" stopColor="#FCD036" />
        </linearGradient>
        <linearGradient id="DMe" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#E02C42" />
          <stop offset="100%" stopColor="#D22036" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#DMa)" d="M0 0h21v15H0z" />
        <path fill="url(#DMb)" d="M0 0h21v6H0zM0 9h21v6H0z" />
        <path fill="url(#DMa)" d="M9 6H0v3h9v6h3V9h9V6h-9V0H9v6z" />
        <path fill="url(#DMc)" d="M10 8v7h1V8h10V7H11V0h-1v7H0v1h10z" />
        <path fill="url(#DMd)" d="M9 7v8h1V7h11V6H10V0H9v6H0v1h9z" />
        <circle cx="10.5" cy="7.5" r="3.5" fill="url(#DMe)" />
        <path
          fill="#0E673F"
          fillRule="nonzero"
          d="M10.5 10.5a.5.5 0 1 1 0-1c.274 0 .538-.055.784-.16a.5.5 0 1 1 .392.92c-.369.158-.767.24-1.176.24zm2.816-1.965a2.993 2.993 0 0 0 .177-1.242.5.5 0 1 0-.998.068 1.983 1.983 0 0 1-.117.83.5.5 0 1 0 .938.344zm-.95-3.383a2.992 2.992 0 0 0-1.07-.545.5.5 0 0 0-.264.964c.26.072.502.195.712.363a.5.5 0 1 0 .623-.782zm-3.422-.217c-.345.21-.645.487-.88.814a.5.5 0 1 0 .811.584c.158-.218.358-.404.588-.544a.5.5 0 0 0-.52-.854zM7.564 8.12c.084.397.247.771.479 1.101a.5.5 0 0 0 .818-.574 1.987 1.987 0 0 1-.318-.733.5.5 0 1 0-.979.206zm2.54 2.354a.5.5 0 1 1 .132-.991c.08.01.163.016.245.017a.5.5 0 1 1-.009 1 3.021 3.021 0 0 1-.367-.026z"
        />
        <path
          fill="#0E673F"
          d="M10.5 8.5c.552 0 .5-.448.5-1s.052-1-.5-1-.5.448-.5 1-.052 1 .5 1z"
        />
      </g>
    </svg>
  );
}
