/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagES(props: {width: string}) {
  const {width, ...restProps} = props;
  return (
    <svg viewBox="0 0 21 15" width={width} {...restProps}>
      <defs>
        <linearGradient id="ESa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="ESb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#DD172C" />
          <stop offset="100%" stopColor="#C60B1F" />
        </linearGradient>
        <linearGradient id="ESc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFD133" />
          <stop offset="100%" stopColor="#FFC500" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#ESa)" d="M0 0h21v15H0z" />
        <path fill="url(#ESb)" d="M0 0h21v4H0zM0 11h21v4H0z" />
        <path fill="url(#ESc)" d="M0 4h21v7H0z" />
        <path fill="#FFEDB1" d="M5.5 7h1v.5h-1z" />
        <path
          fill="#A41517"
          fillRule="nonzero"
          d="M4.915 8.46c.025.295.291.54.585.54s.56-.246.585-.54L6.207 7H4.793l.122 1.46zm-.624-1.465a.456.456 0 0 1 .465-.495h1.488a.45.45 0 0 1 .465.495l-.126 1.506A1.104 1.104 0 0 1 5.5 9.5a1.104 1.104 0 0 1-1.083-.999L4.29 6.995z"
        />
        <path
          fill="#A41517"
          d="M4.5 7.5h2V8H6l-.5 1L5 8h-.5zM3 6h1v3.5H3zM7 6h1v3.5H7zM4.5 5.5c0-.276.214-.5.505-.5h.99c.279 0 .505.232.505.5v.248c0 .139-.108.252-.245.252h-1.51a.245.245 0 0 1-.245-.252V5.5z"
        />
      </g>
    </svg>
  );
}
