/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagTC(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABpUExURQIqi/r6+tgbM//JFgEmgwQskQYxmwEnhwAkgAUvl/Px8oKWydogOP/NK/3lktYZMVNusiZIoO+6weLm76u42XOJvuqQm8rR5N08UMFmH/LW2g2pJuJkdP+Wd/nrvP+tQ+ytJavAH/rSTOz8fiAAAAKzSURBVEjHxZQNk6MgDIZBUWvUigJqrdXd/f8/ckPAr9a7urM3cy9WIMmTYEbLmq7muopRGc/znGcxSXMY5vXfxHidN1zJPS8Vb/KByxO84X3X9RbLeBAEdlFptAUNb+MTfCwBOjxCW828AWjy5ane8mmlYAgGAE28bnnd2a2J0zR2w13L7C7P41y1vAmwIPG8HwI6zhpj461W3FtxzcihsV1BTXyfB9SOGXojlpFa3jeOr3EGTUZ5hucb0fk3OpGABX8Wz/4FH9Gw19H6HY8xkYvfKzrx/CCjKJ1Hpha7yhZrxIzttAaoXf9x7nlrbSaTy3ER5+N11sgpAYnhL82g78q8htLyQdCAjq0v9TFWaixWjYrcNgfyVYvvezn0QDzUuIa2mkGfg1+LqZimovi4fRRXvuRlkYF+KLsa2gzKsgRttwOoKtqJX6fp8XgUxe122/EaC9LnEjne0HG6XslzPFBxjeWM4107uh5Xex7x6ZXHbx+wFouYr482iV80ttP4/vrnt+VDy4eetz6GfctSxqgRno9YjE+Fp4rIbgfy4fSYwiLE/iHPrKydYat9FP4RoSQ5mFEArfVHFMqQL8Iw/AytlvroMC6/XUtjjGQeSaWp2FKfwdWCn3dKcIW5PtsoWizOnCQbtyL+fr8Tr3bsLss22UZ63PCjZj9VBsXCF5D9mK+oAY6/QrV3Jv5GV8KendacaDpASOX1sz9JPJjMgDPP6fCWqtHzo6qWYnPNZJ6ftdiFBJdgBLmJZS/hm7F6mU2g4Cv8wpd9DxyvDyTwyxzxdU2S88zT6UxrXg58WGq+C7+kSQi3FztezEPQT8xhgoBk3QufcSVwsCW/8LmFcFkObeLZz8SLlvgj25rB6YD/kX7NX9x8ERe8Xtfb/ZGdXX6nlRfuJtzivcQT/9v6/4f/BkJwUCd2vY6vAAAAAElFTkSuQmCC"
      alt="TC"
      {...props}
    />
  );
}
