/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagLB(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAbUExURfz8/OwkMfT09O4rN/AxPRyyXb7mz4nVqkzDgJVKsfsAAAFqSURBVDjLvZSxTgMxEEQtF9Dm5B+wXByUsewPiGT/giFlOqiRQqiR4LuZGUNIDnKKRMTcne3dHa/d3DN1Xivzd0MqUE56c9HXRyRqKUuTE1SSHH2VUtancWnSvM4wDDHF6FyMmPujyCkf48I4N+CNw4B5oHoEB+LoFmbo6sU4TLU3nNIZhv/X6Ofr1+1+tm7fWnudMzy21tabySZrjcer4WHb2m7jjUXe8DZaqAQfpisc8a4tXhnv2SFYH5i0fkQdDuSVodBZawwh2JsX3mEXmAlMsQVXCui6pSH4HqIpmhut5Qhh5AntDiuF3GhMONBWhvbEpr1t8AcGPz7jjHXA1OsajzoEGY40NWx5wIxh/LrjyQ4/dAlDreXX/76cDxBYc6k5cyARaub2nKtIsTKoiCGkhkwZiOgoyQJI6bxI5IfokWjco+QSAHEuAQNU+nwiCUGgIAeAgAmMOh00iS8EBqYpQL4hEi8HkA+eLMb39A8uFgAAAABJRU5ErkJggg=="
      alt="LB"
      {...props}
    />
  );
}
