/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagPR(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABFUExURfQQERJa9fgcHAxV8/39/fX19fAFBfofH+4CAvn5+Rhe9/Hx8sza+DZy9WWT9qG99zdNz88dNp8sZmI7noeq9NsIFW5IpzeofHoAAAGpSURBVEjHpZQLloMgDEX5iJUg2qrT/S91EgKITucU5UkJAjcEpBHvR5MEPF9tPMDSyMO7kc97UOqhaqh9HvO4B3ynLhXHSkt6qGN/aGE78fBW/ypCydVBmcc9qBvaedpDGw+T7a7qwIMf23iA2X5Td3g78zAZe0V/eNyDDS5MLGytLXqLR4CkR7KJezCFrPkkmwZEwqWciA9OJmdqJWTEARw5YW9+dJUSBAUHUzeljWA91/IMo2Y7yyjqWEWdMuOsA7kL/w80rEJJv1OJvB9J+HGC9dnFUq6jPqyt4vow5vsw+yKGtTZ+vZlwG8yG7WsOmJdTcDDJg+rWDwvynZvxJT96qTp/nj0atznjgrdQNJ+/6FPdp3Yh7NAhfO/w3PHW+eCMqurvr4nYNrRkOHINc23+0GG+Z056TW50fR4SDLBkrDCHdLX5J8KSaY79Sv7RZ3H+2VPPl/xzxs+541v+OdJ4j+pzz1++Pu/k/HGM3bXwSz/0V7Xzz1d/Q5lfhxur7zzGnh0Msf3Jksp5IsVejKc55fxzO1nBsd8W8cvQwj9fQwu//rTgwy+Et0BERu4lDQAAAABJRU5ErkJggg=="
      alt="PR"
      {...props}
    />
  );
}
