/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagKZ(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAnUExURR6zzCO40Si+1yzC3C7F3/7IOf7LRd7HVYnCkGO/qkW+v6TDfMXGZubaNUkAAAKwSURBVDjLtZGxTxRBFMbfFgaBZmYThAMLdjbCAQ2Z2QASC5O7hKiNkMzuAVaamz3EQo7cxWAFCXBgBQmc0kGiEW1QAuGu00T/Lt+b3YvQQKNfdjbfvPd7375kIX+9HsI/AKbi64HcmMkHuVyAyuXtm5RHb2ujEEzFSgUWSY7Kte55JEdBBfnqskJhXT3GM6lyZBNhAr7Ni9b90akKGikc2IoFkgTSxIK6X1KXhcB4nHrMfxL7g4v0lZYkAmNG+SQ10VQPzOn5KzV5oaSUysc3JsjxWErfxzNs1sZNycRi46Wt4BwlSCGqZeXTRDWubx992aybZboJSbn9IKQ0zwViwj+Pd4dqW6JuvgtfUB/L/eBTgkTMF/s/s8aYt+L3LrYkQUJiwmAsyI/UPnwdriJgVkaO378TNlRgghgw1g0ZU/5krI6qZsHWfOGnCaR9s1tNgDJakQoB2oFsNs4mfbM4WBJXgHDG+tpACpjs2iXAE6JS9lBDzf0wLBZNGJqDhtcS7RAJT7jic2VuIySiWAy39ZsjqrkEePc0kdminlnHXqiRWA11SbguR4gB74445y7HhHWNKuLBhEPu4jz3GLicV5YoI9Pcs10d6oMGp3kXhQku19M2o3ZHJwp7VrHN6eFpAt17or4UKHQX7AQRrR1Qe3qnkgBLaJOaR5/o0tZnsPExARCc5an+JnTi3+y1ESt9+DcvAbQDWcfZ+0FbzPNfO45zBdDTjsMYZ2fRTqa2xev6G+Kc4QjWAS0mMEqoRPWtw+PNul6yA06SwHAHZtWrV9t0QUd8fY4xQqzA6dIANqyn6dzVJ2fPoOOC2XxggGJtESCHlw6Azgja5gGdg0N2jBCovAZmcXZ7FtoLtkjZ0JJ+ylLXfgLQAEh7jo1OElJ1pOeKcIfrdUvfANyY8N/1B+heFBv1AyV9AAAAAElFTkSuQmCC"
      alt="KZ"
      {...props}
    />
  );
}
