/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagSY(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAtUExURdIZL90eNREREf39/fj4+BkZGfLy8iAgICQkJBCCRKDMtBuGTN/r5FelemiwiYbSv50AAAGMSURBVDjL3YwxS8NAGIa//IP4D0ogu9BMglDIcYNkKIHQtcNxQ0XpUtLRrf6FU+yiCKZ2FWwdSwfFSZeKroL+Ct+7S9IWNDo4iE/bu+d7v7dHG9W49B8KBFyH8HFcF+LqW1/WsCQzu9odu6C8CHNwItev5F7ilMeauMXh0t+iXs3mSoGVFoSfFrLStk7XC0Hd/OMFl9Xth+KpeoMYY2EYBIxF01mgHdzdmAQTaxBmbVE2Vu/ZTOe32WKYXbJAE5oXDG9KqaGxfZh6zeNlYedaHZ9ZHSk1YWVBmJtzfqGOGGeCM9ZRClWIYBwFCQR0oU4keoLzPaUeJRdIJQpS6BilaTZFovu7k9EV11u02mQzLjvP4v5cmnQ8j570u3DZJpkT4Tc3JuZ2MiwLX/CDwmE1B98X0iWDAY6+xozGupT27SKnn67TpbSaLrVaraRXYHUl6HUpSZJeUoBdeVqalFTzg4JvgceWpJhN1CQvjvUX+L7nezG+mE2AyKsRNLYLPZtFbNoaz6+RV80vFD4A7EBUcTVst2cAAAAASUVORK5CYII="
      alt="SY"
      {...props}
    />
  );
}
