/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagMT(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAqUExURdEbM9ceN/j4+P7+/vT09NwhOvHw8MzMzaagm9HOzLu3s6Kcmn91b3txaj9e4iwAAAHVSURBVDjLvZDBbtNAFEXf/MHMYj7AbwxStxMViV0ysrzGC+8RWJFYI+Eg2MewLFLb9Jf6C3wM972xMandSN1wY08s3zPnTUKbJ7luz/KO/g/w5nS6vQhcDcOPi8DbYz8CMS6BwJ8ejv3P08dNQDZhxXAYjv0wfA6qWBo43vffHvvDrxgDxxBenfUeBgDff/eHmxDiRkZ43zStb1ssTdvMhhsYkHjt0OQbwYgY7/UMABDmovU+S3B5Z6dfcfcBAoai0J1N4518dARf4X9gDswwxKJ1SCMTxGUJVvknGYmyFA6vAXinkRHx9enrFzkgDDEUuWlg8GpgTclTCq0b5yaDzB4jI2LhzjIZZuQywC8F7DOAsePlHFHJiTnJWupXYa11uXTGGDWkhKrEylh3RgoQGSSqqmoqqyqltHOknc2MlRESwcRT7oxGKQWqnJRXGAh79c4QpSwoFcGUrcVcFJDgLESjoZQOp0hpK51sJ0tCkm6rRgPurZEGFOlRJsOcLd4ZuaQkswKYiSCrzJqB8gFypqJD/gHmdLV23RPDnLrbV109Uvu6e79iwGv1CFYvR2AbIqtKFoZ9Dpj8sASwF7cw8rQEpMN7LeVx3VDnKWJ67gx/82LgD+bcFYIH5S+4AAAAAElFTkSuQmCC"
      alt="MT"
      {...props}
    />
  );
}
