/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagLS(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAzUExURfT09AkurgsxtRQUFBuuVgcrpwUoofz8/BWaShmlUCIiIre3t5WVlefn525ubkBAQCcnJ9FemQwAAAFFSURBVEjHxU/rmoUgCMQ8leCl8/5Pu15Kwb623fzRQDoMjBpMY4C3/WqaVIm05D3h4L9omYM6MDVSHczJ+w0TqDEM+2cJNauY55rrnEOqWDQbLyvjamb9/f/FA//COczLkpS4nHChz7wPfYtnp3PpoLCMYdi/juHGb50d8Qeib3jut+S8I/vY78hvntydH45cG8l7vJ/S/XxAsBxQpMQq3/ew0RY6DY7RUu/VeoqkeSLyrM/m2I3swIasBa11aH2xrXK+Pp+dY6OdtOXeFeB01RX8VyfEP3iGoAvCQ7+l4rc3z7zIuFjnnPX7kGz98Q3+rvkZw+t+/GDcUGSJj6hk1IRUYvpYlkBRyagJWFEkFEKndM0IwDGM+w2WbHGSpCpmIS47r2KXyPtSQgNZScBjRSNPMKyP7Ms1GMOHrnA5AWYMb/t/AFiwNpAwtdkCAAAAAElFTkSuQmCC"
      alt="LS"
      {...props}
    />
  );
}
