/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagTJ(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAkUExURdYNGs4JFvT09Pz8/ApoDAxvDg1zDw51EPrSUg94EQ53EPrknz5912gAAAFJSURBVDjL3Y2xbsIwEIbPb2C/AbIXJJbILJVYGJKdwd27FNZOicTIZClvwNQtgrFTH6//bycEqJqhQh36x+f77+7zReRfSInOh8WQ2eantWYohUsbZZJjNopdSgu8UQxtxGCkdaZVGmCDMoZ9HgxTyo3eyJU3N+K/EjCtPwGW0yoeDaxangngKfLcAX7p/JI3rrQBFT3H3hfinfPeW9yrFu7zwzmY1LPoFuIcUtI8OuvjwXsaWG61M4EDS3zRIsWDdTCOLYzcTCw3WVKAFjHG1vYtymfgojmAeNO5A8YNPwDf9QjgeD6eTkfEGeqSP5/omo75XZqm2e+7rrnotnqTZloXoK63292urhmDy8B2Wi8D8HqXR+B5WptHACEEmJCVXT+k20hZVWVS1bu+pEJZroV1qKp+mDJeVhgGPlnLyF89HXUNlL8DvgCJZho4eZddhwAAAABJRU5ErkJggg=="
      alt="TJ"
      {...props}
    />
  );
}
