/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagHR(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAA8UExURRogmf4PHR4lqfb29vr6+v8ZJv8dKhwjov7+/v4UIvPz84sWWIpSfIpRe9QaN8QyT1tgvsfI4/9WYP7GypxQYU0AAAGnSURBVEjH1ZPbkoQgDESDigyOc3P//183F4hBydRuzctuY3VC6IMvCvNngj/JxzhH9FJ50pkxH4tmXtzEPSc7XSZWksr/SPNpUvlMT27PeKY1H1HOQ2bRhlwaqbFXa5yDWCDrWE87akkzh/yZfP7ePqHOg+lzgBCCjAJ3UlGP9XG/3tV1bjPYQQjmoFRa67per1f1Mq+hXFYwfKv1djvwXbn8jXl1l7942mY0/MLJNzfl8l+z4eevN/xU+4meqXRbw297pM3ChEV0KWuqI4TVNXPIwkV35kiClr/sB03WvN/cLwV/V/IYe+8vLUyOBLPeFYwTLTKu2iODlUn2MidxbhIQSi2rihmsu8v95hbZA9exeHsR/l/s0ZyPJkUtyMVdVT6PboTf78nyi8svKgqhcSUMG/JFrlj0TDPEcytnjQKRwi/4n+sr2rrA4igwY70rGBy9GvjlxVz+2fDPX/PD86X8y8Xf8KyEqzQOT4lkn6FO0PZ2GLqZBCnVcS1lktrJaSc9pM/0MQ+pv6SU7niy7zwcmsibPW9bpbZLp9mJOl3RH3Zj/1vfLDw2lWfZ7owAAAAASUVORK5CYII="
      alt="HR"
      {...props}
    />
  );
}
