/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagRW(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAtUExURSOv6frSNR+q5PrVQSRjQB2n4ChqRitySxuk3unDMUCux06wu9fBQa29aqu6Z9BPOpYAAAF0SURBVDjL1Yw/asMwFIeFx2aJ8AWMQEu7ROQCHYLmIjCYdskQrDWTs3YxCHIC0Qyl0C0tWTL0CMkRCrlAh5yh7+mP66RJ2iFD+z3z9NN7n0zI/6Wz6CxCTJAs4hJLss56vshwTghcEwblgZ37LmarxwzvGYElvmGAd9F42Vi7eYdRAoInCZLncmXt7AlesEbY483aBxe8wBlTra1iV/4PTuCcKwB7zqFyvL1urd1+KMXUDckjPAcjWrez1bObgoALeAQGV26G3t16vkQ3b/1hh+lyuox/aCiw1SGbwgTBGFObAjCBusbsuzH3xDQUtflOWzjIL4T+aXp/QkipSAEqhEtwUkrTZtolAoERdQGVfircFiXaIxSBlNI2Ih5dQvcRO7cDAj27MDnN+AxCBbiotZ5UFTRM2k1gMyalhkJ0WUHTLlRVGWZDUh4HrZNC6QUppYujUo4czVJCDckARgNEYpJ4RkZQ1yTGr7mXB/5ZEI7zs/AJYKBiL/l1q20AAAAASUVORK5CYII="
      alt="RW"
      {...props}
    />
  );
}
