/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagGE(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAkUExURfz8/P4bKfb29vHx8fT09P4QHf8lMvuJkP0zP/m9wPjl5vtbZGUPYRsAAAG6SURBVDjLxZOxTiMxEIZNJEJ7Lry1Y/EAJ40jWrJeRO1iH8CNlRIJUCQqJEheAeme4qS7vN/9M/ZuskiQq+DXrj3+/HmcFKvUcea7dd6pTzJf53X+VMB+PtHhgys2d7VD3uUJGbJ9HoThikqG7H+/Fyopufj1+PQ2EUZSct4jE2Ek/ymcvOLkjzz8zQY5EMuFVTO8m7sZZ55yypiFWMuV4tVMKvhnWedGKgZymCcocBysBfaTVHIcI6sz62qpzlJKmn3LBAyPc7bYDlk0WifLFQ45fqxqdNKSlPAPeNRNYYmHH0qD8JN0wxBvU3SUOAFBHzgzmcWRoQofJJ0S9LcIUWvzTrhs20t5u65tF9oY3TrHxEmsajssWHB4VzHqKIKrx64V9ruatl1FdOBK1twVwhhQdDCmbELncRA2DzKt0MBMyCBsX2W6MabvJ2QQ9n+rgDsmpAi3/BWEACH2ph9J13kIAbnh76h26A1wV0kIEIj8kpejGTrvpcCOv1Y+BJKGHtWyjxGc6KpcSvRTYRU87f94j2oZcdBzQCgQX0G8QdsXePUuokI8jR2INvdCjwQhoQiHHAk1XyH8A2H86Hdtm8mdAAAAAElFTkSuQmCC"
      alt="GE"
      {...props}
    />
  );
}
