/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagKN(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAB7UExURRgYGP7WSSIiIdUeNNEaMP3UQhy4WxMTEx0dHR2+Xs0XLf3ROv/YURqyV/j4+NkmOBqtVVFMOfTFQBmoUjw2I5J9Me+UO8urPHZlK+NbOeC8QLCVNsDAwIWFhYfEUuHh4Ty6WKmpqbPKUGtra1y8U+PSTc7RUjRkRs7MS293ykYAAAL7SURBVEjHlZSLdqowEEWT8LykSkEQFREftav//4V3XgmB0i57EhNIZ88Mx6L696Ku9zev1nipF/HLRHeV+St//ZzwgzF/5YPifWN+5FOa8wPQx9PTz8ospNIUwlISJ1js333LF7yg6apC3xqH59Ou0t8U+FaLbzmDuST4lV/6lrvKucuSq03600DfNI23U4WEk/E3BnkM3uAHN7xKcaJvmqdusdT5gVRlfAYaShjJkbokF60187prqNHz9lwN40iYVyP8QtdPahxVHyT+tkXd3BPQ51Cv8lgcccjRN64U8488KN5prTbvG5jvwfbx5OIw0TfRsF3wpsUqChDinK537dX6JzVnxrejy1idNPNelOgy0V0ztVoNPgHlbHoJCngs/uVp8A2kaPICGc7DMFTkmw74HU1QUNz7hhkU8Y/t2NAN+iZK1G634wQ78E0nfAy+EcRLnvM2Dnhl2sTj+xJ50vud4AQH+IasUrxKBvXAlXyjKF0fS89f8IBOwTelBHZd8C0W73WSSJf7snT89QsOE/pLfVDSrm9gugffmE0SLO74i7Cw9kZ55Wqupku8mCb+4+lg8I2ecibffitFIHJflp6/T0lbiM3OIya5mUXx6uTDpPWI+Nofi2/wntzG7XlOm36qsmc0whmphJ89Ad9IGb9nwww/+Cp6f0QsErxUcu59kzelWvcNWic2kiRc354oPINZjfya3OiWfbNB68hM4v4t+JYRraqt06D4jH2zOOsj0aWsJJXYriE0w/DMwG8cJ6gyEPhm3djPSotUfUAQRSv0C780g8kpJ/hGla3F1uM13jAajAa+PErYdNYSC4Nbj6NlEmZCwX8QtY6+MW2h9TiKYXKCcMxZeghuqTpZy+Ut+DYR06TPkpccpncw+IZxokgWybXOZ9mhtq56XcY/KlrnyTdWfYx/UbHGq9bT6FsRBE9Xhdu+8eKbFC+KmAbufMGYHwuefZPiElpIEpepmM6LBe98o9aLdcXTxaL/mW/Fawr40LfoRbz4Dym2XlA+bAZVAAAAAElFTkSuQmCC"
      alt="KN"
      {...props}
    />
  );
}
