/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagPG(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAzUExURRAQEOzs7Kmpqa8eL9YcMiAfH/7SQeUmPRcXF98iOX0cKEwbIfakP+52PVhYWOZLO7a2tj6hWWkAAAH6SURBVEjHpZOJloMgDEVjCRRc//9vB7IRrO301IeDCrnJI3VgLs87griEe3yM800+LniPjzHc5OOvbVT+Owvb8Z7/wsKR1g98a2MpdD31as99rCk9i48pxfN6Bgs54UdKq3un3ZGvFgTSGKu2bltKaRtTnuvXBKE4OSPVO/Pj5plvbTQHPnRLqs1vvfJ8hoGtOlLX0Zev+NrGcpK4F61u55I/W9jSqM3zucbndtVpejwmWhjb2PjVW3B8Qwlvf49pekTOVduIeo0dWNeNFlF4KV5HJl5e+AyUgKKP0btsAEcTHTP7lwStjWgmlC+8iL5+zjKzzM6ClqFOK/ce+1IdYHB0Q1PGUEMkEgt/wOhx1Pq+vJyC1mYsNrBaOOyZpuq/ad/jvjMgXbSXJbRYZASP7ocXgAL3aZp2M8C8GoozWjSi3SQj1a8fzjTZAaD5z131a0T1UPy9PYr/oX6GDJB9hnAubBrP/1YzXqko/7+W8IK6+mpbb3xltwnx2gJYOAP93S3w5nLNWxVwPsByuZ7GcF0fqjpxOXgfXs8grBXjNLwK9iQ/KcC5jQiSnAPpy4Fzba1B13xdn6f25UqgKfcj0qRtDMZ3ET/Wc6/qMigcxL+p+YdP4uB59D/meMMMojaGV/9fi9sYfuZB2wi/K9zkqY13+PYPAfc0/wFfBDo776edXwAAAABJRU5ErkJggg=="
      alt="PG"
      {...props}
    />
  );
}
