/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagMO(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAzUExURQSPcMjh3JrNwjSfhwebegKBZPf39waVdQF8YAOHaSebZ9nJI1ewnHqySPzRF/HPG4m8f2PzrUsAAAG+SURBVEjH5VPZcsMgDBSXsRyc/P/fFpAQwgG30zx1umI4pN0VTmzwnwH+vT6ugpa+n7JA18qo8JHU8XydzUl4muGhi1Qb8X89X9qOaXLDGEFnonIilP6q4PWh7iHGONEdj8eh8pejYo56wfl8nuujwkL/bf+u70FmIKYQndmMUz3euQBR8aHgOA+u+K3As67noXFJ0BauPJ4P3tuqt1ysebKSldxkEh6dNwLxm14sVF/oF6j3p0NifYL2XFfqPSzrLfwOn+oN680tC98CfErJ6f7R1QyXBy4NmnjPfY30b4kIjdnmJkIaNdy2QrsBypS1qLQ02YXcVibqZ8CrYynzg9uUX30sz97eQ+EJQB+Q74LobP7RddJs1g2k/sxV8WaTvwPnfO3vncufhba/trtg9QO6CXemRzOVG/yhPqSpPs31QYJGjoBvUcYkjdA0pCIfRDkP+9Au2HNQfCtQzeI1AvVKrUCupS6aB4wvoYXuj8opQFgh9X/BpCVrrQ/B2fzlGWPdDedOv+97XcKdfi+EMfomhHmhB+QuXNlrQ9pQMHo9qCydQRKDWgj9pO16HrgUBso+9JnUpQD7Z/jr+i+M3D32mf86IAAAAABJRU5ErkJggg=="
      alt="MO"
      {...props}
    />
  );
}
