/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagTM(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABUUExURSq0a885R/qpK+ny7S27cC6/cto/TSiwaDDCdCu3bfv7+4zYr0KdYm7QnMro2OBdWkfDgbVQT2GJXvrk5nCAXO1+OTekZZ5hU/bGqVrHjeF5g/asbfGkEGUAAAIzSURBVEjH1ZaJbtswDIZlW4cp387VtO//nqMkkpKPtUuAAduvNKJJfiQtpIBUy7Ks9hWpf4efbvXH5WN6lTemNcGa6rr+unj/WYbNGWOEQd7wM+L1bfL+EmOcE3ZW6Q9lgq3Ej63xDVCmUNd0IWx+Uy/xSZ/Y+gvxqUhpG99EYzZbTJR5O+Hp4RvYff/Id2ar9sizdpmpxDiYU33PD0ilVxiazdhGC6/pIfM6LnQP3g/Uf0aL3GnT0j884J9dVjy9dbF57MjrmD77MdXk6vRRyYmfh3P1rXbuoaPC2BrnjzGtZ99otnkPUmL3zuHwzvUpgP11oWfBk0ziWTteayhLdMiXHCvzu/nDKzTC6NGP+kyZl/M76R9OsvuJt7bCZSvxAABZM57m8we+Ipz6Q/oKK+IjuQ48UJKtqAKkzFkadngQTauTHyIAVBqUuKpl7V2/LhVQ2jAOz3l+dmPT+HEGgIzziIA8xAjAw92v1+vdPYD1HENjj6troWhfSCsgl+7X+Otfex4ONWDzcezmDaWLVfQv+DPpc7cS6zj/nyjz+fze5FnHDPU9r0Dh58grisQleXmPPpHw2UWkKrLIW/rIWq793d3765JdqQDl5FG2HAv//6N69Z7K/u/o7P3/Ju/ikoeCp4hTm/1gM0oPlU33hyqXdtyHgWS7xBRFw7nL/UF8OZZU+qkah3GT+4PbiRudKUxDIbk/cEHlJCaVckyV8fAt9wf3inL9Kt0fbPUuz/qv+F8mwUIukF2UAAAAAABJRU5ErkJggg=="
      alt="TM"
      {...props}
    />
  );
}
