/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagER(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAA/UExURe8eSk6U5f/FPCSzOCW7O0qQ4UiN3ewXQyfCPvInUFKZ6fNJRvymP/d4Qp1Yld8rUMg4Yl2SQIxuRLZQSXZ0vNNxGwIAAAI0SURBVEjHpZSJtqsgDEVDK1IErR3+/1tfRkDUrreuB8qQsANELazv4XFBEGP8vIZLPIe4xqPer2t8jM8/hGh51Pq+PwYs1FhvY523deh5TsW9QkMXYFf3vDyQgd1F7ZgnZjjkORVDJ6Ue25gn/HGIA53zks0D5P7fvGYTibZsJj2f5ny75TynGIEqSAgjtz0WgLoQK8IqjcAeTMWdkPITlirEpqRbqxTVTg2HsAgqGrY84znxLThAxanHbDagSllexzRAmhFMuQQAWwHwed87gYiclDhamW+ZLDQ1p+C0CD6vjpctgC+fChd1bt4mgmRztz9eeQbu8OmRSQ12vFY1RLVl3h73z7OMkl6gHGATRrNZDXhc8qfCUz7hVEGyueFBzj/Pc2v5oeeyOX/cnD+WB3CidZmm3f3T9v6BDrqrgWA3TcTTLGCVdAc7f4CS/32E5/KdRFAiluev+8s8aGlqhWV/dYds503MZzlP9ct4/bqpkZrpp+8/jlMCfv9jCNXP8LKBlbdFSb57Sp18f4bR/iGsyzjtxG5T9/2rh1u5tNNS5BTWMLKv/P/ECsPydQpiQ9VZWzfXI8w58/9fNWHGbLWBHIbbnu+Fl3a/BFfgn/yTLq3yx7A/5Qn2tACL15FNvPPF4Q/59Tv6Ktf2FkHG7oDHS/t+ZR+quuAY7uX8iWB7aT+OGGD0JYoOxzIeq51K5RkW62hLR+vb8ehrMR4z1siPvfyZVz+s3ufPAlW/+KCB/6J/aYs+FwAPQc4AAAAASUVORK5CYII="
      alt="ER"
      {...props}
    />
  );
}
