/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagUG(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABaUExURf7fQRcXF/3cNSQkJOIPGxEREf3dOP7ePOoUINsLFyAgIPT09Pr6+vzcMxwcHBsbG/3cM/79/YuLi+vl4/3kZTs7O8HBwVRUVO1DTfjvwPW8v/vrnP753+6IjqdtjSwAAAGjSURBVEjH1ZXbuoIgEIXHQNMGLQHP9f6vuZkxUvuwE1f7l5SBtSC9WICIA05xwLmqztX5gSs20Jwfe+4TkMQBacLXTPJ4LGNekCzzKy2kccB/5xhHtD+L45XfTtdrfb1O9pX/4CndtSKDofYMcNgDyrK8lBfXyg0Xq8ipG00PZZ/nPZCH6XljLUQ3/4V+R7fj77F2+xtxEm2tlOvjzgIg6S65LchRMfrUkZsYvUrmazFIIue20JOjJr9Wnv6uyuVaDDLE7b59VTXG+29B5d1fbEdHb69OQiP1UY0yJIWCkcUG4/RY6zmiGqqUMkVICkUIpA1R6TmjGkMFBpVhv0F24LxA6hZANGF/MNVbMi8LJFS3n+e/+2ZMq7VLSZF2VOgv8r9hu+aE1Khbqpov8j8lh9KpNl1q+F2w3cv/0AEwfzF0t46Xct1mM//o7+V/h/4VBHe6b/Pf4gpjv89lOzzsg/0p1+00GDTDZCH7Kf8zTnf4Nf8zbvz7Nf+PUfmfZYf3/lX8r/K/nOuSD4Wnk+Gz/F+Nhebf5f+nRPtlHNH+Io5Y/x9NrEybUYtNpQAAAABJRU5ErkJggg=="
      alt="UG"
      {...props}
    />
  );
}
