/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagMF(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAnUExURf39/QYmnQosqg4ytvI7SfRCUPn5+fE0Q/X19fAvPfPz8+8rOvHx8X/NEAsAAAG1SURBVDjL7Y6xboMwFEU9scNURV3AUpWxSqXMGYxYM9CdCTFmQEL5AWRl6oYsfqCyOnRF/EHER/U+27gQpe0P9MTvZbjH17AXzzPzvHqO7F+4FfYFoiKg9Zq6PD+ynYv5bs+KMsCURZDneUoICHxneeH7whIEQeqElBrmnD8FHhenIj3MAodQekQuDHl+YJy73DfgSygiqIEnPNklcJI7DUIcGFIyEjQULi7KOc4h0G2kPFk1iEUDQAFqfhEsRqj+EmC0VZllohaYuj4thG3ZyqotaQsyarJWDZJuS9rZzLqhNVSgwfWsru0TURLF5mwrQyulrJusqRtaJ+ZzNEj6SdPQUAP+TiyOfYPJW1rNDDVEsWOLy9Iyx41piOPIWFuXtvK7wQnW2TjhXV+WQogMg/OASOuLe6Izc0ZDFJIDY6MvgBr02dJ0HT4yhAGi8IEKtMYLF2TOwRMwiDDcIAQkIVHnrsO8sXAm2miPUp2yxkIIF0JHuaJZCdM0fegrBg1KWWUpPGp9vVpFeVbCdEUFMdlw6G8Fz0CMfd8Pn/cFNfZW+UkYh6HvxxHnJ4FAPPwqGP4WvgAEZNGJcKJg7QAAAABJRU5ErkJggg=="
      alt="MF"
      {...props}
    />
  );
}
