/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagBD(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAbUExURRGAYAxtUfI1TA96Ww5zVo1SUtY9TllhVRtyV0k/u4QAAAF/SURBVDjL7ZO9T8MwEMVP8sJYSzcwR2rKaGGXrrF8fMylA/8AzB0AsYP4u3nnpI7ddmBk4KlJLu/97pyPhuhfv5Or6reX/nnfpEaJUUQX2071ZHKTI2eMlsah0M2/57zr9whMblKCnPcetTfrbtJyBKaNvJ564932AHSPaEEbTBTkR5lNybsVcvQqgQlOaey+Z6D/9EVlgp9XyGucAlXeXZ0BNjWwOgXSugaWcMIBCFn+rgZ6GD6EBA2U0B58umkAxAgxJUwTUrqugQ4T0CTwHSVJqEK7RBKBra0DIcQvtYBoJjoC1yCi5W1zF9nTXMYJWOa+eQ4aShaAUQ/Nkxw9DJgBqd/F7mBKKECs3+ZXAaoJ1UWs5AiIwhLjvMaOObvqA2BmVBzLjS6jqMmZGCjqEWJ7+Fe/8uiBkTgQzthai7PL6buAA4/1YHlBMVeoIf2yPmxWzE0xLiiX6sSp4CI9WRBbtlgkZsY20h5MmEZMzBxz3itwpKhRAc8Arf4E8APJkK7Tf+8T/gAAAABJRU5ErkJggg=="
      alt="BD"
      {...props}
    />
  );
}
