/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagAI(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABaUExURQMOitgcNAoXpvv7+wgUnQURlAgVoQQPjgUQkQYSmAkWpPPy9HuBx/bi24GK0FtlvO+8wv+nIsTG5d07UB8rpD1IsuqXoayw3JnK/tTW6uJebpCVz+Z8ifvQjiC6mI8AAAJxSURBVEjH5ZPrmqMgDIZDAU9RsVbrepj7v81NIijaw0yfnX/7YRFC3g+kAPdbo4fuQqq1UkrX3Lx0s64m334r0I1aNLoj71Df1aRdUVyKb/hSV7dbpedLsfHdQDFybWmcDJ56cJwFhUNKvuuxD3yJuCj5quK12JM9oEj6ESc1IQ7CD6NubtwtwxRvBWTVtVomFJ72TclykqRI1hxqPG0Ln1D/MtB2qUb4RinZjuRRzDEfC2pRq6u75+mNgwTdDj46BV5HkvVHcsm3AvVauv4F3vjCTxL1ffQ7npJMhJ5oQ9+Pm87fj8681EobA2VNZUBslgaJx+ZeYVuK3Bs6CLia+Qgrz9PpwSExPxSYvG+RTs9UofBIp3fBtjvltb0xfbvWR57uz0SnF9tZ+IG7E459nJUbrduW94Rr7m/8wCte6LqYUviy4+XcKuwpK885lbPjfV0d1wJyV3Ho8tzzuWwHxRzTQcxV12vF7yicA919HB2HAp/ndKMX2k5uhomY+7pev4TfoiYH2rd59dt509FX0QqieQ7zRwJse990cogcN610xijPw1If+JKSV1nHZyYMGOe6KA9l8VLjgbd2a1uWzE6PVPlmPu7zjwd+zV3LahIFrA1m835NZm8sBeyukGtze1ba7XwXD4B9Kj/37gQu4C79Af+gDNwfkYPsEz7bDXrGezhMb2O3zGb7k3Ed4TaFrq47SCVufUoG2UnBwO4+XikAPad0eKBfiw2y9/zHOvOp/NKUG+G9jx37wqdHZesvC/weP/oGwZnO0o8E6b/p13hp8D/sy9k5xE5vgG04RIJB1IY9Gw6WLxXyP9Q23/+ivzamSMHqypVHAAAAAElFTkSuQmCC"
      alt="AI"
      {...props}
    />
  );
}
