/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagKP(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAqUExURQxUpQ9ZrO0kM/ArOfIxP/Q3RRFdsvLx8f7+/hNftRNgtvJye/ba3PWxttSr2pYAAAGISURBVDjL7ZQxS8NAFMdfvkGzZC650SXknTiIULjLZAtFLzjYwS6Bbg6FE1Rwa6C6FuLk2q4iDuqkYkE3kQz1w3gvaau0NThk9JfLu/f+75c1MBoOE8Pl5XBIb5LMJqqj0RVEUdTpJMlgEE3pdL77KDqA7HIcJ1rNAdiO027b5ixDmwrYxVTAsm3Lsq3f9hUwVLKzEgtKIC7mrAQhLKZZgqBm7KfpRKkgUEpKqvQq1QQZSCIIxr29+DmQZkGbwHSU14AiqVS4F1804p7KUpl9FZBUAzllHPe34/hJLjAXzLIrj+L+siCEkFyIxk2oeBg+5JOp0jSScw845yg4r79SuvmWT9xIpkEhPKDLPBu9a0S81WI6I5KKWAPMqes+4r4+xwW8mbCljxE39emywBDNMbsuXnOy0M+TvHjgE8zFl/fWyW766PqMuVnETOqzKmSXCVt3Wh/f77DcIClrq+D6LuGvp1rrD+YyM7A8pOLBfF77PJm4P2BZrYJbTBmCLuawBOH/H/U3vgC4AHq51cc2DAAAAABJRU5ErkJggg=="
      alt="KP"
      {...props}
    />
  );
}
