/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagID(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAASUExURd0dMtMVKv39/fj4+PT09PLy8jL9BNUAAAD9SURBVDjL7U5bjgMhDAs3IDeoygUq4AAjEf73A+5/lcYJU/UhjearWq3WDMZxHBiif5xDCC/Ve5coUuSALxoFRXTNAQaZ6ZtWezFmcUNkDGjeBtiaxriBIz1cxsluB5/AY/gDZrY3PRvjnkBHb2C2JkIPhFXhx/gZ4bnwqdfAJ/5K4HqMy68IpGNoIOeUcvEFYfXu5QvlUryXVgJl2r1yIzVSgV0Wp0VWJQsc4UygtVqxpSkKtHIBK9qNxCxBpK6UiGtF3Ug9qYKWWEec2lqb3iCGlZAKMmVSAyK9y+h9DNE9hhZQ0mXOMTaaOAwqZp9dz65K6674QeAI3wjcAYCrrsJUK2JUAAAAAElFTkSuQmCC"
      alt="ID"
      {...props}
    />
  );
}
