/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagQA(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAhUExURZAfQJYhQ/z8/PT09JwjRqEkSaUmS9iwvKM0VLlpgO7k5wNLdDUAAAG7SURBVDjLlVCxboMwFDR/YEv5AhgiZbQHJKYgmb0DZu5CvqADYyulnVsp7Q/kR3v3MIlJHFW98Ix5d757jioXTIccntVFUP38ISi3H38LxnEYDnHNRpCK3BDGEIYhEUwD6RFtEovXUyIIM0axmYUhpBHfYY2BKU/pkO/hHv8RVN9jRrBPh+y6LvRcE6S36EPoe++hwrvrWKuI3cmT7Sjyvo+1V1VVWjyo7bEnQEQwgjOQL1Hbo78HHKigze7UsdPNRH8RWJK4ZDl5n3eoSlc5Z+0jAcer6NCcYq+9dbAOZV1ZH1vCb9oEe+WsYwDW+rjBkU17G+EwAm12J57YAEbW+Y0IS0AytcYYtKkyssXOaEXSwcBNhg5CyW7WayUJUNjmy0TWzGi503EG/hX1m1kwq1g63oKqRHAFI0jjiRE5wYzJPBJUi6Aw2hSFrEsV6uqACHaNxsoCq1cRGLJgt9CoQmnyKwdXvyoChE7WJOJTaQH74iH75BYgxELaEXolED4u+vIBb3fGr0EEievp+AFOJrgMeQs5Lap6nxWAIXuWiByahgbnxr3keRlShngkgAMMgEcRpGnSNPkhfwGLaxIJbXZLKAAAAABJRU5ErkJggg=="
      alt="QA"
      {...props}
    />
  );
}
