/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagPM(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAByUExURSSl2ssQFf39/dQWGxyXyvj4+BuVx/7ONh+bziKg1fX19d4sKm9zQfLy8ieiUCOaSukyMN7t83vC3u40MoWFhfi2M6e8d4W0jWe41OfJRmevpDKhyMjCWSsrKxgYGOFaJOuCKvGcL4WQe0WovCAgIC8vL/gEXo4AAAJ+SURBVEjHxZRrd6IwEIaBBkwoKCCXw0XbHu3//4s7VwwcpHU/7A44ziR53hkiMThnx+MxO5/PURSB5yz4vSnCvMQv8QIhr728wBdFwVgcx/QNA8VrfFEgGEex4i/zKAD1FX+Fj7fsX/HO41O4yMMNEy4gtwjmVAfhfifLTqc0TU+njFN/6dC2g4PEOc182UBx5kWA5njVcABrVazFbOBJnlc8Az5TAeecrHA9EoeORlxHSe9mnHjGgH9XAZ7DD5YHif6Gya3nbBB5R/0LlOf5HLvZuCI+AVgrSccwCcw1iZfswSuCPcuziJjw0Zat+J42jZ7lr3jZwU61XuC7Ne/9GsrX33UUk4/EOwsX7PdtvHk9z73A8ChL8P39vl/g8F7ulyhGDzFJW6w3bdWftAcLfBTXlxpUyEccs/jBt8HaYTFAa+z2+UNla/vDjvV7vCWb9viJ1wSpd3Lh7LJZ0h72+IHXBAzU91o8qWD38Jl2yzuuT3a9Xmcv9cHGpzvQj5YqAJ/naZ7W1xref/ZgVmx80sE06oog3zI7W7fRQt895n/iQWHVw9T5sz/z8BRDO/X4J9JP7TBas+Dftuwxb/Ay5C3dZqn9hDdCisZCTmb4elbfCPhYaa3n5i/iPz6/mga2pmm+Pj9wQBoey7LSohXGhoUgHiVGvlnsb6O8NRX8FTBVlRHHVuLK0L6Y4C1c1w+RR4P6eJjKqir1YGlcjrSAeQDwDjEKKTGiDrX0SCGZygmjntgChmaYnZkNFPD91qdY0cgr6pvOJiZJZOcSTL2Yp4lfP38YJgmvp0VspCUhK9MI8qv9n3klNPYkFOf+F/VD4vftoRSEW5b82v43/wcjV1RSN2Hb6wAAAABJRU5ErkJggg=="
      alt="PM"
      {...props}
    />
  );
}
