/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagBA(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAA8UExURQQqlggxpgYun/j4+Ao1rwcvowkzqv/QQQUsm//NOSpLrMfP52pueG2Dw5Gi1HGJzerAQ8irUDxRi5yOZNKmKsAAAAHISURBVEjHpZIJosIgDERDF4Rav13uf9ffCQFC7WYdFBLII6RAzae6x7F0LG3wTX+Xf3fdG+N4k3/W9ZMrGO7xf3X9d17Bef6mmX+qf9FwkbfoLRq6JnrNdMTb2CzZwAUvaZnYr8BmZuEVpvZdnN1L1AjZXU1H+Q94/ooYty7Rn/MWt8jGiHD+xcZuwZtsG2tYeEVs4xkKpzeyJseDj1ycT/lNr1LnbQBYE3mTbBntq+teYUs7F6f3YYj5IDKf4tSiwZcngKtjt3itKUD89wH/ijez95I3FXDEt6ZlLQbbph0lt0+nwFri2w2BNHhF2GDy6QSygw7d5Fm4RTZ6r/W4yuMVBWv0pfb4aju/64YjvuKWO/FbvKLgVP2az6EUTFY8AHwJkXEu+BiLdaouaVjzUdd4N/3GV9V8mXeFh1fEs+Me71ZNO67CLS6jq1QFOoKwFqA0auEVhbl8iTqG3LGQX8xUgV4/4/GKJB0NN/glIIX0l3jSCEnHkzRv8USCkNhqF9kr/qSCGCcQ95BT9toPRrjEdVw8QeHkicXCV8wVrCFX7FTawccthrmR+VX6U+EVBWvK+b9Qzk/9HR71R3u8wRcafuR77fwD4lI20E9y1ucAAAAASUVORK5CYII="
      alt="BA"
      {...props}
    />
  );
}
