/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagGS(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAACfUExURQMqjAAlgdgcNPX19QAkfwYwmwQskQEmhAUulgIoiPv7++zq7n2Rw4KXymtpa/bDOHl4dy9Ypt07UFhytA58Ec3U5pyaSrC82hg6kJGlzuqXoYianyZAeuJebvLV2SdGllo0UE5VbGuCuw8TH+Z8iR839vG6wTI4RvDFylBhh73Wu+uzupdEFdupRA8q7hAwwEiZShh8HydocpplO3SaIQuPymQAAAMNSURBVEjHxZTpeqowEIYjgQgJIPsiKIL70vU5939tZ7JpWm2rpz/OB02GmXknQxpB02RDy84BBdSyLBo4QjVlM21/J0Q31gqz9COfMjq1ZjS9gx/oPEnmtDb4uAQfVM2dO3gnxSyxpjSPNe9jvLLOb/Uj78QMz6wZw6Xg65xuEv448LArLilXD672w4XgocupWFDwsG+WaMd1ZaJIdl1Vidu6IrcRjzglbJe1EfzOssR2SEiMxoLK46oY9B8I5XQ+3Ul+usG4FM5ULeYacnQnyo2oIdE/F5ZTeoGuK0k/sr4WDtwf9S3v3wC6ffcYT8StZuIURfSBx4Y4YyrlhAJ1ocVpobziQj5XzfBmtRP8bjrHpXD6KSGavtyn00n7+B/iU4DhvFuSP8LpwaVDVNNKrp74+obPBT7OMZye2Vz1fxQ/neqcc64R4ADGfbQ/24SvPzA4sckR57XgS/44Y3lMPothxvGIFxC26L/kHa8YG4gveF+0k8zZVQGf+aSKuCphy/UZ/HR2uOyI5uV2gG/4XMBZr7tosVhE3XrtKB+C3z7O+U4jzROU5lD1KAogfiOxzeRlvX4Jw0UYckPGCJrNWV0hnnHhUQVvlRwZQYoUych5fnb6MIx6biAZQziPweCCDxGGL6EIoAHsXAW0eH4bhmErbekciAzxAvzMKBtV6VDpPKIzEKmAry4FP8lDP8iD/sMeyLYoWvSYqqZ6z6Te7e3DvJc2+0OWvf15y7JDu9waPXty+NC+6fPE1TQ9fs2KSZG90nK5lBkQVJmXmUvXMvxNsw3es8lkkh0oWyz12hfdqmOoibZx/Ab8K8U4XOrce4WacBvEDfAHOCbRUq95t4CHQwXvX8d1/jiP9uG2xvjw5xDHcR0a/Ngbw/0NKqNVZHtwrBtcd6jb2pq/sGN5CXGfqmtGx12OWWysicaaOMu78phB+PKYcfR15m03fHnMx6/5W2qLJ/j/PRXtP/JPHObDFT8aj4TAELaeP/ravoex79uzH40ekX3leYwf/XfeHtk2fw09I/t3+i3/F4W5WbmBdDa3AAAAAElFTkSuQmCC"
      alt="GS"
      {...props}
    />
  );
}
