/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagPF(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAA2UExURdkhNPX19cwaLAxJps8cLvLx8d4lN9MeMf39/fn5+f6dM4im0/zPnv62ZNPc6Uh0uOSDjeNwbmNHcjUAAAHASURBVEjHzVbbloMgDAwsEbFo9f9/dsM9ocp21z7sYM0QMlF79Aww3QPc1UPokUYLvD9ASXQ8DYCUTiiRYzrj03nt72H/NgohFpDDGHBS95Zw1NPQydhwjiFSk9b4nCKbthyYBE2D4WV6BdCmjigqs5JIXBvJ42oA6HuA+R7+td6v9KWsfqx3lbt6isB1WegLW5YVx3qXEFmZzg4XAn0gIWAtaOWJAOOuakNco95G/eo4ZtYJXLdUeni6ee/pLfaeHsGzJVHd6Rvo8vaYd9jnw/Y3wHCpp7u2Zqd/aDekXy71yjnllIALOe/9ofV0TFofxGOODuXyetZA1bRfAe6W3nC7oxILLhfGNpCI6BAv8fzieBZF6pNr2PVfsD04Nvl8DZd6JV6zy6qox3Agyrix29/wpCZyQMQy7+JW/oJnkGPRVG3kgGmttmFzfIQOzwcKKMEBB1CqnJXUNQz1b+C2/sJFs50PEWuyKVc7n3pvTqYPcu1j9t1beDoyl6s8zZ1cMFZXHVrKmW93hg6nlj/aDnzC/40R/m4rP43G1H2ASf5vzc+wFzz6f9swdLxsCXIuc5kb+79hrO0ZhP/f3D98A5yyNefYTMn8AAAAAElFTkSuQmCC"
      alt="PF"
      {...props}
    />
  );
}
