/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagWS(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAtUExURdUZL9EXLtkaMs0WLAQwgt4cNAY1jAc5luEdNeMeNvj4+Fl3scrT452uzydPmskCMaIAAAH2SURBVDjLtY7BitRAEIY7eYI0/QJNIHdD3mBo+6LCMBCYB0g6gnqNruPCXgIzN4+ZV8h5GcEFT6IHr6InX2Gewb+qkh3GgbiX/ben6u/+v6qsevuPrvZn+qgeCGyOn+aBD8P3Cej77Xa36/vdbr/v+5sRuB5+j8C77ZluVDNtENNeAC0L/wO1pmkugSbgYJYamJddt153XVlKXSp+bUMI7d3m0IamLku8I0Ypu/VSBQoJCp+HAy51xznFVAGE8PrPN4LeD8TW5ZkYeDP8IoA2zAJ3m9sTkN0Dnj9RBV+5ygcf6hWrzLKM+lJVVYU571E9fFVnZYaYERSrPLKKfj886ynGsnTF89gCwFXOe+fdFzigizRFDqWIU3zCOby7V8cDOrxbcJgSRpINzj0fvqKSX9CzfCVdEeBYL4afYgQ4aQJkwwzw7Hg7D5y0iNPY4lgr/RJIY5ZA1iqrWNbGMTVUO4k4juQiPDGK/iwl0/hJPENLyKpHVzS2KEqg6S2hI8INRSGki44SHWkJkkmaAN6geUtCmHjZS7BKNCZpejyySo9eY0iuYOhEEVvM64RBAmb1IMCwM3Rywy7P0cjnAIzRxuRFnhvKYeFAkAqYRLHBSD7KiGSgME/U+FpAhE7V8BgBBWcFj8FzijoVACPBVHEuI8Cs/g/8BT5cVoTabAGtAAAAAElFTkSuQmCC"
      alt="WS"
      {...props}
    />
  );
}
