/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagAO(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAwUExURRkZGRAQECIiIs8XLdMaMNYcMtkeNNsfNd0gN/fSP9k/M+iKOox6LOFpNrGZMWJYKKLDIM8AAAG2SURBVDjLrY6xSgNBEIZn9wmyb7BcLSLsIigIgd0rVIQUuastvNimMpZ2WlsIo4iNFvYi2NoJvoCWdjYWdlY6s3uXuIm5NP7czM78881wcNKuIxiXx8eHhxxN3QCjv8Uwv8N5QKMhHOzvj0YHIaeK3hAG7dpdDBRlWVVlORhwnkRRRK8HZUGqiiaX9VtV0aML9fQPMdyDol096Od5vw424tt0DOSexECfC3/jJ2K3C76f+zz29G3jfZ6z1bgEJNpEvE6MaWAL8XwasFHeeeu3XncQ9+qOMgPOWue8d84aa9fQ3OKdc86wy7kLxhljDYkIQ8A6nlHtgkN5BWgc5kGrr8bgJVeWFykYGCusmZeLX1YKGLNx4dqBNTxfcAHx7uEyBbJEX4h4+tvQU0D2jvjWCiwhXrUAH890AR/nAss0xafkJ1KA7uObfE8vaFImWTrLvp8/ZQbAjq5FnZQQ5lTL0GotQUNwJHt8BXgaSB4BE8Fhv5GeKSS0SC+YL5ag6ISqMyslKAkhgAO4EmIypbL24gAULSjeUvzRcng60aYBKBUn1CnaiJWIsOILHTUlkbzxQov+AfgBvP5G6ZC1s1IAAAAASUVORK5CYII="
      alt="AO"
      {...props}
    />
  );
}
