/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagGN(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAeUExURdEZL/7VQ9ohN//YTRekUP3SOuMoPhmtVRu1WRy7XNolVbAAAAGOSURBVDjL5Y4xjsMgEEUJkg+ALHqHSPQoF0hhidqFD7BEcu3Ckl2mA7otndvunyHxblZJDrD7xdD8xxvEsOV83HLd8in+AnB5DqxpXa8557S+Mqxr5j6/MKScgaBPrwDKmnKCIdxjD99AZoJuAgZr7WCHcK7r2rnjsXbFwLkISwTeG3twR8enrh8Aa03AZcMHmlt+AoFrE4I5KDwuk2JaSshggsEJZFDOORr0RRAvwiAF2itFBBapFOPMWcbyB0Ah7PG0VhQ3LwstifFmKGEDS9Qc44IBN94AcuypZoVbyD7P2DM+GrjFoFt44i/AFUbNW54YngLNG6ChGCOb5o0BrZEwdFqpbgP87CcAUgq0ErNDr7XqkHlCqJ9oBWpJe/YdiCJBQ7WfAKCTPLLCexL0WsPgPY0fBXZIGil3mktiWu9bRqYT/4FGNFWPjqf3UwtiAnQSqNEStUPTa1xas4EvfFIg1IuK/Bp7ut63CF9kQMepdH8PLSDEE1AEBEDOO7q+3VKAm4HeFssboP+nwBfkj4VyfV1aZwAAAABJRU5ErkJggg=="
      alt="GN"
      {...props}
    />
  );
}
