/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagAZ(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAzUExURRuyayClzxmbxCGn0usWRBueyB6izB67cuEOO+YSQCKp0yOp1CSq1Pj09e+HnfTCzepJa3j8Uc0AAAE3SURBVEjH7ZHbbsMgEEQHsDEQY+f/v7YsZmHj4EQtldqHHDYwexlQZKzrGtYQbuGWWW9riueTezxLmkAwJphQSUmGaqbT45w1zBhQShllUqhvwR6oMWCVssqmOHLW5xrRq4NbDWWva2cU7Biw8w+WrQrzGL/l17NOITta1FmX4A75dWXWfebrltbQYwz7pzH+o9+ndbDtcb/3jf6Ygz8o+YOe9hi3SeRipuQeeeeilN5vMe4yFzPZTcB3+uVIz9/plu2p1+j4KzHGKe8vZuCadhS0CvJ91yZKHMNwDXYmkXX6/1u5lMIJTZE1ypN5yauIPV9Qcs9Vob2T71dfJX9/9wq4Mf7cv4zx8Y/6sfTjTe04APotZYGvE9XHhEdbwgN1uDmAk7WNVjMe9lPeirK5vOij6/hwyRfCyDhXXggXBgAAAABJRU5ErkJggg=="
      alt="AZ"
      {...props}
    />
  );
}
