/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagMQ(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAqUExURfj4+ChLmSRGkTNasf39/S5TpjBXq/Ly89vg622GvcTN4ZCjzK672FFusOvNKjkAAAJUSURBVDjLrZPPaxNBFMffYWFDT81AEJFCdqB4ECEQWREV9pBL6SU97ApVIbDZAZHA3qbaHKSEbtPWS0VLSy4i2EBzKUVpAh4UJCG9+AMsrfi/+N5MNtktKAr9Bvb7fnzemyzsQDGpGyVUqlKAiwKGx9/TwJ3OYQpoN96kgbNofgT4Sncbh75v21UCbMyLxe05m1QAmxriZhOfvq82qOhW5hWZXwBhCyH8LxsvBEZqA6ZCPJrq2tSqgErF42cZzHwN0EjxCN6i2QSQai1J5WrJMEq68rO/ShYDfdkkqxolRwNnculHDHiiNpChfC9EUMW+QfVWJPVIBYIg8O6v1Xd2Vz3PqzgGlNDddtTdqWPglcF13UA8jDp7nzEqG4bhUMU7eTpcdgOsAOKo2+39wHODsgMOoLterbf+jkC1QSmgRxkAHDepCTBKDYC/Ag4S54BzcgD+ofRH/Q97ETIhNMcemiRtOoeQOviLCWJDUwd6MtRNMCcrNWPqoTGTTWoaO2G6kgBy2ewlU5qgIl1YUEAuLhAAoUwMTDb0jhdUGkqpgQedg9QRg8ZrtQG/TQ0sRvMpYKZxoI8w4yO258YAQ7/X1P9BxkfMZL6OAMaylmVVNl4yFL2FpIBdnuoqJ0DlexkFqA04YPEj+KgBjJnFcy2qs6sEWIxheNpfoU4eLE6OVw/dUgDnOLQYLn3DQZYHzhi/TldvCwm9gXNOV+85rZ4GzPi1teVfuysY6A1IDKIPp5vUyiuAz0ad/qcxQDqpD58kAH6lvc9SwGxvfSsJjDQBYl0A8BtFdDW3egcYwgAAAABJRU5ErkJggg=="
      alt="MQ"
      {...props}
    />
  );
}
