/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagUY(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAhUExURf7+/vj4+AlDsvLy8gc+qQxJv/vRP/vqrvzgfPvz19exLAdv8j0AAAGnSURBVDjL1U8xbuMwEFyW1y3BwnEnEFJvgkVSGoIfYAjwF2g7nRHA0pVBAMvXxY0TfyDFvfJmSSnJ2YJTpMqQXA1nx7Mm0c8DX0qKGNvQM0e2OMO8c7zSHyVswCD6+PlYr38dSCl1aWDFPF41dbs7MA8aoKrVqT7tQFgPjNB61G52YTVqNsMjmE24CyE8BafgPgMjQfHL8T68rX+DMWsIn0AEYdRukbBsNuDMnYm1LMWElGa5fQv3y20L/h7dURhA+hGpoyVAKFLEAOxvwt/wuNd66E+i3IQHPPM2PIJXVVEsFn21NosJuh3XhyYyW4mcalUtink0mFCf6uCEFgD0QixSU8Loabtf3m1SgpUA9AuphRgM1tGvtRMa09G0sW/tnIzRzplb/YA2qD0DEoxO2zkn5OKZ3hjvnNcOFnA53vfMmAnF4IQ4TPuYJyr6Lib0iC6fVq9NSCZ8mLxMkGEgcgwSrmNC9joyym2JHU9CLrDdN88o9m06aQuPtxIJU8r7X3xKwG0W5XKWUZlILt8yFfnYzpvR7Azl/9fp18/8EYbZdUy/b/gH7UDwJTR80qYAAAAASUVORK5CYII="
      alt="UY"
      {...props}
    />
  );
}
