/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagMY(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABFUExURfb29skWOvPz894hSAg2fcQUN84ZPQQtbvz8/As8idUcQsASNf/PP78RNDdSb/DGQ2tzYpSMWdm3SL8RNbKgU8SrTvHx8WZF2SoAAAFpSURBVEjHzZTpVoQwDIUjVsIAXWF8/0c1adIBUeooP+ptDm1CvnRhgdsTej0X/CPexeR9iu4LP5xr4919Jvk1xvAX3nmmw7frr/Imt4wnRyMJOBqabNRq+zeSxov3bkNCMLdHq/KZcLx3RliO6qyr9FmUN2pT037M85MiT6/ZN3NPwfuQ7howtf1LRiJ+LekmH0bezrM8A/HBm3X+VO+XfMjT89PUwHguQMNN158dFwIfxxxDcBKq8XSbTM4PxaHLnNIs1dj7YX6eMz8/FIdc78hQC+AAMMAgBrpvHcv6EeX9UccEYl0o1ZBTodQAKONcB0X6/vLQPC4igwpIl0dahVRy9ftB3INaprr/ot33iwdRXj/2ZDWeKuj/44hjn3mq8FWATwgqas3319Scb63u6HbdMXaOUu7LNTXnu2tqzr9dU3P+/Zqa89M1wWLtZCcyaxe7kEnPmpYtztrfKwK7ac9zv48X/pj7Ac6lT+Fizn+jAAAAAElFTkSuQmCC"
      alt="MY"
      {...props}
    />
  );
}
