/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagMS(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABgUExURQEnhfj3+AgynAOtygUulQUwmdgcNAIpigAlgAMrkAa10n+Ux6U9CR4eHu/k6BMTE+++xORqed07UFdytqi22MnR5eqWoDNUp2uCvC0uZoU4IwZ4twSdwgOMuQJtqlMySGD8Nk8AAAJlSURBVEjH1ZTpuuIgDIZDy1LsiK1d9Wz3f5eTEFY9o85z/sx8pW0IeUOKIKznQcwNqRdaa9F7u5mFG6P9SCAGPQo31fzkxIruSalGPeF34c5nh5hK/DaL4Yz4guOYIOW4tUmgJkygV7Fske+FGLX/KvVcoNTmMH50Yvb8vPjJndhxppf4pll4Qs/jumlfjnpJQA9c7VXrwfOD1rwcL/K91yLcGnh8i9k7JymlkgqbrFT6QBTy9RfaC6K4SifoP0v0Mex2+ux8zj/Wj/lH3z8VgW/tIap9K3i/0rPz687r78TSp/WXlh9vh1I5AdB4T1su//4rbl1pLWGWm5Rtxbc+J42BtdtCuwd3LNcfjo61kSXLMnc8HtmwLIn87pzfvUvY/9Qd3bJ5kG95z4fpJcxU8ejcLsP58+Wcndtsqe/nx/pdOKvWBt765UDfXvEtwSy0M09n301omcjjitA31Anatk082pnHdeulNTbPj2roH2hw9PUm8IeCP7TJD3jSOcrgH5GgUmjE7GgvaPoOXq3X8XRkI/lh5yDqT32/E26oyWlveAoaN4ydTqfAx8rA3IgBatw13H+v+PeY2ICxKcZUmLGph/2Piv9I/nL+lMLWPro/K/4zRUGKtuaRVMXL5Afzoq6/sq7m7/mu4LuCB5+DG78gJM1u77ok/GIqniEw8aqNEIG6JDzHkEx8xEwQ8kHsscyF1uB6gawwnDIEp7lJYWLk1/ULylrvMkHlhJuA15z/vLq7bldd2eR21y9jU5LOK4wW73tflMe7qt/VgnB31TtV0xUF5gIKKz6zs/tmhp/of+d/A/xORnoDPcGQAAAAAElFTkSuQmCC"
      alt="MS"
      {...props}
    />
  );
}
