/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagEC(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABCUExURf7UGtUXLAI+nQRCpNETKNobMAA7lv7WJP/YK//aMwZFqd0eMwZHrt4fNIprIebCJ724VvHKI7qWImuCe1u31TRpnGJn7lcAAAHBSURBVEjHvZTZkqwgEETTFdTpAbf//9UpCgVKwRszRtxDSS1kYveLGN6B/+rXsqaApl3zRimW5wrhm3TAAa0TndBfbhMvcqec4ZU6jgLDpc8eQf+G+3VQoVQcEvXY8vtVWOd2DuImJWkBVqShdSzPqbqpzgSlfK1kcZQ6nSaHQQRVZF4WQ8ksy1wWoWj+dhhlOBevgL8CoYUfLc5DXhfuriU5O9RcAMeBj7Dm2c0N/wSSUHtavTrJQLAj3uUxi0k68YqgkzcIHTCnA0H6GjlOOytPZ5HuiIOBnu3Iv4OvGQaFeZvdFwJ/wX2d7GY5l/kqsZLva9/2kfJaVGEswP512zbOJdVY9I/OZ8lvn/2Nz83YUPjsGJvdfWStdfZhP2bpua/R5GCRDZ9q2xTJ+2v37MG/P/jrHI3b+t2w2+x1GdydTexW+v9r6f6sv+cIXc/x9P6+Z5Gn9vo+9v1lcgVC+y/qmxb9O/D5fKbPFKCG+2tOz87agalMN3UU0yPoHuAbnsEh/Cuo3F7JiFSZUsxQEZ1/QkS6TClm6K6zKjPo8mMC1TvQtlVLufWrreLi/ijSs7PmTP6U6njE4Am073jr/wEbTkCR5mIHCwAAAABJRU5ErkJggg=="
      alt="EC"
      {...props}
    />
  );
}
