/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagHT(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABRUExURdgWOwchowkkqeIkSAsnrt8gRNsbP9QRNhAsuQ0ps/39/fj4+NS6dhE2hzltGLDAs3GTXCFqMWZbVYaWyo5bMefZtTBNZFVwqn+aYXmabMKDIT2XhKIAAAHDSURBVEjH3Y6JcusgDEVlAjReBM7e9v8/9CEQGGxlkjSd6cy7shUt98iB/XuC/4/vn2WDsYd+q33/nMgHj+m9UOZiD/17SrwuWfdac5trzTuu2cU96EW9Tv71pOr6dQ26sbysyCu95Jd5RaFS1m3QnFdaF8fiJD5bclqJzaqyNQL1nmT+NA4bne7wXReelFQOAR9G1QkBXce0SneiBkmdJOgqbMX7Q5JveVUjIF4dRorxM+Kfsbn/fUHBHZDLNAd8ni50axhlfidpJP8wTeHAHDJ14yg67/JBU1ZqX+NvvuL97QXeRB7xdGH8ckKMvNl6wZB2ZlFwmcjjjfkbRj5uFusuvpBnu0QmEX88IvpAe6SS+OoD5QoYSZH/PiMe3AHx/N3wjQJvU2VLRbzH65H+AdLXj1f0ha99xMfe8pgrP7sr1rq62dOq9YWANLS8s8nk3Jdv9eWcMdmb7eGFQi8y1rl5pcDb7KvvgJV0dludRafIA5QdFAuI7mDNUQpIdZlyUzz5KM0KAQ3NIwAoS7BV4iVbRNkH+0fb39DHM5YQ9ZN+cw1VVQdPIVkrcPPwvXK1XAfOLKh+YWmXv7KZ19RP9df8P1rDQFd81CETAAAAAElFTkSuQmCC"
      alt="HT"
      {...props}
    />
  );
}
