/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagLU(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAeUExURfz8/O0zRfA/UPT09Bym4CGs5SSv6Say7Ci07im07lZu4IUAAAEOSURBVDjL1YwxcsIwFET/jC4Q5QSYE2hGF6CQewrhmga7pcK+AaRLyXGz+4VsQTxOk2HgyVqt9q8l62VW8haFCqw/AY90yY6shDNLyyNdsiMfYjmGYHFgVapR8IIFOrfJgWoUixeWeY3Ce+CMEScU/bico3AGl7Z3HKNrXHLAew8r3niPHArHGIrNBCu9wG5KWL51bs6J16l2Jpy+ok6K2Hj/UHwozPGUwrWf+LqWN02+BToMl8v5nLNhmHzfH0WPruv6eY7Sdt3p1M7CyV5+x21b/LCXRs/mrtOUhd0y27HQjNmhTLZ/vxAiqOus3CFkF+NG6hr3EGuEIVLwx44ePdw3EngWxHurhSX+ofADlZIMIONTENUAAAAASUVORK5CYII="
      alt="LU"
      {...props}
    />
  );
}
