/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagCC(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAeUExURRyBEiCOFCGVFR6HE/7gO7XFLtnSND2XGWOlIH2wJF400boAAAHdSURBVDjL1ZHNbhNBEIRb2hfwzChY3Lwr8Xeb0RzIA/QuyRGx+A7afYAAAuVICArXgKXwuFR1x7EThdxT9vx01ddtey3dw1rJowFeTcPvh4AXo2r/6XYwr7dA23bPFfoYYxdRcMc29i3LdiUxtpv+7OV43HXBLNfYdyAigbab3rTtl8H8SARBnNdtDKgXglP7s7BR1kSCX6JrIaEN+AbfVMmjsEbfuVaChkn1mQ7BZBl2vrkWgnKjutFjDjTbOFwiL/iIEA74M99a8HOav3tiig4s+aBOaHzV4e+vm/jJ+w8OhKfTcMlzqXoZdjrAWAdCSd6iR+FeAHGCwrl9kxTmtXn+EZYknzDqSSkFZ+9eCWkhBePhpoRtGgKLOva0QJbiExiyQ4dkwbwml2raApUI1jTYLATMCpMsbCm11FpLGfUzD9TIlhewS5ZKmZPqub4rRDmiHh6xDRM4zaia8Bwcxz0dXtREoO7p9aR/PL/htkDx2v6LHVLvTqgV/+aPW8ZdAGruA5pcc/bV1OxMtguABiLhvTCbbB4P+MKYjY0IBmQnvckicwG6k/dkFNoaL7AJdy7BfnV6fYc4nKdVthrJ0yAmtglf2WyOcXrsWTWyU967wt9O+K+uTqWRR6N/w+e2d4PBSt0AAAAASUVORK5CYII="
      alt="CC"
      {...props}
    />
  );
}
