/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagDO(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAwUExURfj4+Ac6dQU1bNcaMd0cNAMxZNMYL/39/fPz888XLc0WLO/T0kOFRZuykRJuHHSJgzWtGzEAAAHMSURBVDjLxZMxS8NAGIa/LRlUTBbXJhC6FlKKoxAHxxLI5FIIBLPdljVjBgWn4jk5Wv9CcRfU6u5v6OhUEN/vLolJDAEn3+t3V+57cpchD1nNHGXIaTMn9C9AMEX8cu4DpkHA7UDVhGzLsS3LwcA/BficwNeZkOvaDsp1MNxxDfg1gG23Ipw+wG1mnBlGlszqxEkXMDKRJSoxRjKLFxoI6xNEZiTNLMjzvDD0yoyEQVnVSzUQoQ8gCnnMDcMQS45MpVwu0/SaIh1NzIUgkhwQKa81oDMnEkI20wXwDkLe3q50ek8gemjmjv6Yj/X6fai/v10/boeAy+fP3csQcLCLzr96O7le9vQJJnHlpto2OSAQs3yHvCKo/HFb7xSbt80Tnil5Lv1sxdDV5jXv3N62ANflre/8sA2cFThuEDDNwhwGCrPoAMoftgieBbji1wks2lSL5gfHeVF0T4Ac01qTY/QLm2M5DktpK8BvA3CRVcMEKUd9ANvIwvJySHEyg0ZlNFDFRo2ILYuVajDxogW4FfCTHyD8DSwrwGPZXPgWsYzUEE2mNwyEoWoCwzTXoqUQDSUVUMvIPpbAStWqBVQqKdEkZqbue4CWaD3AN/oTbTgdsoaSAAAAAElFTkSuQmCC"
      alt="DO"
      {...props}
    />
  );
}
