/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagBZ(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAA/UExURQlIk/T19RKBFePq6dEXLdQXLvv7+wdChwhFjc4WLM3e1325fzSSNlaAsFelWbTVtYelyJrInKC30X+cvjdoorJ/VNEAAAHtSURBVEjH7ZbtksIgDEWBVEAopdT3f9dNwmdrdV39sTM7m9KSYk5uCM6ouHxm4jJNl2m/NpW16fDZdBIrps/sjL9OVxx9frTG/PUz+5j/wxY2BxrcFt6iV91t/bm21KPJ8Ia4817ruHj3tATLA+/iVBwWpVTSMz4XKAms6DE2I8MiJ7A4AlVMoIqasqiFKgiDlN2naY+8THuXhFHlETN47kEXyFp2LNzWimzpvMN95ya6qNlbW4Qdaqj52kzyfo67/nsqQXJMZm3dvs1vts+4e6fUjJL9DHEzuJdgS7ioTnsI25yN5HLLZLl07sE2CInGVd3qOO59qiiPxAW5QedQ9GB42MhDE6cLiNdwT5zwGJ9mX7TxknSnJaJzH3ymL5tlWFcHXuIdxrqYmcJq6ROtnvCmeqaOTUrcrq/6bNh/zLiVkIER+d103AQUUhzfLNL5SxmKzsAI09Z6A1lvHng8jwUn0bmun6UNj/yyHguALL82nK+in60s8CzwBOI8g0zRgUsJpKfTA9SqsRxOJmoyU3CaA2lK6VW2spNghtjqiwK2ZXZutekDfzuQXd8MaHnjBOAXbNzsIeOjSFMS3d1ZGL6FlCrssWbCPDBxA1lzwO0uzH7HUxvx9wcc/v7Yx0FP+Jfs1/n//2+/+v/tC849Os7b7ds4AAAAAElFTkSuQmCC"
      alt="BZ"
      {...props}
    />
  );
}
