/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagMZ(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABXUExURf3hNg+CeNoaPQ97cRCJfugeQ//lQ/7jPREREeAcQA50axkZGf/+/vHx8SAgICQkJNEbPCglJfi+POE7QelnSfCRO5cbMmMaKGFZYZpEWPzbefTU2u+mswSw9pgAAAHCSURBVEjHpZSLcqsgEEBXrALNjRJB00z7/9959wEoJk19HCgLGw4LmWng8XEKaFx9zm+ar0NmxQP5zaM6wAeP7DfuszqI+PiGnKlXMS3q1bQu/OZRR6pVTItlvsqfZx/fUB9g9vENJ/3m8bmbwsc3vKV+npV+Y79O1UfCv10UvqXBf+/zLYvS5ISfnX40Qz5gujH9rcc+x5Qj0jr6NOh56uKuvwEy2As6JB0z924bkAQ76pFPisdNPX/eY+v6Zy/lgQVCa7A2nYC429vCl1zf+oHQWnP06UB1v3TcpK9aDFKTZEH0eIcJxWj/hvg2gOYWbMG03Nq98fHb/0v/rb7irSMQI65wrdL7zaqVUIbqkzOgDDCIiF0pdzMsmfgn85KLAbaVB/zi/ABelorubmbhkmPZjAHFjOMyWOXuZhtAu5XyomHk8q4z2305waqZyZhdfon9uW7n2fff1zN+uF4P+C7pY7sPQJWaBD+0u32uLUcE3e73XS4/tjo36XNc5wiagbh89/gT0HIveJGKgMh4d9BHAEe6c6M+6pON/3ka4k8QT/J8uX6Vp/p4d5BFYjlPG3nQT3m6+4vNm6G7nyGcsuE/FdBQ9vZemsoAAAAASUVORK5CYII="
      alt="MZ"
      {...props}
    />
  );
}
