/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagSG(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAhUExURfPz8/j4+P39/dETKNYYLdscMd8gNeiMlvPe4OBNXe+zumabQjEAAAHFSURBVDjLzY1Pa1QxFMVvFJm3TOYTTN7GLgsJQncDuUF0NYvkjbrqwjc4u4EO0tlVkCquioq4VCnUj+m5yQwtzB9cdNHzXm7OPfeXhGaHdUr3BMz/mi8/9gB9183mf1p7s5qvZj26rt8o5647pdzn7qodve9m745yzhJnmchCM6Eu968ftZcYvTqCF6RIEEATQn3Tajn3YpW3VYCv9qn4xDuBlNNv8yRPBwnIdJCjoKgplTqhmPIHc53GOkdGRZ4iMpaaOI6JmZVZxucDjpGnA7SMASdUnEgAkgCII9dhrEis0URukCd4hyQsTyzUR96nAlwRng6LJS+WAYbZr6eB/ZhCCC+pees9PWb83vuA3LvgxfIxeedOLujSufMztzhzzgnhHM4FgY4J1v2k5jtGm9zJYZkiAwA9+0XNzSq4LYVQAXdy/vnTN7dLa2C/7gNoD2v0IAB7R+2ta9shZC0A2Ybmzif90FhrLPyIhsaUXChTljRlKJAmUyNTuE1BVK0twCH9B6CNwq80ZBQCeFM2GSu5QeYIUFSFlEhvRKQVaVLYxZGMqDZwCEjG0iOgekIukJDWGxVqW5oeki7K19xa+IZKhO0fffcNLcvew6MAAAAASUVORK5CYII="
      alt="SG"
      {...props}
    />
  );
}
