/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagMH(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABFUExURQJBmfv7++SAKSlgqwNFoPb29+yHMAE+kwZMrAVJp9DZ5n2dycuBRUNWf6FvTkR1uLy+x2iQxqrA3eTp77qTd7WmoXRjZnfcihwAAAJUSURBVEjHpZOJtqsgDEVBBsWxWuv/f+pLSMKg3q6+9kCFQnZOpFR1P2lWv9DT6H/hD++/54MZ/S/85D3zIbWuGGkSqpa3utkLH6icLkA3Mpdkgbd5Xehp9MIHEQav4aQu3CgeXOKlOgzeAnumtRC6czOjL/kysbv1qzU1/pbvlmC0Ccv7FHb2/p4Pm1n0Yrb35qO/58F1fQ56eK5/HFrUcaL3HniLZS3bapzW2pl1W+Ka5R0qG7o1p9r3h9aK4mwwvXMamuuNcCkDTeLBNbGjRqCB5yCzDAhDjmExBW2pWTq4hnvDNPlDya4WvAyx2GMCOLgm4UA7zbylAPQnoT95WkqAj4NtCX8JHeunUHz/qN5Yy0ktZ1GzZxaezeupdcFTsMHzR8HLGOYkz4RUROFT0Ym3nbVrP7ihX+NcUNRMhSPsT3TmQXD/HNw/W2saGxLQe6/dn3ww1jj4hAo/qHCsHeirVBX9PJm3cyMSb1eXIDyNm8zp65RouC5wtRiOT5z0g1GWGg2rlS84zplGgDG65hG2jKVmUqbi4IhmkkYXnTlY5RFFvDoyTRKc4MQlqqokHdzrmf8VES/eWbFoKh/UdKE13W10zrLpkZOh5qt3hu05+iw+uL2/gT/QcaU/h/ngSvo/YD64/VHB7XtD3G+pRfP0g5Nzq9J2EalkLitycImOzm2xS2Z50pbu2I9M1zBuonJsrljJOtQ+0g8OMIdn5ehytU2p24mvi8CSQZVBVTLF3lFzpEv4xFy9i7BpfPW188dC/tj772Di98e3MPLT8j0M+gf0jD/eLvp5+QAAAABJRU5ErkJggg=="
      alt="MH"
      {...props}
    />
  );
}
