/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagTH(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAYUExURfAkMf7+/ichVPLy8u4iLywmX+whLjApaCDr3CAAAADJSURBVDjL1ZSxCsMgEIZvkMztGwTBvdAXcDicgyBZHcS5i/T162liTEG7hNB8RnP336/jD3AijElJu64IRJTI6IwiVv+MBIvoHNbaOrLIhkGCQqeUc16pKFJVHIo6Cb6Fixe9t21DxsK9z+0ahnef1xkGEwlxmTmtVIcihQnmOauBptlhqEuSMfmFDtNvg6jRCVP1X4YM1ytCjKD5Qim44Js2Ap06aYI+XQ2pJkOXIwzPPo9rGP4ko5bIaWQU9kmGLZl2GYUHZdQHeDMmqk+Tcr0AAAAASUVORK5CYII="
      alt="TH"
      {...props}
    />
  );
}
