/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagKG(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAYUExURekbN/EoQ+4iPf/vQfzKQPaQP/NqPvBHPqtN/e4AAAHNSURBVDjL3VJNcxoxDFU80Fyxhw1XW1PCuZUXroVNplfIFrgym016bZN28vf7ZC8MIRN6bh94JUtPT/4iex4D+vcIo268S7haWbs5RyhmdlSeEMKxfhHtsDzu4qAQnA2As8XWDmVVRztZW+cQxdd60hwmiIxkNZRSoq1nLgfxHRAyWSDYKrbbny/fWplr0CUW1pCdwC7UsVFqK3dqNOqCJ2bnOCQ8zwMDtnoCP+g/MBS0FqPYfP/N3FY3DRcvj2uHOodiVYDhwFcic/4lIvEpVDJNWqmFdmed3kszEcVXdZk1zpwVEq4jf0wE2CmnmteE8IDKhGbcHKJHhMmWq0xYwH1LKKpPB0KQW3dKuBb5zDmfnOmB4Nl44I0C4qyJvYIxr9aQ04gT+Qz2/OD3u+g3BoxOwbBJXU7OITEAIljvdeD4LvJJwt2ZDl5bwBiDbSx8vguDu9BcWv5hEWPcpifc5s6PcZtaRygnMvuPMc8LUpjqB+Y+NYCCEpWNDdVxByq1ssxRylBr0k/f5GCEN/kliebmSVuzRJey7OmrNvczVaC9QgdD/TvqybKOZNaUFY565JVSP1KvTF5XdKJC/RldlnQGH5ZEG/oLDP2H+AOAK4gvyPUEfgAAAABJRU5ErkJggg=="
      alt="KG"
      {...props}
    />
  );
}
