/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagHU(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAeUExURf39/Uh2Ut06T1CCW/f399czSFeMYvPz89IuQ88rQP4llicAAAEbSURBVDjLzYy9asMwFEbvkAeI0AuUgnYbgWYNAq3GYPBYKHTOINDaJSBvHZu3zXcl2SUNVTKEtufK90/Houc2T/QfhEmpaRpHzqpUdFs/DTROWUEe1yulNk3hhTbDDWEe6HhJmvNJc2WgxMzpWOu8GnXzTmv3Ayyc0lKnZUmfOCkvliqc2nzcFv4A+33hLGK3c2u2O1B6FGfJlgaz48x7uKWHZfGCXSd0/C8v+C6/B6HNHUL0wAXvoo84IWAsOQTn/YFCjDiRc6lfM3OguO3z0scLAgtNHiG8tXn5DUFrgwDG6Fd9RUeG7w3QuDdXdKTb3CH0WvYZVF1rzfx1JEUvM7zmKrbM356QRZ9D5iijrI3oSLSQYt8WxCOEMwW3fCckU6ngAAAAAElFTkSuQmCC"
      alt="HU"
      {...props}
    />
  );
}
