/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagIQ(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAnUExURfz8/BEREfT09M8XLdwcNNYaMBkZGSAgICQkJA96QDGMW2ytir/azAM6gfUAAAFRSURBVDjLvY0hb8MwEEZPxgUNCbaMBypZ4wM1r1SHN8ShQengWAerMA+Wbagaq7Qft+9iO6m0LA2o+uyev7t72Wg9zQs9QDBry9dYixbJri2ecKy1G7KFwS2MMUVRICHiCcewUPSYIdo+XQujzBC2zLPmwujQ96wojuMm2P1E6w3pDnRapzhkvV1RGo6y1VH4nxnCg/np6uIcw1/8mevlGENEkBRdhXDk6CEcu54Eb6QUQiipFt/St/TEVcCUUiklYSFIRl1a5dtY4eAjPpKUYBfZx1W8+IxXEAJC+Y8vXoXaCv4H/EuCUh60qbZpeiV8YnVK9TQijHMP4X2at9vCfpqa9q/7w2EYXHec6xt/oaqpqirXJEKsBpqanHONS8CIfZrtyE0zQ8gDyGXAcdfPdpSVJV+Q51melbh8eMqzJeEpwyLjh82wwxSfLCmb5g7CL9d/Zm1yG5PjAAAAAElFTkSuQmCC"
      alt="IQ"
      {...props}
    />
  );
}
