/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagAW(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAqUExURUaM3UuT5E2V50mQ4U+X6vnVNtwbP/Tv8cjb8mmk6eyZqIy57OApSuh5jqx/2PQAAAFrSURBVDjLvZC9TsMwFIUt9QVqe2TBlh8gVhbGyMqAxMLCKxgJdUQkalnK0rkVUpG604UFFngCWJjpwsNwf5yAUJtKFfRTbZ977vFNUlF2U4g9BIJzZRkWtw7LQBUTgrXOFcKRqC6hFWjZBF0MhwJkCCfDkcUOLaJ0HCsEGvb4unbQdVQkKGdpgg3zj9WM77cPSCkO2Mnr241dCwfuhvGinm0OvFQP8X1ZP20KzKvPGONgVfEMZa0x5jug7PN9JJaPUik0jVGKl5R9ocyPCWghFpoojekLOPAdBvAOIJVS0ihOGZ6Akr5iipZsMJJiPEHqSTwfy7VwQMI/Oe0MHF3VsjNwMBxJL3XjkvApoAHpJ2Poa+3BxR0crwmaANZi6ptmiqTVFzng4QclKjp9q/JMgMAa0ZTBs/HwEXka0aLT6XOekHeTibNuTv8gsPUddgn09v0V28lET2QZ7a3iooe7wOL3DfZ3Yveb/8oX3a7/NdUGZE4AAAAASUVORK5CYII="
      alt="AW"
      {...props}
    />
  );
}
