/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagKM(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABaUExURfz8/PT09D55xESAzdAXLf/LRkOTPP/HO0aaP//JQUF8ydUZMNocM0yfQkaD0UeE0qrOplifX0iF1JjElOrv6aW1QYG5fEmF1MrfyHloOa06M9no2EKBtEOGlh9FeiUAAAIXSURBVEjHpZGLooIgDIaxvBMFama393/Ns38M1M7J9PRDMsa+bZA6Z19JGVN9yZvzl7w5VxkNfDJvRXv0ZTNftJkvDRNB2cReVuZ5buF/CvxfCYpPMAWo0uO0FEVRYeADUxa/r/yhj4i+qlBAJce5iIr0fD9z8or6mEhSThKsleLykoTvsJGPuL/G+R+8TMiYVm1ToI3r27Ynw9238R7viUqs4xbstvpggHSOEtnElqZPaJvI9GPch5/4mR/Ic0fxknwl7pBAKsxRavzxZJ7fjHGuz3cInJommmSTFbxBQ7acyfRdskZKyiemfEkgd1jBD9TYwFA+y2AT6kHa6GZ22HbMk4n2Aed8/1wyXQ8fBR6PYQWiXNJITuNzAkVhaMsKZDvLJEZ51Svq5+VA/CAl/eRk+e2g9YFS0IcV7MNkqDzPWzyKEc6jtLnedJSP/Uvo3/AFmGL5q6d6jRTC0UDnGGy7lnPctF7LkyxewMCi/xR5UpJO59I8vKHDqfLtIsHd4S1Q/yq0lhnJdDTEqeTOjv6Ezjrfe7peKr6Z6du+34pHPuqapt/wz6ZpTs3p1DSXS3OB6fdQsLFCFHB54WvEHU9HmuO6pBnv9setmvLP/XG/VkcqhfAJ/xjP5onC/tUPRf5ZL5V7e6hi7zULkfSJ6ztf8Av/qLcpZmH+uat3S9G7X9YuLIrxZdULLuIf74/rj4mU232lH0kfTtGKnsxAAAAAAElFTkSuQmCC"
      alt="KM"
      {...props}
    />
  );
}
