/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagBW(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAeUExURXyv3oO144m66BkZGREREf7+/vPz8yAgICUlJfHx8XPfwFsAAADUSURBVDjLzZMxDsIwDEXNDWKfgHCCSqnUFSk5AAtXqJQNKQMrIyNTJW6LXScSBZF2QNAnx/k/+euHXZ0t/CCAiERoy0a0fBeNaIDYyC9vi5bRD8tPbMgA1lkQMDPAhgHDa7QqweRhmTGTe1NmLRzrHL4QuNa5wLnOaT7QJcaNdKz1FFJqQP+S61yOTWnAu3ZUrfNOptCqaSAEHwQf2iBT8Gr2EOosCNyFYYhRjuq+LyrGmwY+syDwh3bTxNm3dvN+bje9tFs25VZK0wnX2G6t9Nra/QBbXu+gS34JSgAAAABJRU5ErkJggg=="
      alt="BW"
      {...props}
    />
  );
}
