/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagBT(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAASUExURf5TKf/ZTv/XSP9aMf/UQf+ZOmF5E0kAAAFcSURBVDjLhZJRjsMgDEQt+QRBzQGC6D+Sb0DIfyTuf5f12JRG2l2YOrRlnscghba5bpr7Z54Du8yBV1sATebALnPgJQugLYBTHDjCpjV06BOw7tIB84+hoNqwtg+wYRNPDA445AMAxNCNR8xxvGUAvhGjFhbQMUT5AtGkEywaplZ7ApgYekJnL/mVgMZo4aokfwBPtQVwyhzYZQ4kvARfH0Cy/VhsSScJczYJZ01QO6mUKUUJu2FGMXwmimaarU9CJxLY+/NISNFiGjNjW3wEC1FJqSakJ10v7WbqGXYSA2KpqRZVzX489rIv0j4kIKA2yoSMbCGIQkKFhdIbopv0A19RI9yrqre7PjnbL70lEtTUCfXOn71+UmMIvRZwEjQYhJhq10U21DezE/bf3FJrt8iCP+Ajobk5NMJoDPhD/AUy/Svzb5oDJ82BixbAvQCmAxSYD1AgL4B74f8AL3yUcbcLdKkAAAAASUVORK5CYII="
      alt="BT"
      {...props}
    />
  );
}
