/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagNI(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAnUExURRFsxxRwzBZz0P39/Rh10/f39/Ly8hl31Rp41tzOlOjhwrDj8O/s3vZZR2gAAAE0SURBVDjL7ZOxasMwEIZPb+D6CVrjBygULZ1K6AMEzAnaePAiQdsM2ZqxW/IEARtvgYBL10yaXYj7Uj3JNlHsIOjQqf2tO//367MGg2C9Wi2Xa0ft3Kdv8OrXAu79ujsHTCZxfASiseL46C/PAa4sEIah6W1dGUXdHEUBXPj1YyAYAywIGBUAcxxj0HkjBjazvXdu+vu68et6APCm9gNVnm99wENRN/kAwIQeztH2qubJYct5m9ALp5C0hmZEUeAMHzfEokk4UVM6Ieknflui3qel4WnPnJoQ4Ig+1nss3OgUmJczrdPyFBAo0SwUAtPiRevnDTlJi0KBGUghlKKlJLnqS+vDzjip2p6B2SGCivRUfDa5dcoGUhpAOQn9yV3rOjmA1fz94zQYAiNl8H+7/9Lt/gbecy2eVmiEHwAAAABJRU5ErkJggg=="
      alt="NI"
      {...props}
    />
  );
}
