/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagBY(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAzUExUReFAUFi2Zlq6aFu9alCpXVSwYvj399g8S9A5R8o1RPDW2NxeauydpOGWney5vuKBiqXUrG2Ph4MAAAGgSURBVEjHxVbZlsMgCNU0RklSO///tQO4gCbNtOZhrksQuKhgz6lZEC+azBiQuZv9Dn/Feb3B33DexvmRP/Hf9r95/z3nfzfeeG++bJ63ftEhfMunqYakXvTN0PziKJG871QnB6zn9wLjK7kMidBC8tcwr6HjYv1Q2jL/a+D74UzFYX67f+D+GciX7o9R6P6BW/507UzBvin1Kf8Hv7zWEZQPS8bn+ouJhZCFvFSC7oofKrwaWlRrQT3/82A6g++FlD86RBiC1G+UH7mWcQmgWuoftLR/wP2BEYDVFTkQqICKDcD3D3R/sQIohxIVDjL7mielniZ4h5bQaU3I9Ycx3Ob/ff5rfnq6a8n/AH9DPtbv8RGmx4Rd1vh+6BlBXNjG9h7kX/Wdj+xvpxHw/YHubyumrl2h5v/nynGyyVq+ig+5/mc0pwR31LZ8p2HTZGVpW1sBnx/o/NnLFpp1JYZVJlZbWUj+3BCofviMsH5uPjHP56xZ8SO/w7iQdmawwL3Vnellf/Gai5emCtys9Cb9dNfE/x5mWVP+h/nl/+8Y/xelDzpxCe9CGwAAAABJRU5ErkJggg=="
      alt="BY"
      {...props}
    />
  );
}
