/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagHN(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAeUExURQF20wN62QV+3v39/QaA4vf39/Hy8geC5AeD5rPV8D5BoTsAAAE4SURBVDjL7ZOxasMwEIZPbyB5y1aJkLlgVMgWjMFkC4g7yNZFgmwdAl479gkMedveyXJjQ2sydGs/y3e//vt9m+FjnXfo13mD7nptC13X93Lr2Jv0Ado52ya35u4cwDm33TbNVMc+aeeewK2zDFTOSrOLgJlhTSWtmlkajLW24pGRYs3YK6l8rATW0aBHWBolmGJopfILoBRoUMBw0WLkR6SWK+gyUkX/PvU6z48H9sOt/kbPAu0x9zDTOYCIAb3HF7fjiiF474sWThB4HBD92WykDjf0OGqsfc0Bzwv4BB5xlpd/xWRHOAEuILdbGveAfIXj8qJLgDCinHN7JKI8iqyR8oBOEIlSjCklt2MrCcSavTx5hWykmC5mI40S26ynaA7IIF2GWypQ0exSCfzMA4H/v/sv/d2fSUIqCfCFS08AAAAASUVORK5CYII="
      alt="HN"
      {...props}
    />
  );
}
