/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagZW(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABLUExURTKUCTadC/v7+/X19RQUFCAhIDSaCzOXCv/TBP/UCugoGOtHOfXY1SlBFj8+PG1tbStwDtPT0/GXj6Ojo6ysrG9eEtq1CuhWSaqODkGHc48AAAGISURBVEjHpZaJloIwDEVDF8VSXIqK//+lk6VgGT0zbXg608Lhpi81OQXGQ7dH4Ec47BB47684Hg9HFk42ovvLvd9zEvFo4agV3M4U4ApaGXshC+oAxpg7BXicVCLecA7np5o3hnN46fmcQ9+shZccxqeaz7/DS83nHBr7oeQlB9/UDxt+qaWW+l/QGHmYGvth5VPa5NBQ/+TbmGHgQXJw9f1AFHIxhChTyzk4XyewTNkUQrI5FuVQz9s0oAKKxoSxLOVQGYDyT2FVIppCTN45V+ffmjgIPUTeAP53R5pCfHyz8gX6J4l/y97tun7xeMHJJwv46SjrR74gXcpn/pKsjzswzzl7/LudXa2AkZnQFGZZfPKubvFl/Ygb9x4udP/adTXt1wmfs6YJe//aw923a7Bb8b4XR+K//bvFxXvL+VXS4r3tKPr0DkqevbeeIbDxPjafYVB6f/QnHR/Fe684vwrvvZKfHHvvdXzM9a57jwPpVfU7HDipd/X7W2O9f9Q/4rBH4y4afgC37jqnnASlkQAAAABJRU5ErkJggg=="
      alt="ZW"
      {...props}
    />
  );
}
