/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagBM(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABLUExURdEVLXqPvuNwf+mQmvz8/AUqiPT09NQYMNseNdgbM/PT1u+6wNs3TGi30+3l6b3P4eFYaq240zlXoTCOIpGhydoEBZNGKl1tJphldQR2Nw0AAAJJSURBVEjH7ZTbkqQgDIYRMCGIqD32zLz/k24Conjoand2925/rUISvoRwUJnQ2akVNdY5Z5v03c42amvcWynbOQ3xkZCVf0RmRzve4BvrQ/B2rvI/JutHjurdDb59QAzO2OFR+AZAO6kq3OJ5sjC6McKU+HmwXZBu07p7fNsONiVMvI1ctUynbR1dInTi24mXizpLRJaLzsvBvCNy9VNgSo5kU03SYL3JfGc6gCkZtYwuLxVsiySPspWET4LcaBK5ii1TWeMpei0wdW+bQ+osusHv8tWwu8O7S9caSUElYWrp4/g6XN6DvP5zBFl34TvjYciboum90v7P4AO5hScykC8k3eMfA/DpGf0y/y6QhuHIH7a54psYRwodDHPiJ+mOUW70Sx6TCeVVU0oYo9w74Zs0neA5gPgxDzvlL3YVNQWfCm4AEfnapeVgW7OkxsLz1fCZLzTn57uffz8bzzc6al5OveSXRzjzfJrC55d5Xrc5//I2ni8kV9VFR2sJdX42rIUpnuvS13JkouYg7NERwC85xCLw1PcTh4C8ftmjdImEqI0xI2aR0zrQ8o1ylp/P777/5hIAcbMrwlWKVQquxqTWez6qfd8o8h6rMQrxiBRwF8MA9EkAprarPXKOs0wtAAyCD/y33jnwpnQKMPClxB/x6vMj6RN/xiN+XuC/wyv19XUafuZfR1QS4+BXa5tdx/bKt7dd+99x9ZlLlspfCRdvbd+PyOzZsJg3X23GasRu3Cn2it4RXn1j3eyqwJfwX9Y/DP1ff6ZfJHg/p43jjMwAAAAASUVORK5CYII="
      alt="BM"
      {...props}
    />
  );
}
