/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagTL(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABFUExURf4QHSEgIP/IQ//KSf4fLBQUFBoaGv8vO/8oNP4XJPX19T86Lf5bNW1XK/i8RP6APdCjPf+kQZycnM3NzaCANGZmZtu6baMQphYAAAI1SURBVEjHpZOJssIgDEVDoQili7b2/3/1kY1FnzOODSgp5dyQ6wjLfLsSYJbtGm/SfbvEZ4HHfIU35mkfl3izWLtd4c2y2nW+wGcTrEUbAs76hbM+vO6FypNAbiKUoUnN635ZK48usgLu60egPi/rrePRRZttCPoylKUqdGtfn1y0aEMPf46X+saTCdzEdwFeUZrGsMC6fcsj5oX2xUVu4rv6QntdFysKt+Bo8HzPcQCD3qSEC2mwi2gDlVCosJzxOxDcm4MEzpRFxEX6LZ1rUVelnHN0f73AMZ0+7RNewhsVyDbQScc6NBjl1IGXMPs04aTc+6cKDI9bpUSnbITK+3PCSPq4DHZggWEL9QKqo6vy43kgfhQ5k1Y70LDDOrs+QmlK+Nw4x14E6AYDfrLG1hVtAqT541ABI3hah4/1X3k/jqNH985930epTjTG5j4HZFDGSd2PtOGfzOavh9w5vrGReI8szjSdBOdp7oNE/v2jjJK0GyAFkTs8p2NSHBuPkUsTI2BVAyYokuToHF1/01IYtTA9SA5EqgWUL3r10JTkpJK6B9xyjeycNF6Bhmw3cIWxg0d/l8b1wIdVo+fVue312D/B1+l5cg4b/zo6ftHGf+PJuTkCDX4bJWsTJXlU7+6lcdC37xl+8ZRzrXPSOL+CTgBiO5r96tw6g4Qcx8mP9AS1dvlo/YUar0ehHIlVpd0uQuLc5pojNeme4/sL5u+PAL/GmP/sM/weY5rjBRwWd4WGP2T8P4wFvGbgAAAAAElFTkSuQmCC"
      alt="TL"
      {...props}
    />
  );
}
