/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagOM(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAtUExUReQjLd4eKP39/espM/f39w+BEvPy8hCEExGKFRKNFRGIFBGJFOxOV+9+hPXGyN2ZF2UAAAGeSURBVDjLrY4/awJBEMVnWbCy2CtC/jUh+AEWT6wkiFksJU2wtTiuCiGNCFeljNikNF06ITYpxSttRQKXMqTJF8nM3J2euIuE+Fxndvf95u2Bv1b10qILOBCw2AckVGotU6lUWsaYvGJvAs//UEbVVOjakLuuDKwW1ysEaqbotQzvGSjfd+58BnbVBI3Wp0l8qR2A1P63MZ1E+7XAtE2ACwvLmHYbn5CNZT1sLH1ZN0EQtnGFCPE/DEJ8Qkq9ulpoLUshelvCYw80Wl/lBF8qhRb1QEoJH/pDS3ABmAGIgSsBCQrBBIfQB9ApVhB9PPc0AZzzxaQsjbeaMoqWe8h9PJwUgNhDKBAClOCSLxZ3HM8sSuK7DUq/9agn0jFYz9IlfoGgEaU87sB7mkmroITsPSFyIz3yiBIKo2kvPE95XlYypReAjVx85PTFomcgXxCsHAAHCcrbAcbj4ZAScp08WfToBkaj2WwbOJ/Pp9M4LtY4fi8AZ28WvdqBySSKLEAUkUHKoSh6KADHA4v+BBx1u4NBv7+pO8CtRTf/B34BGO4y0YNj2joAAAAASUVORK5CYII="
      alt="OM"
      {...props}
    />
  );
}
