/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagSD(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABRUExURREREdQYOvj4+OEbQP39/dsaPfLy8hCFNRkZGQ9+MiAgIBKMOOcdQiQlJA53L+QdQeofROkeROkeQxNIJHdUO2Sue9Hk16DMrr8vP7UqOswdO5Wl7YMAAAHeSURBVEjHpZKNuoIgDIanBkYolml1zv1f6IGN8aPY0Xq3YI59bPoE03Adr+N4G2/I9Xa1nu98vowdoNvX2I2BbuwQl0tjPlvGoLWeqKwbusF6twuudXo9ieFTUG/fYWgG6w2SxunzMu8gvR2h+QzW23fwGYHe8BqyIj/16aDX6iWQBl3wKjgbk3QJ5aPejZDWl2ORX5rp9VSJo2R6rX5Etc/IM33rfhOeOKiAnzhVZYdVZf+/ZK2mffrNCkOxz4n8UICXU38XmJ+qyG8xC9y3xRlohGo/0LYspZ9jrk97AdbyDTTFY7++DeKA/RjPg/oV+A41+hvqTb3Wj9py8kZ+wjBlU28veC6LiVNiVq/QgqskMcuoSbdCf5ZQzI9z/R+glK8Ne4yxP80gaZFJjAtQsXeGLnhKiQrafIx7TIBKL0jb64ekUqz1sqiUtIHaYJahKlCIN/Q4e04tS5T1OPsuSnozS3lMbzL5vd8PWK1RuHgzfX9IT+2Nn8E2v/SX/YAh/B3mvqroL+ULKQ88NXGk9bK/Ubb5ORr5Os6M9Y77OYNU6zgDTBh+s+YdsNH8qN7KAc3lOF5brnVG8jOAjZ1zEDM+8rkEfMTm/JDsSXTO1miYcx8OvoBm/5z7V2r4A4WSTKr9rmD+AAAAAElFTkSuQmCC"
      alt="SD"
      {...props}
    />
  );
}
