/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagAF(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAA5UExURcQIEhwcHCAgICQkJNgNGNAKFQ8PDxWcGRmtHRelGxMTExUVFRkZGeeEiRcXFxgYGPLAw9xTWuykqHPBIB8AAAHASURBVEjH7ZHbkoMgEERHAzGCN/L/H7tzBTSYrFVb+5RmdLCK0z0kcGvJtfRoCb78n/C9LqkLfC8yA6krfOZu4kPVoP3b/Fv1pnzv3XG9n38vT3lSXrw+5B+Umbrj6fHX+YQwVkyYHvXNG1zQFarrO5X33iYvouNC2Y7yu6I+L+Nc8XFeQ3UEHQD6rl46gsEuzSnnay4/o3Safyd1MCTNczFQyC4hBge+uj9NMJNcdf8qXwze8on5VOeXIWR3yrvkMk974x/jTtBNUzcJNeU9nn5uT+Ud7+t886H5J+H2wtPbtuX70/7IW/7UEudvSX//tDXyD/w6rVj2Qb8dQ/z/s9UZv5ZU8iAhD97h0DNS4GfcOextfhFmWResVQXIJTEAwhPifhxGrEGafRBPbK11weMgN+D4xN/MsLID5ce4xAWr9Bg9sMHsADcpAX8P4yGfXhCLCk80kDyT8qnwbvyh5osRo2oiDvjQ8WwwaG/yJb92sPhBXKQghBBDxCo9BGO9WfD9M0pdHYh/lUFQOxT0kP+iWLHZCQbTOBSd5TeUZ/6Yf8q/CsKdFe4BS/olnpG7uli/wofdktel/Ia+/H/xP48ZQy3KTTBbAAAAAElFTkSuQmCC"
      alt="AF"
      {...props}
    />
  );
}
