/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagAD(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAzUExURf/MMQoptf/POw0tvtkgR98mTtIaQf/ON+ctVAYkqhAxxRI0yxQ20NY4KeZyL/CWO//tsYLvnwcAAAG5SURBVEjH7ZDbkptADERlGDwLBLz//7WRujU3VrHXqVTykpasGao43cLyI9IU6SOS/HN+D+oNfm8ylHqLB1ZZ3H8vv+kP8XnK2i/4LahLMn1iftt3NAva9txU8rPmL2gO3BfjN2s3gPYtI5NVhffb4CHbRfDIedzARibQ8cyPlCM5vPTn8m1+ygQw/Nfy57Hj/Ap+NBfR11mv92f+KPAw6PXL/M6DG8g806DsjnrCX/MvyX3+eVDnU37mBl/56Tgej/NUl5d8nH+cn5+TreF8QlkvPNNzPtw/FTThQebbXLtecxat8zhN5EXzU6PdIgmwUmXo20r44sbbc6OTWxk/oCht5j+Oh2I27SkDMy3lplPwPluHWwgM5Djw9wv3T74/6YUe4jQ0l4O8fYFaiEndUqeWX8DZLzgBZHFl2qVIcovk++dawv2/zw8w1n8vv20vxeFC3hu/1mFzxfdftxe5J5QfiYfo62Da0CYz5Nv+wFJnoPlfcKsG8kMwo/i7VAbF4yaRxv39kAJV2C7d1h1Ppe4wHqQbULf1+um43ZnK5OIghV67+DXefwj2KS200zN+lKyR/vN/i/8JEKI8RweOQZgAAAAASUVORK5CYII="
      alt="AD"
      {...props}
    />
  );
}
