/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagVE(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAtUExURf/QQN8fOQMpgP/OOdccNQUvjv/MMtEaMgQsh+nr8XyQvUdkpyZJmIebx4aZxeXcNm0AAAFhSURBVDjL1YyxasMwEIYP/AIJ6AGKJzWTQeA5BoHXLAGNBYPnDgKvQSAw3QtN3qcQsnfIG/Qx+p8kO6F1DIVQ6Cfff//d/ZjoP6CyrACsQw0zsVKhVKaY7KoKNWzxB5UW0xSk5imoaVSpIKzBlUEbHrFEoCwxlW3bJNe0fGbflm3zRLi0XJxJjA4ZDvykudjpQPurwHaezf0D54/vAeO9AZ45Hc3+dXt6NxG+bMj3pvd4+Mz+rT9/9lAfnsFlR7jzMTScgvo+4XsErjgdL5pAwKG5OEkW567uckdSujx3Usr85SDZOLc6yOBYHygeEZKP+3w0vIV3EoGIzPPVIfnRgDFwi3sElvMs/iIgltVSMOjxxRY2QiwIUvEUlEtroatxuybNC500VKWFGLcLCq3CmwDLNel51mS1rrW12qIFG+ewg0WgqzHWXd0NrrPc6try7pm6SB1ewF6a7cbALe4Q+AKvD3ZJxlrXnQAAAABJRU5ErkJggg=="
      alt="VE"
      {...props}
    />
  );
}
