/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagGD(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABIUExURdATJtwbLwKCYv/XMP/ZNwWTcNYXKuIgNP7SHAOKaSyYYFWjVd7NNXyuSPq7Kdo+KqK7Qu+KKOhcK+3OJsLEOOEuLZg6PUxjVGplC00AAAI2SURBVEjH7ZLZlqowEEUrxIRMBCKi//+nt4YEsKVbXe1b3xPJWLtOQYT+d4L//Cf4mE7vKcXGK2y9MdNb+GRMzyT7K+TNGyWkaIgnEhSnMaTpdXNT/YmnkXdMeKWEFCQYYQSBhuqPGlqU/g4fWqjiyoEGpdqmCRdEtT5JT12b8HAJa2TPJEgZZtOwRW+/mmTYxbEv+au9P5egj7Uz5/q/4fEqZwHKeemXc+H5aY73QT/wJkxI5BFLXPB+xoyrKZgnfKwRnhcpL/RlCnVL5n+M53bM4/5JJzTxpkaNtL9oyqJGs6KSxPuVtzR47wO9ZcITOb/xcdGFxxuDrJaBti35W2y4HvgzDZwb21WdUVlnGtTV837zpk6MwVIC8h+c005f2AEfUPzZNH9IC3V7FflbdAa2t7gTnXPDnFqAxdOiKWfBQLsDayKi2d8K7yfnfJhaHCBkM+KZJuAfxL4WbPOnNwjb8RWpxZEWnF0PeaqfhlYe4l07vmHusyu2uDOe3w54W/1pQK7rqPO+q20EKPjAWPDx92fULAtk8O1UCuh8nDOeAQnHPEd/l+KBF38+RNG3dHkE0ZhxNe1CeHrHd/WI4S7OdG/OFbx4OxbHqzluITR+5dcM4eKOdQk1ip9HXjTM4ic/VpvOwy5OYOC28V/N9VEJjUccJMlq7p5pLUGMJUHlQ3LPlWoJIPcrb/Ci+b4EW/8f3OE6Jveq8CrRH9YE5D+5dzQRvxP9Y97SHGvlH9Cn8vxF/QMNhDrqIYxiVQAAAABJRU5ErkJggg=="
      alt="GD"
      {...props}
    />
  );
}
