/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagBR(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtCAMAAAAun0N9AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAABXUExURQKgO/3SFgIqewUvhAOkPQSrQQGdOQOnPwSqQAGeOv///yKqOG23LNW/IuzPGLrGID+vMylGdGduVZa/JbaiNIicw09sp83V5u7v7LW/yf3aQP7pjYWPkoWqQkAAAAH6SURBVEjHxZWJkoIwDIbTghwWgYJ47vs/5/ZIr1AUx9nZfzpCab4/AUOBw3eCF2vNoVHjDd/YOCcaH3vQcy1AJvbYI8dA853+mB+78Q1f22Pd1GqQRTEwxgbhpjRGz4HMtVxM1zOtvqtT1p1bPpW7XtcmudUg6i3BxvWmY7G65jN+PLFUp/ETfrbMJGUh5WS95mYvb5OfpsLJOmRLgK3k5yLWeauEFT/2GdwZ9GOOL+tSDTMVMz6uggof6Cx8LPKlkb2GHcPYz0USfsIV1U1lxEAZFDrmcVS6LpdMAaabAhPxPjljzyPKeHAzJr/adxk+alfG7vfrzVkc77oMXshofRCUT9tV6oSX5YoOt0U5yLShU16k3Woq5pwHj6XgaYh4mZ9rXDuouhdzK7efV/nJ/UtuZDxU6RddxC1//6A9QB0gev6TT49SDs/V8zcc5P7/UyDRpVgeIbnLqbOW5gePvoSJU4X+8wzWYJ3sjfj+X/Gh/wF5RMukBnDvH8Hd+4dFh6xEamHOGOD7vwERuf0n3DvuP7BTZdj/eNj/YLdaEOv9dw/WqoETsv+DX8jEZn2S70+rpePXXLux1oL//kVAi/GOcRz1MNfw+xvHxzns+QtVlfr+txXlYwGuVio4REYO8YTE6DmQuVab8cydWz6Vu55Tbg2q7/Tf/C9odDwmIfCheQAAAABJRU5ErkJggg=="
      alt="BR"
      {...props}
    />
  );
}
