/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagCY(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAtUExURfj4+Pz8/PT09P7+/vHx8d58JXF7XPPj1MLGuuaYVOy5jISNcvHQs5adh0pXMLTazZkAAAIDSURBVDjLvY8xaxVBEMdnl4Ca6pYtbJdhIa+wyPG+gCwLUcRyEcV6DYgQRQmvfYSHYCNiCq3ShCBYyiNgZcBCy3yAFH4AP4Mzs7v3DJ6vEv93Ozs785v/7cF0vbbhnwP2D6A31q46Vg69RMuHbbDTvu+ntpeztT2LdmM4t6YDyvilMIjz/b6XnIExzd7U5C/ALH1ZC8zSAzMOPOdw/UNKr1u/A2WM6uq7md593P9+mMhAdZ2RB4xSjHLoXqSi+095qqMOO3BCCwDUcQWOFDsq7lKVJKHrbjQD4HmWIYB3EH1LA8DiQdmhQptp0JEUS6MGUFuHK+AeVxWUm0GFZ+k3oDXKJ+QKwx/IJ8rMZX0drrhzAmO61oC3oEeBK81gr1Vc3TU4eW9L//0eGzjHfa5D8dOgNdI1H6LWpeScLpPgkOS4vHGczhw3HHKkvQDyAcI0+hPqO9QrOQRAcaDHf37GPT7e+cS1IpDI85Ncy7ix3KUBRjW64kCZ3slPgpYb3c2PpMJ2DOjC4CKfyj5Z5jn3Lzmw460sxNVl3sVBDWD5V5lGyejxPIwCGBd5fnG+yAc44uC9Rx9f4s8fkwNPBsUjBAe+SE4R8eIcY0AvBEVPQIwheB8Cz8Syc4Fy7jigvCFlxaqS3wRKvVSH1SS5gxiYjuITy6oOceUwFFdZOwuwTv8D+AUfPfLGZjzHqQAAAABJRU5ErkJggg=="
      alt="CY"
      {...props}
    />
  );
}
