/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagTW(props: mixed) {
  return (
    <img
      src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAAtBAMAAADrb658AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAkUExURf8CAv8MDP8UFAICngYGr/8qKv8fH/f3+BkZrba24UBAusvL6nUKvQwAAAF9SURBVDjL1Y9NbsIwEEYnN0hyApJFDoAthNg6INRVN2QdRYqvEFGWsCkcoCAugjhdv88O0PATddm+2OPJzPNAJL9juujwLn9HeNvk237hND/3C6vdR7/QNBeh7gilGDA/HppmedznyKeLmhQ8iqLABJNrs2vAaqO1MTNbFGjVlouCYXX8BWHPYWZWW3TQZr+2pWittPaCJqOiNfBAg6CMUf4n1kYpM7JXauxSlFZqfuCfPOzp/hCsF3BLqQk+UxH9TACT5ScEDFOvhNP47DMKletVNrPZVVirbStkoMpcrCo7aIUbo0vPUz4IQ5bppC4+ThimoMKmkaaDpxNgIKD9akKWXhlI2s8vhOSObj+GEMdJu1M8POM4chUyELzF7Y4SNtB1uFocCmpsJFFEDSkXksjVIggtvtwaiTOY3IQHEhd7hOipEEbBvRB2oHFFQizBjSBgjyVGnzLQDQXAEn9FeMtlvM/p4gJeGMRPFVdlPxBP2DmDW4E3+gjlv/AN8O8Fk6YfvggAAAAASUVORK5CYII="
      alt="TW"
      {...props}
    />
  );
}
