/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagGG(props: {width: string}) {
  const {width, ...restProps} = props;
  return (
    <svg viewBox="0 0 21 15" width={width} {...restProps}>
      <defs>
        <linearGradient id="GGa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="GGb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#F33349" />
          <stop offset="100%" stopColor="#E51D34" />
        </linearGradient>
        <linearGradient id="GGc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FCE24C" />
          <stop offset="100%" stopColor="#F9DC38" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#GGa)" d="M0 0h21v15H0z" />
        <path fill="url(#GGb)" d="M9 6H0v3h9v6h3V9h9V6h-9V0H9v6z" />
        <path
          fill="url(#GGc)"
          d="M10 8v4l-.5 1h2l-.5-1V8h4l1 .5v-2L15 7h-4V3l.5-1h-2l.5 1v4H6l-1-.5v2L6 8h4z"
        />
      </g>
    </svg>
  );
}
