/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagGN(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="GNa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="GNb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#1DBE5E" />
          <stop offset="100%" stopColor="#169E4D" />
        </linearGradient>
        <linearGradient id="GNc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#E72B42" />
          <stop offset="100%" stopColor="#CC162C" />
        </linearGradient>
        <linearGradient id="GNd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFD952" />
          <stop offset="100%" stopColor="#FCD036" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#GNa)" d="M0 0h21v15H0z" />
        <path fill="url(#GNb)" d="M10 0h11v15H10z" />
        <path fill="url(#GNc)" d="M0 0h7v15H0z" />
        <path fill="url(#GNd)" d="M7 0h7v15H7z" />
      </g>
    </svg>
  );
}
