/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagGS(props: {width: string}) {
  return (
    <svg
      xmlnsXlink="http://www.w3.org/1999/xlink"
      viewBox="0 0 21 15"
      width={props.width}
    >
      <defs>
        <linearGradient id="GSa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="GSb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#07319C" />
          <stop offset="100%" stopColor="#00247E" />
        </linearGradient>
        <linearGradient id="GSc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#DB1E36" />
          <stop offset="100%" stopColor="#D51931" />
        </linearGradient>
        <linearGradient id="GSe" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#1E1E1E" />
          <stop offset="100%" />
        </linearGradient>
        <ellipse id="GSd" cx=".5" cy="1.5" rx="1" ry="1.5" />
        <linearGradient id="GSh" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#A2ADB0" />
          <stop offset="100%" stopColor="#8B9497" />
        </linearGradient>
        <ellipse id="GSg" cx=".5" cy="1.5" rx="1" ry="1.5" />
        <linearGradient id="GSi" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#4F4F4F" />
          <stop offset="100%" stopColor="#2B2B2B" />
        </linearGradient>
        <linearGradient id="GSk" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FEC241" />
          <stop offset="100%" stopColor="#FEBB2C" />
        </linearGradient>
        <linearGradient id="GSl" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#A84B14" />
          <stop offset="100%" stopColor="#913F0E" />
        </linearGradient>
        <linearGradient id="GSm" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#CFB063" />
          <stop offset="100%" stopColor="#BEA157" />
        </linearGradient>
        <linearGradient id="GSn" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#2D42FF" />
          <stop offset="100%" stopColor="#0B24FC" />
        </linearGradient>
        <linearGradient id="GSo" x1="0%" x2="100%" y1="0%" y2="50%">
          <stop offset="0%" stopColor="#E3DC3D" />
          <stop offset="100%" stopColor="#CFC82A" />
        </linearGradient>
        <linearGradient id="GSp" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#7F7D7D" />
          <stop offset="100%" stopColor="#656263" />
        </linearGradient>
        <path
          id="GSq"
          d="M.007.506A.489.489 0 0 1 .495 0h2.01c.273 0 .498.23.502.506L3.03 2.25a.52.52 0 0 1-.207.388l-1.095.722a.414.414 0 0 1-.417 0L.24 2.639a.526.526 0 0 1-.21-.388L.007.506z"
        />
        <linearGradient id="GSs" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#0F8012" />
          <stop offset="100%" stopColor="#0B6A0D" />
        </linearGradient>
        <linearGradient id="GSt" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFCF44" />
          <stop offset="100%" stopColor="#FCC72E" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#GSa)" d="M0 0h21v15H0z" />
        <path fill="url(#GSb)" d="M0 0h21v15H0z" />
        <path
          fill="url(#GSa)"
          fillRule="nonzero"
          d="M3 3.23L-1.352-.5H.66L4.16 2h.697L9.5-.902V.25c0 .303-.167.627-.418.806L6 3.257v.513l3.137 2.69c.462.395.204 1.04-.387 1.04-.245 0-.545-.096-.75-.242L4.84 5h-.697L-.5 7.902v-1.66l3.5-2.5V3.23z"
        />
        <path
          fill="url(#GSc)"
          d="M3.5 3L0 0h.5L4 2.5h1L9 0v.25a.537.537 0 0 1-.208.399L5.5 3v1l3.312 2.839c.104.089.072.161-.062.161a.898.898 0 0 1-.458-.149L5 4.5H4L0 7v-.5L3.5 4V3z"
        />
        <path
          fill="url(#GSa)"
          d="M0 2.5v2h3.5v2.505c0 .273.214.495.505.495h.99a.496.496 0 0 0 .505-.495V4.5h3.51a.49.49 0 0 0 .49-.505v-.99a.495.495 0 0 0-.49-.505H5.5V0h-2v2.5H0z"
        />
        <path fill="url(#GSc)" d="M0 3h4V0h1v3h4v1H5v3H4V4H0z" />
        <g transform="translate(18 8)">
          <mask id="GSf" fill="#fff">
            <use xlinkHref="#GSd" />
          </mask>
          <use fill="url(#GSe)" xlinkHref="#GSd" />
          <ellipse cy="2" fill="url(#GSa)" mask="url(#GSf)" rx="1" ry="1.5" />
        </g>
        <g transform="translate(14 8)">
          <mask id="GSj" fill="#fff">
            <use xlinkHref="#GSg" />
          </mask>
          <use fill="url(#GSh)" xlinkHref="#GSg" />
          <ellipse
            cx="1"
            cy="2"
            fill="url(#GSi)"
            mask="url(#GSj)"
            rx="1"
            ry="1.5"
          />
        </g>
        <path
          fill="url(#GSk)"
          d="M16.5 12.5c.828.5 1.5.276 1.5 0s-.672-.5-1.5-.5-1.5.224-1.5.5.672.5 1.5 0z"
        />
        <circle cx="18.5" cy="5.5" r="1" fill="url(#GSa)" />
        <circle cx="16.5" cy="4.5" r="1" fill="url(#GSl)" />
        <ellipse cx="16.5" cy="3.75" fill="url(#GSm)" rx="1" ry="1" />
        <circle cx="16.5" cy="11.5" r="1" fill="url(#GSa)" />
        <circle cx="14.5" cy="5.5" r="1" fill="url(#GSa)" />
        <circle cx="15" cy="6.5" r="1" fill="url(#GSn)" />
        <circle cx="18" cy="6.5" r="1" fill="url(#GSn)" />
        <ellipse cx="19" cy="8" fill="url(#GSo)" rx="1" ry="1" />
        <path
          fill="url(#GSp)"
          d="M16 7.5l-.5.5h2l-.5-.5.5-1.5s-.448-1-1-1-1 1-1 1l.5 1.5z"
        />
        <path
          fill="#5D0543"
          d="M16.5 6.5s.5-.112.5-.38c0-.008-.5-.12-.5-.12s-.5.112-.5.12c0 .268.5.38.5.38z"
        />
        <g transform="translate(15 8)">
          <mask id="GSr" fill="#fff">
            <use xlinkHref="#GSq" />
          </mask>
          <use fill="url(#GSa)" xlinkHref="#GSq" />
          <circle cx="2.5" cy="2.5" r="1" fill="#225DA4" mask="url(#GSr)" />
          <circle cx=".5" cy="1.5" r="1" fill="#225DA4" mask="url(#GSr)" />
          <path fill="url(#GSs)" d="M0 0h3L1.5 3z" mask="url(#GSr)" />
          <ellipse
            cx="1.5"
            cy="1.5"
            fill="url(#GSt)"
            mask="url(#GSr)"
            rx="1"
            ry="1"
          />
        </g>
      </g>
    </svg>
  );
}
