/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagIT(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="ITa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="ITb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#E43D4C" />
          <stop offset="100%" stopColor="#CC2E3C" />
        </linearGradient>
        <linearGradient id="ITc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#1BB65D" />
          <stop offset="100%" stopColor="#139149" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#ITa)" d="M0 0h21v15H0z" />
        <path fill="url(#ITb)" d="M10 0h11v15H10z" />
        <path fill="url(#ITc)" d="M0 0h7v15H0z" />
        <path fill="url(#ITa)" d="M7 0h7v15H7z" />
      </g>
    </svg>
  );
}
