/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagJP(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="JPa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="JPb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#D81441" />
          <stop offset="100%" stopColor="#BB0831" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#JPa)" d="M0 0h21v15H0z" />
        <circle cx="10.5" cy="7.5" r="4.5" fill="url(#JPb)" />
      </g>
    </svg>
  );
}
