/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagLB(props: {width: string}) {
  const {width, ...restProps} = props;
  return (
    <svg viewBox="0 0 21 15" width={width} {...restProps}>
      <defs>
        <linearGradient id="LBa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="LBb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#F03340" />
          <stop offset="100%" stopColor="#EB212E" />
        </linearGradient>
        <linearGradient id="LBc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#1FC065" />
          <stop offset="100%" stopColor="#17A555" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#LBa)" d="M0 0h21v15H0z" />
        <path fill="url(#LBb)" d="M0 0h21v4H0zM0 11h21v4H0z" />
        <path fill="url(#LBa)" d="M0 4h21v7H0z" />
        <path
          fill="url(#LBc)"
          d="M9.65 9.35a.497.497 0 0 0-.003-.703l.206.206a.972.972 0 0 0-.837-.232l-1.032.258c-.267.067-.3-.017-.08-.183l1.191-.892c.224-.168.184-.304-.103-.304h-.484c-.28 0-.309-.1-.064-.222l1.112-.556c.245-.123.223-.222-.064-.222h-.484c-.28 0-.323-.138-.103-.304l1.19-.892a.719.719 0 0 1 .81 0l1.19.892c.224.168.184.304-.103.304h-.484c-.28 0-.309.1-.064.222l1.112.556c.245.123.223.222-.064.222h-.484c-.28 0-.323.138-.103.304l1.19.892c.224.168.191.25-.08.183l-1.03-.258a.977.977 0 0 0-.838.232l.206-.206a.496.496 0 0 0-.003.703l.3.3c.193.193.134.35-.145.35h-2.01c-.273 0-.339-.156-.145-.35l.3-.3z"
        />
      </g>
    </svg>
  );
}
