/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagLU(props: {width: string}) {
  const {width, ...restProps} = props;
  return (
    <svg viewBox="0 0 21 15" width={width} {...restProps}>
      <defs>
        <linearGradient id="LUa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="LUb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#F14455" />
          <stop offset="100%" stopColor="#EB2D3F" />
        </linearGradient>
        <linearGradient id="LUc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#29B4EE" />
          <stop offset="100%" stopColor="#1AA3DC" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#LUa)" d="M0 0h21v15H0z" />
        <path fill="url(#LUb)" d="M0 0h21v5H0z" />
        <path fill="url(#LUc)" d="M0 10h21v5H0z" />
        <path fill="url(#LUa)" d="M0 5h21v5H0z" />
      </g>
    </svg>
  );
}
