/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagMF(props: {width: string}) {
  const {width, ...restProps} = props;
  return (
    <svg viewBox="0 0 21 15" width={width} {...restProps}>
      <defs>
        <linearGradient id="MFa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="MFb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#F44653" />
          <stop offset="100%" stopColor="#EE2A39" />
        </linearGradient>
        <linearGradient id="MFc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#1035BB" />
          <stop offset="100%" stopColor="#042396" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#MFa)" d="M0 0h21v15H0z" />
        <path fill="url(#MFb)" d="M10 0h11v15H10z" />
        <path fill="url(#MFc)" d="M0 0h7v15H0z" />
        <path fill="url(#MFa)" d="M7 0h7v15H7z" />
      </g>
    </svg>
  );
}
