/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagML(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="MLa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="MLb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#E2233A" />
          <stop offset="100%" stopColor="#CC162C" />
        </linearGradient>
        <linearGradient id="MLc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#2ECB4D" />
          <stop offset="100%" stopColor="#24B441" />
        </linearGradient>
        <linearGradient id="MLd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFD749" />
          <stop offset="100%" stopColor="#FCD036" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#MLa)" d="M0 0h21v15H0z" />
        <path fill="url(#MLb)" d="M10 0h11v15H10z" />
        <path fill="url(#MLc)" d="M0 0h7v15H0z" />
        <path fill="url(#MLd)" d="M7 0h7v15H7z" />
      </g>
    </svg>
  );
}
