/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagNA(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="NAa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="NAd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#0C4799" />
          <stop offset="100%" stopColor="#05387E" />
        </linearGradient>
        <path id="NAc" d="M3.121 12.304l21-10h-21z" />
        <filter
          id="NAb"
          width="107.1%"
          height="115%"
          x="-3.6%"
          y="-7.5%"
          filterUnits="objectBoundingBox"
        >
          <feMorphology
            in="SourceAlpha"
            operator="dilate"
            radius=".25"
            result="shadowSpreadOuter1"
          />
          <feOffset in="shadowSpreadOuter1" result="shadowOffsetOuter1" />
          <feColorMatrix
            in="shadowOffsetOuter1"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0"
          />
        </filter>
        <linearGradient id="NAg" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFD243" />
          <stop offset="100%" stopColor="#FFCD2F" />
        </linearGradient>
        <path
          id="NAf"
          d="M6.621 6.804l-.765.848.058-1.14-1.14.057.847-.765-.847-.765 1.14.058-.058-1.14.765.847.766-.848-.058 1.14 1.14-.057-.848.765.848.765-1.14-.058.058 1.14z"
        />
        <filter
          id="NAe"
          width="112.5%"
          height="125%"
          x="-6.2%"
          y="-6.2%"
          filterUnits="objectBoundingBox"
        >
          <feOffset dy=".5" in="SourceAlpha" result="shadowOffsetOuter1" />
          <feColorMatrix
            in="shadowOffsetOuter1"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0"
          />
        </filter>
        <linearGradient id="NAj" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#1BAC55" />
          <stop offset="100%" stopColor="#149447" />
        </linearGradient>
        <path id="NAi" d="M3.121 17.304h21v-10z" />
        <filter
          id="NAh"
          width="107.1%"
          height="115%"
          x="-3.6%"
          y="-7.5%"
          filterUnits="objectBoundingBox"
        >
          <feMorphology
            in="SourceAlpha"
            operator="dilate"
            radius=".25"
            result="shadowSpreadOuter1"
          />
          <feOffset in="shadowSpreadOuter1" result="shadowOffsetOuter1" />
          <feColorMatrix
            in="shadowOffsetOuter1"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0"
          />
        </filter>
        <path id="NAl" d="M5.433 19.304L25.75 6.609 21.81.304 1.493 12.999z" />
        <filter
          id="NAk"
          width="106.2%"
          height="107.9%"
          x="-3.1%"
          y="-3.9%"
          filterUnits="objectBoundingBox"
        >
          <feMorphology
            in="SourceAlpha"
            operator="dilate"
            radius=".25"
            result="shadowSpreadOuter1"
          />
          <feOffset in="shadowSpreadOuter1" result="shadowOffsetOuter1" />
          <feColorMatrix
            in="shadowOffsetOuter1"
            values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.06 0"
          />
        </filter>
        <linearGradient id="NAm" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#E52347" />
          <stop offset="100%" stopColor="#D01739" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#NAa)" d="M0 0h21v15H0z" />
        <g transform="translate(-3.12 -2.3)">
          <use fill="#000" filter="url(#NAb)" xlinkHref="#NAc" />
          <use fill="url(#NAd)" xlinkHref="#NAc" />
        </g>
        <g transform="translate(-3.12 -2.3)">
          <use fill="#000" filter="url(#NAe)" xlinkHref="#NAf" />
          <use fill="url(#NAg)" xlinkHref="#NAf" />
        </g>
        <g transform="translate(-3.12 -2.3)">
          <use fill="#000" filter="url(#NAh)" xlinkHref="#NAi" />
          <use fill="url(#NAj)" xlinkHref="#NAi" />
        </g>
        <g transform="translate(-3.12 -2.3)">
          <use fill="#000" filter="url(#NAk)" xlinkHref="#NAl" />
          <use fill="url(#NAa)" xlinkHref="#NAl" />
        </g>
        <path
          fill="url(#NAm)"
          d="M2.65 19.608L27.243 4.24 24.593 0 0 15.368z"
          transform="translate(-3.12 -2.3)"
        />
      </g>
    </svg>
  );
}
