/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagNF(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="NFa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="NFb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#219646" />
          <stop offset="100%" stopColor="#197837" />
        </linearGradient>
        <linearGradient id="NFc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#259D4B" />
          <stop offset="100%" stopColor="#197837" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#NFa)" d="M0 0h21v15H0z" />
        <path fill="url(#NFb)" d="M10 0h11v15H10zM0 0h7v15H0z" />
        <path fill="url(#NFa)" d="M6 0h9v15H6z" />
        <path
          fill="url(#NFc)"
          d="M9.444 4.003l.422-1.52A.705.705 0 0 1 10.5 2c.276 0 .562.222.634.484l.422 1.52a.5.5 0 1 0 .248.893l.31 1.116a.501.501 0 0 0-.614.487.5.5 0 0 0 .85.358l.325 1.174a.499.499 0 1 0 .217.779L13.5 11H11v2h-1v-2H7.5l.608-2.19a.5.5 0 1 0 .217-.778l.326-1.174A.498.498 0 0 0 9.5 6.5a.5.5 0 0 0-.615-.487l.31-1.116a.5.5 0 1 0 .248-.893z"
        />
      </g>
    </svg>
  );
}
