/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagNR(props: {width: string}) {
  const {width, ...restProps} = props;
  return (
    <svg viewBox="0 0 21 15" width={width} {...restProps}>
      <defs>
        <linearGradient id="NRa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="NRb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#0744A7" />
          <stop offset="100%" stopColor="#00307D" />
        </linearGradient>
        <linearGradient id="NRc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FCC747" />
          <stop offset="100%" stopColor="#FEC539" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#NRa)" d="M0 0h21v15H0z" />
        <path fill="url(#NRb)" d="M0 0h21v15H0z" />
        <path fill="url(#NRc)" d="M0 6h21v2H0z" />
        <path
          fill="url(#NRa)"
          d="M5.5 12.25l-.773 1.128.038-1.367-1.288.458.834-1.083L3 11l1.311-.386-.834-1.083 1.288.458-.038-1.367L5.5 9.75l.773-1.128-.038 1.367 1.288-.458-.834 1.083L8 11l-1.311.386.834 1.083-1.288-.458.038 1.367z"
        />
      </g>
    </svg>
  );
}
