/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagPT(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="PTa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="PTb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FF2936" />
          <stop offset="100%" stopColor="#FD0D1B" />
        </linearGradient>
        <linearGradient id="PTc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#128415" />
          <stop offset="100%" stopColor="#0A650C" />
        </linearGradient>
        <linearGradient id="PTd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FAF94F" />
          <stop offset="100%" stopColor="#F8F736" />
        </linearGradient>
        <linearGradient id="PTe" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#1D50B5" />
          <stop offset="100%" stopColor="#15439D" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#PTa)" d="M0 0h21v15H0z" />
        <path fill="url(#PTb)" d="M0 0h21v15H0z" />
        <path fill="url(#PTc)" d="M0 0h8v15H0z" />
        <path
          fill="url(#PTd)"
          fillRule="nonzero"
          d="M8 9.5a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm0 1a3 3 0 1 1 0-6 3 3 0 0 1 0 6z"
        />
        <path
          fill="url(#PTa)"
          d="M7 6.256A.25.25 0 0 1 7.245 6h1.51A.25.25 0 0 1 9 6.256V8A.997.997 0 0 1 8 9c-.552 0-1-.443-1-.999V6.256z"
        />
        <path
          fill="url(#PTe)"
          d="M8 8c.276 0 .5-.724.5-1a.5.5 0 0 0-1 0c0 .276.224 1 .5 1z"
        />
      </g>
    </svg>
  );
}
