/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagSG(props: {width: string}) {
  const {width, ...restProps} = props;
  return (
    <svg viewBox="0 0 21 15" width={width} {...restProps}>
      <defs>
        <linearGradient id="SGa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="SGb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#E12237" />
          <stop offset="100%" stopColor="#CE1126" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#SGa)" d="M0 0h21v15H0z" />
        <path fill="url(#SGb)" d="M0 0h21v8H0z" />
        <path
          fill="url(#SGa)"
          d="M0 8h21v7H0zM6.874 1.657a2.5 2.5 0 1 0 0 4.686 3 3 0 1 1 0-4.686zM5.5 4a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm1 2a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm2 0a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm1-2a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm-2-1.5a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1z"
        />
      </g>
    </svg>
  );
}
