/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagSJ(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="SJa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="SJb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#F14247" />
          <stop offset="100%" stopColor="#ED2F35" />
        </linearGradient>
        <linearGradient id="SJc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#0A3A85" />
          <stop offset="100%" stopColor="#032A67" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#SJa)" d="M0 0h21v15H0z" />
        <path fill="url(#SJb)" d="M0 0h21v15H0z" />
        <path fill="url(#SJa)" d="M0 9h6v6h3V9h12V6H9V0H6v6H0z" />
        <path fill="url(#SJc)" d="M0 8h7v7h1V8h13V7H8V0H7v7H0z" />
      </g>
    </svg>
  );
}
