/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagSM(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="SMa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="SMb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#7CCCF5" />
          <stop offset="100%" stopColor="#62B7E3" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#SMa)" d="M0 0h21v15H0z" />
        <path fill="url(#SMb)" d="M0 7h21v8H0z" />
        <path fill="url(#SMa)" d="M0 0h21v7H0z" />
        <path
          fill="#445F42"
          fillRule="nonzero"
          d="M8 7c0 .901.482 1.72 1.247 2.164a.5.5 0 0 0 .502-.865A1.499 1.499 0 0 1 9 7a.5.5 0 0 0-1 0zm3.846 2.107A2.498 2.498 0 0 0 13 7a.5.5 0 1 0-1 0c0 .518-.264.99-.693 1.265a.5.5 0 1 0 .539.842z"
        />
        <ellipse cx="10.5" cy="6.5" fill="#D89F3D" rx="1" ry="1.5" />
      </g>
    </svg>
  );
}
