/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagSX(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="SXa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="SXb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#0740AA" />
          <stop offset="100%" stopColor="#012F85" />
        </linearGradient>
        <linearGradient id="SXc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#F02C33" />
          <stop offset="100%" stopColor="#D82027" />
        </linearGradient>
        <linearGradient id="SXd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#E72C33" />
          <stop offset="100%" stopColor="#D82027" />
        </linearGradient>
        <linearGradient id="SXe" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#78C1F0" />
          <stop offset="100%" stopColor="#67B1E0" />
        </linearGradient>
        <linearGradient id="SXf" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#F7E14B" />
          <stop offset="100%" stopColor="#F7DF3E" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#SXa)" d="M0 0h21v15H0z" />
        <path fill="url(#SXb)" d="M0 7h21v8H0z" />
        <path fill="url(#SXc)" d="M0 0h21v7H0z" />
        <path fill="url(#SXa)" d="M0 0l10 7.5L0 15z" />
        <path
          fill="url(#SXd)"
          fillRule="nonzero"
          d="M1.5 7V5.506A.997.997 0 0 1 2.495 4.5h2.01c.55 0 .995.457.995 1.006V7c0 .845-.384 1.447-1.003 1.798a2.304 2.304 0 0 1-1.03.3 2.312 2.312 0 0 1-.964-.3C1.884 8.447 1.5 7.845 1.5 7z"
        />
        <path
          fill="url(#SXe)"
          d="M2 7V5.506c0-.28.216-.506.495-.506h2.01c.273 0 .495.232.495.506V7c0 1.5-1.5 1.6-1.5 1.6S2 8.5 2 7z"
        />
        <path fill="#FFF" d="M3 6.5l.5-.5.5.5v1H3z" />
        <path
          fill="#F9D835"
          fillRule="nonzero"
          d="M1.001 9.368A3.389 3.389 0 0 0 3.5 10.5c.948 0 1.915-.448 2.521-1.162a.5.5 0 0 0-.762-.647A2.395 2.395 0 0 1 3.5 9.5a2.39 2.39 0 0 1-1.743-.787.5.5 0 1 0-.756.655z"
        />
        <circle cx="3.5" cy="4.5" r="1" fill="url(#SXf)" />
      </g>
    </svg>
  );
}
