/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagTK(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="TKa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="TKb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#0637C5" />
          <stop offset="100%" stopColor="#002CAA" />
        </linearGradient>
        <linearGradient id="TKc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FDD33F" />
          <stop offset="100%" stopColor="#FED02F" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#TKa)" d="M0 0h21v15H0z" />
        <path fill="url(#TKb)" d="M0 0h21v15H0z" />
        <path
          fill="url(#TKc)"
          d="M4 12h15v1H3l1-1zm7.5-6c3-2 6.5-4 6.5-4s-1.643 3.073-1.5 4.5C16.69 8.407 19 11 19 11H5s3.5-3 6.5-5z"
        />
        <path
          fill="#FFF"
          d="M4 9l-.707.207L3.5 8.5l-.207-.707L4 8l.707-.207L4.5 8.5l.207.707zM5 2.5l-.707.207L4.5 2l-.207-.707L5 1.5l.707-.207L5.5 2l.207.707zM7 5.5l-.707.207L6.5 5l-.207-.707L7 4.5l.707-.207L7.5 5l.207.707zM2 5.5l-.707.207L1.5 5l-.207-.707L2 4.5l.707-.207L2.5 5l.207.707z"
        />
      </g>
    </svg>
  );
}
