/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagTO(props: {width: string}) {
  return (
    <svg viewBox="0 0 21 15" width={props.width}>
      <defs>
        <linearGradient id="TOa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="TOb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#E20F1B" />
          <stop offset="100%" stopColor="#C00711" />
        </linearGradient>
        <linearGradient id="TOc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#DF101B" />
          <stop offset="100%" stopColor="#C00711" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#TOa)" d="M0 0h21v15H0z" />
        <path fill="url(#TOb)" d="M0 0h21v15H0z" />
        <path fill="url(#TOa)" d="M0 0h12v8H0z" />
        <path
          fill="url(#TOc)"
          d="M7 3V1.258C7 1.104 6.89 1 6.755 1h-1.51A.25.25 0 0 0 5 1.258V3H3.258C3.104 3 3 3.11 3 3.245v1.51A.25.25 0 0 0 3.258 5H5v1.742c0 .154.11.258.245.258h1.51A.25.25 0 0 0 7 6.742V5h1.742C8.896 5 9 4.89 9 4.755v-1.51A.25.25 0 0 0 8.742 3H7z"
        />
      </g>
    </svg>
  );
}
