/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagVC(props: {width: string}) {
  const {width, ...restProps} = props;
  return (
    <svg viewBox="0 0 21 15" width={width} {...restProps}>
      <defs>
        <linearGradient id="VCa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="VCb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#08C47A" />
          <stop offset="100%" stopColor="#009F60" />
        </linearGradient>
        <linearGradient id="VCc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#0C87E1" />
          <stop offset="100%" stopColor="#0073C7" />
        </linearGradient>
        <linearGradient id="VCd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFD147" />
          <stop offset="100%" stopColor="#FECA2F" />
        </linearGradient>
        <linearGradient id="VCe" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#00C778" />
          <stop offset="100%" stopColor="#009F60" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#VCa)" d="M0 0h21v15H0z" />
        <path fill="url(#VCb)" d="M10 0h11v15H10z" />
        <path fill="url(#VCc)" d="M0 0h7v15H0z" />
        <path fill="url(#VCd)" d="M6 0h9v15H6z" />
        <path
          fill="url(#VCe)"
          d="M11 6l1.5-3L14 6l-1.5 3L11 6zM7 6l1.5-3L10 6 8.5 9 7 6zm2 4l1.5-3 1.5 3-1.5 3L9 10z"
        />
      </g>
    </svg>
  );
}
