/*
Copyright (c) 2018-2019 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-FLAG-COMPONENT
// DO NOT EDIT THIS FILE DIRECTLY

import * as React from 'react';

export default function FlagVE(props: {width: string}) {
  const {width, ...restProps} = props;
  return (
    <svg viewBox="0 0 21 15" width={width} {...restProps}>
      <defs>
        <linearGradient id="VEa" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFF" />
          <stop offset="100%" stopColor="#F0F0F0" />
        </linearGradient>
        <linearGradient id="VEb" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#063191" />
          <stop offset="100%" stopColor="#03287C" />
        </linearGradient>
        <linearGradient id="VEc" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#E2213B" />
          <stop offset="100%" stopColor="#CD1931" />
        </linearGradient>
        <linearGradient id="VEd" x1="50%" x2="50%" y1="0%" y2="100%">
          <stop offset="0%" stopColor="#FFD044" />
          <stop offset="100%" stopColor="#FFCB2F" />
        </linearGradient>
      </defs>
      <g fill="none" fillRule="evenodd">
        <path fill="url(#VEa)" d="M0 0h21v15H0z" />
        <path fill="url(#VEb)" d="M0 5h21v5H0z" />
        <path fill="url(#VEc)" d="M0 10h21v5H0z" />
        <path
          fill="url(#VEa)"
          d="M10.5 7a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm-2 .5a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm4 0a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zM7.5 9a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1zm6 0a.5.5 0 1 1 0-1 .5.5 0 0 1 0 1z"
        />
        <path fill="url(#VEd)" d="M0 0h21v5H0z" />
      </g>
    </svg>
  );
}
