// flow-typed signature: 9e46bbf66937a8e2d1b741601b4768e5
// flow-typed version: <<STUB>>/extract-react-types-loader_v^1.0.1/flow_v0.98.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-react-types-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-react-types-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'extract-react-types-loader/index' {
  declare module.exports: $Exports<'extract-react-types-loader'>;
}
declare module 'extract-react-types-loader/index.js' {
  declare module.exports: $Exports<'extract-react-types-loader'>;
}
