/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import Icon from './icon.js';
import type {IconPropsT} from './types.js';

export default function Alert(props: IconPropsT) {
  return (
    <Icon title="Alert" viewBox="0 0 24 24" {...props}>
      <g
        transform="matrix(
        1 0
        0 1
        1 2.5
      )"
      >
        <path
          fillRule="nonzero"
          clipRule="nonzero"
          d="M 11 0 L 0 19.5 L 22 19.5 L 11 0 Z M 9.5 6.5 L 12.5 6.5 L 12.5 11.5 L 9.5 11.5 L 9.5 6.5 Z M 11 17.5 C 9.899999618530273 17.5 9 16.600000381469727 9 15.5 C 9 14.399999618530273 9.899999618530273 13.5 11 13.5 C 12.100000381469727 13.5 13 14.399999618530273 13 15.5 C 13 16.600000381469727 12.100000381469727 17.5 11 17.5 Z"
          fill="currentColor"
        />
      </g>
    </Icon>
  );
}
