/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import Icon from './icon.js';
import type {IconPropsT} from './types.js';

export default function ArrowLeft(props: IconPropsT) {
  return (
    <Icon title="Arrow Left" viewBox="0 0 24 24" {...props}>
      <g
        transform="matrix(
        1 0
        0 1
        1.800048828125 3
      )"
      >
        <path
          fillRule="nonzero"
          clipRule="nonzero"
          d="M 20.199996948242188 10.5 L 4.5 10.5 L 10 18 L 6.5 18 L 0 9 L 6.5 0 L 10 0 L 4.5 7.5 L 20.199996948242188 7.5 L 20.199996948242188 10.5 Z"
          fill="currentColor"
        />
      </g>
    </Icon>
  );
}
