/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import Icon from './icon.js';
import type {IconPropsT} from './types.js';

export default function ArrowUp(props: IconPropsT) {
  return (
    <Icon title="Arrow Up" viewBox="0 0 24 24" {...props}>
      <g
        transform="matrix(
        1 0
        0 1
        3 1.79998779296875
      )"
      >
        <path
          fillRule="nonzero"
          clipRule="nonzero"
          d="M 18 6.5 L 18 10 L 10.5 4.5 L 10.5 20.20001220703125 L 7.5 20.20001220703125 L 7.5 4.5 L 0 10 L 0 6.5 L 9 0 L 18 6.5 Z"
          fill="currentColor"
        />
      </g>
    </Icon>
  );
}
