/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import Icon from './icon';
import type {IconPropsT} from './types';

export default function ArrowDown(props: IconPropsT) {
  return (
    <Icon title="Arrow Down" viewBox="0 0 24 24" {...props}>
      <g
        transform="matrix(
    1 0
    0 1
    3 2
  )"
      >
        <path
          fillRule="nonzero"
          clipRule="nonzero"
          d="M 18 10.20001220703125 L 18 13.600006103515625 L 9 20.20001220703125 L 0 13.600006103515625 L 0 10.20001220703125 L 7.5 15.70001220703125 L 7.5 0 L 10.5 0 L 10.5 15.70001220703125 L 18 10.20001220703125 Z"
          fill="currentColor"
        />
      </g>
    </Icon>
  );
}
