/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import {useStyletron} from '../styles/index.js';
import {mergeOverrideResources} from '../helpers/override.js';

import Icon from './icon.js';
import omitDollarPrefixedKeys from './omit-dollar-prefixed-keys.js';
import type {IconPropsT, StyledComponentArgsT} from './types.js';

export default function Blank(props: IconPropsT) {
  const [, theme] = useStyletron();
  const {overrides = {}, svgRef, ...restProps} = props;
  const SvgOverride = mergeOverrideResources<StyledComponentArgsT>(
    // Icons from theme really targets the SVG override in the underlying Icon component, but
    // have props typed with IconPropsT. Provided the missing props inline below here.
    // $FlowFixMe
    {
      component: theme.icons && theme.icons.Blank ? theme.icons.Blank : null,
      props: {
        title: 'Blank',
        viewBox: '0 0 24 24',
        ...omitDollarPrefixedKeys(restProps),
      },
    },
    overrides && overrides.Svg ? overrides.Svg : {},
  );
  return (
    <Icon
      title="Blank"
      viewBox="0 0 24 24"
      overrides={{Svg: SvgOverride}}
      ref={svgRef}
      {...restProps}
    ></Icon>
  );
}
