/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import Icon from './icon.js';
import type {IconPropsT} from './types.js';

export default function ChevronRight(props: IconPropsT) {
  return (
    <Icon title="Chevron Right" viewBox="0 0 24 24" {...props}>
      <g
        transform="matrix(
    1 0
    0 1
    6.89990234375 2
  )"
      >
        <path
          fillRule="nonzero"
          clipRule="nonzero"
          d="M 11.5 10 L 3.800018310546875 20 L 0 20 L 7.70001220703125 10 L 0 0 L 3.800018310546875 0 L 11.5 10 Z"
          fill="currentColor"
        />
      </g>
    </Icon>
  );
}
