/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import Icon from './icon.js';
import type {IconPropsT} from './types.js';

export default function DeleteAlt(props: IconPropsT) {
  return (
    <Icon title="Delete Alt" viewBox="0 0 24 24" {...props}>
      <g
        transform="matrix(
        1 0
        0 1
        1 1
      )"
      >
        <path
          fillRule="nonzero"
          clipRule="nonzero"
          d="M 11 0 C 4.900000095367432 0 0 4.900000095367432 0 11 C 0 17.100000381469727 4.900000095367432 22 11 22 C 17.100000381469727 22 22 17.100000381469727 22 11 C 22 4.900000095367432 17.100000381469727 0 11 0 Z M 17 15 L 15 17 L 11 13 L 7 17 L 5 15 L 9 11 L 5 7 L 7 5 L 11 9 L 15 5 L 17 7 L 13 11 L 17 15 Z"
          fill="currentColor"
        />
      </g>
    </Icon>
  );
}
