/*
Copyright (c) 2018 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow
// BASEUI-GENERATED-REACT-ICON
// DO NOT EDIT THIS FILE DIRECTLY, SEE README.md
import * as React from 'react';
import Icon from './icon.js';
import type {IconPropsT} from './types.js';

export default function Upload(props: IconPropsT) {
  return (
    <Icon title="Upload" viewBox="0 0 24 24" {...props}>
      <g
        transform="matrix(
    1 0
    0 1
    1 3
  )"
      >
        <path
          fillRule="nonzero"
          clipRule="nonzero"
          d="M 17 4.0999755859375 C 16 1.6999754905700684 13.699999809265137 0 11 0 C 8.300000190734863 0 5.900000095367432 1.6999754905700684 5 4.0999755859375 C 2.200000047683716 4.5999755859375 0 7 0 10 C 0 13.100000381469727 2.4000000953674316 15.699999809265137 5.5 16 L 9.5 16 L 9.5 9.199951171875 L 6 11.5 L 6 8.0999755859375 L 11 4.800048828125 L 16 8.0999755859375 L 16 11.5 L 12.5 9.199951171875 L 12.5 16 L 16.5 16 C 19.600000381469727 15.699999809265137 22 13.199999809265137 22 10 C 22 7 19.899999618530273 4.5999755859375 17 4.0999755859375 Z"
          fill="currentColor"
        />
      </g>
    </Icon>
  );
}
