/*
Copyright (c) Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
import * as stylex from '@stylexjs/stylex';
import { semanticColors } from './colors.stylex';

/**
 * Light Theme
 * Default theme using light mode values
 */
export const lightTheme = stylex.createTheme(semanticColors, {
  // Background
  backgroundPrimary: '#FFFFFF',
  backgroundSecondary: '#F3F3F3',
  backgroundTertiary: '#E8E8E8',
  backgroundInversePrimary: '#000000',
  backgroundInverseSecondary: '#282828',
  backgroundStateDisabled: '#F3F3F3',
  backgroundOverlay: 'rgba(0, 0, 0, 0.5)',
  backgroundOverlayArt: 'rgba(0, 0, 0, 0.0)',
  backgroundAccent: '#276EF1',
  backgroundNegative: '#DE1135',
  backgroundWarning: '#F6BC2F',
  backgroundPositive: '#0E8345',
  backgroundAccentLight: '#EFF4FE',
  backgroundNegativeLight: '#FFF0EE',
  backgroundWarningLight: '#FDF2DC',
  backgroundPositiveLight: '#EAF6ED',
  backgroundAlwaysDark: '#000000',
  backgroundAlwaysLight: '#FFFFFF',

  // Content
  contentPrimary: '#000000',
  contentSecondary: '#4B4B4B',
  contentTertiary: '#5E5E5E',
  contentInversePrimary: '#FFFFFF',
  contentInverseSecondary: '#DDDDDD',
  contentInverseTertiary: '#A6A6A6',
  contentStateDisabled: '#A6A6A6',
  contentOnColor: '#FFFFFF',
  contentOnColorInverse: '#000000',
  contentAccent: '#276EF1',
  contentNegative: '#DE1135',
  contentWarning: '#9F6402',
  contentPositive: '#0E8345',

  // Border
  borderOpaque: '#F3F3F3',
  borderTransparent: 'rgba(0, 0, 0, 0.08)',
  borderSelected: '#000000',
  borderInverseOpaque: '#4B4B4B',
  borderInverseTransparent: 'rgba(255, 255, 255, 0.2)',
  borderInverseSelected: '#FFFFFF',
  borderStateDisabled: '#F3F3F3',
  borderAccent: '#276EF1',
  borderAccentLight: '#A9C9FF',
  borderNegative: '#DE1135',
  borderNegativeLight: '#FFB2AB',
  borderWarning: '#9F6402',
  borderWarningLight: '#FFD688',
  borderPositive: '#0E8345',
  borderPositiveLight: '#7FD99A',

  // Brand
  brandBackgroundPrimary: '#276EF1',
  brandBackgroundSecondary: '#EFF4FE',
  brandBackgroundTertiary: '#FFFFFF',
  brandBackgroundDisabled: '#EFF4FE',
  brandContentPrimary: '#276EF1',
  brandContentOnPrimary: '#FFFFFF',
  brandContentOnSecondary: '#175BCC',
  brandContentOnTertiary: '#000000',
  brandContentOnGradient: '#FFFFFF',
  brandContentDisabled: '#A9C9FF',
  brandBorderAccessible: '#276EF1',
  brandBorderSubtle: '#DEE9FE',

  // Programs
  safety: '#276EF1',
  eatsGreen400: '#0E8345',
  freightBlue400: '#0E1FC1',
  rewardsTier1: '#276EF1',
  rewardsTier2: '#F6BC2F',
  rewardsTier3: '#8EA3AD',
  rewardsTier4: '#000000',
  membership: '#9F6402',

  // Hover/Press overlays
  hoverOverlayInverseAlpha: 'rgba(255, 255, 255, 0.1)',
  hoverOverlayAlpha: 'rgba(0, 0, 0, 0.04)',
  hoverNegativeAlpha: 'rgba(222, 17, 53, 0.1)',
  pressedOverlayAlpha: 'rgba(0, 0, 0, 0.08)',
  pressedOverlayInverseAlpha: 'rgba(255, 255, 255, 0.2)',
  pressedNegativeAlpha: 'rgba(222, 17, 53, 0.15)',

  // Tag tokens
  tagRedContentSecondary: '#BB032A',
  tagRedBorderSecondarySelected: '#BB032A',
  tagGrayBackgroundPrimary: '#727272',
  tagGrayBackgroundSecondary: '#F3F3F3',
  tagGrayContentPrimary: '#FFFFFF',
  tagGrayContentSecondary: '#5E5E5E',
  tagGrayBackgroundStateDisabled: '#F3F3F3',
  tagGrayContentStateDisabled: '#C6C6C6',
  tagGrayBorderPrimaryUnselected: '#5E5E5E',
  tagGrayBorderSecondaryUnselected: '#E8E8E8',
  tagGrayBorderSecondarySelected: '#727272',
  tagRedBackgroundPrimary: '#DE1135',
  tagRedBackgroundSecondary: '#FFF0EE',
  tagRedContentPrimary: '#FFFFFF',
  tagRedBackgroundStateDisabled: '#FFF0EE',
  tagRedContentStateDisabled: '#FFB2AB',
  tagRedBorderPrimaryUnselected: '#BB032A',
  tagRedBorderSecondaryUnselected: '#FFE1DE',
  tagOrangeBackgroundPrimary: '#C54600',
  tagOrangeBackgroundSecondary: '#FFF0E9',
  tagOrangeContentPrimary: '#FFFFFF',
  tagOrangeContentSecondary: '#A33B04',
  tagOrangeBackgroundStateDisabled: '#FFF0E9',
  tagOrangeContentStateDisabled: '#FFB48C',
  tagYellowBackgroundPrimary: '#F6BC2F',
  tagOrangeBorderPrimaryUnselected: '#A33B04',
  tagYellowBackgroundSecondary: '#FDF2DC',
  tagOrangeBorderSecondaryUnselected: '#FEE2D4',
  tagOrangeBorderSecondarySelected: '#A33B04',
  tagYellowContentPrimary: '#000000',
  tagYellowContentSecondary: '#845201',
  tagYellowBackgroundStateDisabled: '#FDF2DC',
  tagYellowContentStateDisabled: '#FFD688',
  tagYellowBorderPrimaryUnselected: '#D79900',
  tagYellowBorderSecondaryUnselected: '#FBE5B6',
  tagYellowBorderSecondarySelected: '#845201',
  tagGreenBackgroundPrimary: '#0E8345',
  tagGreenBackgroundSecondary: '#EAF6ED',
  tagGreenContentPrimary: '#FFFFFF',
  tagGreenContentSecondary: '#166C3B',
  tagGreenBackgroundStateDisabled: '#EAF6ED',
  tagGreenContentStateDisabled: '#7FD99A',
  tagGreenBorderPrimaryUnselected: '#166C3B',
  tagBlueBackgroundPrimary: '#276EF1',
  tagBlueBackgroundSecondary: '#EFF4FE',
  tagGreenBorderSecondaryUnselected: '#D3EFDA',
  tagBlueContentPrimary: '#FFFFFF',
  tagGreenBorderSecondarySelected: '#166C3B',
  tagBlueContentSecondary: '#175BCC',
  tagBlueBackgroundStateDisabled: '#EFF4FE',
  tagBlueContentStateDisabled: '#A9C9FF',
  tagBlueBorderPrimaryUnselected: '#175BCC',
  tagPurpleBackgroundPrimary: '#944DE7',
  tagPurpleBackgroundSecondary: '#F9F1FF',
  tagBlueBorderSecondaryUnselected: '#DEE9FE',
  tagBlueBorderSecondarySelected: '#175BCC',
  tagPurpleContentPrimary: '#FFFFFF',
  tagPurpleContentSecondary: '#7C3EC3',
  tagPurpleBackgroundStateDisabled: '#F9F1FF',
  tagPurpleContentStateDisabled: '#DDB9FF',
  tagPurpleBorderPrimaryUnselected: '#7C3EC3',
  tagMagentaBackgroundPrimary: '#CA26A5',
  tagPurpleBorderSecondaryUnselected: '#F2E3FF',
  tagMagentaBackgroundSecondary: '#FEEFF9',
  tagPurpleBorderSecondarySelected: '#7C3EC3',
  tagMagentaContentPrimary: '#FFFFFF',
  tagMagentaContentSecondary: '#A91A90',
  tagMagentaBackgroundStateDisabled: '#FEEFF9',
  tagMagentaContentStateDisabled: '#FFACE5',
  tagMagentaBorderPrimaryUnselected: '#A91A90',
  tagMagentaBorderSecondaryUnselected: '#FEDFF3',
  tagMagentaBorderSecondarySelected: '#A91A90',
  tagTealBackgroundPrimary: '#007F8C',
  tagTealBackgroundSecondary: '#E2F8FB',
  tagTealContentPrimary: '#FFFFFF',
  tagTealContentSecondary: '#016974',
  tagTealBackgroundStateDisabled: '#E2F8FB',
  tagTealContentStateDisabled: '#77D5E3',
  tagTealBorderPrimaryUnselected: '#016974',
  tagTealBorderSecondaryUnselected: '#CDEEF3',
  tagTealBorderSecondarySelected: '#016974',
  tagLimeBackgroundPrimary: '#4F7F06',
  tagLimeBackgroundSecondary: '#EEF6E3',
  tagLimeContentPrimary: '#FFFFFF',
  tagLimeContentSecondary: '#3F6900',
  tagLimeBackgroundStateDisabled: '#EEF6E3',
  tagLimeContentStateDisabled: '#A6D467',
  tagLimeBorderPrimaryUnselected: '#3F6900',
  tagLimeBorderSecondaryUnselected: '#DEEEC6',
  tagLimeBorderSecondarySelected: '#3F6900',

  // Deprecated tokens (for backward compatibility)
  jumpRed400: '#FC7F79',
  backgroundOverlayLight: 'rgba(0, 0, 0, 0.5)',
  backgroundOverlayDark: 'rgba(0, 0, 0, 0.5)',
  backgroundLightAccent: '#EFF4FE',
  backgroundLightPositive: '#EAF6ED',
  backgroundLightWarning: '#FDF2DC',
  backgroundLightNegative: '#FFF0EE',
});

/**
 * Dark Theme
 * Dark mode values
 */
export const darkTheme = stylex.createTheme(semanticColors, {
  // Background
  backgroundPrimary: '#000000',
  backgroundSecondary: '#161616',
  backgroundTertiary: '#1F1F1F',
  backgroundInversePrimary: '#FFFFFF',
  backgroundInverseSecondary: '#E8E8E8',
  backgroundStateDisabled: '#161616',
  backgroundOverlay: 'rgba(0, 0, 0, 0.7)',
  backgroundOverlayArt: 'rgba(0, 0, 0, 0.16)',
  backgroundAccent: '#276EF1',
  backgroundNegative: '#DE1135',
  backgroundWarning: '#F6BC2F',
  backgroundPositive: '#0E8345',
  backgroundAccentLight: '#002661',
  backgroundNegativeLight: '#520810',
  backgroundWarningLight: '#392300',
  backgroundPositiveLight: '#002F14',
  backgroundAlwaysDark: '#000000',
  backgroundAlwaysLight: '#FFFFFF',

  // Content
  contentPrimary: '#FFFFFF',
  contentSecondary: '#C6C6C6',
  contentTertiary: '#A6A6A6',
  contentInversePrimary: '#000000',
  contentInverseSecondary: '#2E2E2E',
  contentInverseTertiary: '#545454',
  contentStateDisabled: '#727272',
  contentOnColor: '#FFFFFF',
  contentOnColorInverse: '#000000',
  contentAccent: '#6DAAFB',
  contentNegative: '#FC7F79',
  contentWarning: '#FFC043',
  contentPositive: '#66D19E',

  // Border
  borderOpaque: '#161616',
  borderTransparent: 'rgba(255, 255, 255, 0.08)',
  borderSelected: '#FFFFFF',
  borderInverseOpaque: '#C6C6C6',
  borderInverseTransparent: 'rgba(0, 0, 0, 0.2)',
  borderInverseSelected: '#000000',
  borderStateDisabled: '#161616',
  borderAccent: '#6DAAFB',
  borderAccentLight: '#1948A3',
  borderNegative: '#FC7F79',
  borderNegativeLight: '#950F22',
  borderWarning: '#FFC043',
  borderWarningLight: '#6B4100',
  borderPositive: '#66D19E',
  borderPositiveLight: '#0D572D',

  // Brand
  brandBackgroundPrimary: '#276EF1',
  brandBackgroundSecondary: '#002661',
  brandBackgroundTertiary: '#000000',
  brandBackgroundDisabled: '#002661',
  brandContentPrimary: '#6DAAFB',
  brandContentOnPrimary: '#FFFFFF',
  brandContentOnSecondary: '#A9C9FF',
  brandContentOnTertiary: '#FFFFFF',
  brandContentOnGradient: '#FFFFFF',
  brandContentDisabled: '#1948A3',
  brandBorderAccessible: '#6DAAFB',
  brandBorderSubtle: '#1948A3',

  // Programs
  safety: '#6DAAFB',
  eatsGreen400: '#66D19E',
  freightBlue400: '#535FCF',
  rewardsTier1: '#6DAAFB',
  rewardsTier2: '#F6BC2F',
  rewardsTier3: '#8EA3AD',
  rewardsTier4: '#FFFFFF',
  membership: '#FFC043',

  // Hover/Press overlays
  hoverOverlayInverseAlpha: 'rgba(0, 0, 0, 0.1)',
  hoverOverlayAlpha: 'rgba(255, 255, 255, 0.04)',
  hoverNegativeAlpha: 'rgba(252, 127, 121, 0.1)',
  pressedOverlayAlpha: 'rgba(255, 255, 255, 0.08)',
  pressedOverlayInverseAlpha: 'rgba(0, 0, 0, 0.2)',
  pressedNegativeAlpha: 'rgba(252, 127, 121, 0.15)',

  // Tag tokens (dark theme versions)
  tagRedContentSecondary: '#FC7F79',
  tagRedBorderSecondarySelected: '#FC7F79',
  tagGrayBackgroundPrimary: '#A6A6A6',
  tagGrayBackgroundSecondary: '#161616',
  tagGrayContentPrimary: '#000000',
  tagGrayContentSecondary: '#C6C6C6',
  tagGrayBackgroundStateDisabled: '#161616',
  tagGrayContentStateDisabled: '#545454',
  tagGrayBorderPrimaryUnselected: '#C6C6C6',
  tagGrayBorderSecondaryUnselected: '#1F1F1F',
  tagGrayBorderSecondarySelected: '#A6A6A6',
  tagRedBackgroundPrimary: '#DE1135',
  tagRedBackgroundSecondary: '#520810',
  tagRedContentPrimary: '#FFFFFF',
  tagRedBackgroundStateDisabled: '#520810',
  tagRedContentStateDisabled: '#950F22',
  tagRedBorderPrimaryUnselected: '#FC7F79',
  tagRedBorderSecondaryUnselected: '#950F22',
  tagOrangeBackgroundPrimary: '#C54600',
  tagOrangeBackgroundSecondary: '#461A00',
  tagOrangeContentPrimary: '#FFFFFF',
  tagOrangeContentSecondary: '#FFB48C',
  tagOrangeBackgroundStateDisabled: '#461A00',
  tagOrangeContentStateDisabled: '#823006',
  tagYellowBackgroundPrimary: '#F6BC2F',
  tagOrangeBorderPrimaryUnselected: '#FFB48C',
  tagYellowBackgroundSecondary: '#392300',
  tagOrangeBorderSecondaryUnselected: '#823006',
  tagOrangeBorderSecondarySelected: '#FFB48C',
  tagYellowContentPrimary: '#000000',
  tagYellowContentSecondary: '#FFD688',
  tagYellowBackgroundStateDisabled: '#392300',
  tagYellowContentStateDisabled: '#6B4100',
  tagYellowBorderPrimaryUnselected: '#FFD688',
  tagYellowBorderSecondaryUnselected: '#6B4100',
  tagYellowBorderSecondarySelected: '#FFD688',
  tagGreenBackgroundPrimary: '#0E8345',
  tagGreenBackgroundSecondary: '#002F14',
  tagGreenContentPrimary: '#FFFFFF',
  tagGreenContentSecondary: '#66D19E',
  tagGreenBackgroundStateDisabled: '#002F14',
  tagGreenContentStateDisabled: '#0D572D',
  tagGreenBorderPrimaryUnselected: '#66D19E',
  tagBlueBackgroundPrimary: '#276EF1',
  tagBlueBackgroundSecondary: '#002661',
  tagGreenBorderSecondaryUnselected: '#0D572D',
  tagBlueContentPrimary: '#FFFFFF',
  tagGreenBorderSecondarySelected: '#66D19E',
  tagBlueContentSecondary: '#A9C9FF',
  tagBlueBackgroundStateDisabled: '#002661',
  tagBlueContentStateDisabled: '#1948A3',
  tagBlueBorderPrimaryUnselected: '#A9C9FF',
  tagPurpleBackgroundPrimary: '#944DE7',
  tagPurpleBackgroundSecondary: '#3A1659',
  tagBlueBorderSecondaryUnselected: '#1948A3',
  tagBlueBorderSecondarySelected: '#A9C9FF',
  tagPurpleContentPrimary: '#FFFFFF',
  tagPurpleContentSecondary: '#DDB9FF',
  tagPurpleBackgroundStateDisabled: '#3A1659',
  tagPurpleContentStateDisabled: '#633495',
  tagPurpleBorderPrimaryUnselected: '#DDB9FF',
  tagMagentaBackgroundPrimary: '#CA26A5',
  tagPurpleBorderSecondaryUnselected: '#633495',
  tagMagentaBackgroundSecondary: '#50003F',
  tagPurpleBorderSecondarySelected: '#DDB9FF',
  tagMagentaContentPrimary: '#FFFFFF',
  tagMagentaContentSecondary: '#FFACE5',
  tagMagentaBackgroundStateDisabled: '#50003F',
  tagMagentaContentStateDisabled: '#891869',
  tagMagentaBorderPrimaryUnselected: '#FFACE5',
  tagMagentaBorderSecondaryUnselected: '#891869',
  tagMagentaBorderSecondarySelected: '#FFACE5',
  tagTealBackgroundPrimary: '#007F8C',
  tagTealBackgroundSecondary: '#002D33',
  tagTealContentPrimary: '#FFFFFF',
  tagTealContentSecondary: '#77D5E3',
  tagTealBackgroundStateDisabled: '#002D33',
  tagTealContentStateDisabled: '#1A535A',
  tagTealBorderPrimaryUnselected: '#77D5E3',
  tagTealBorderSecondaryUnselected: '#1A535A',
  tagTealBorderSecondarySelected: '#77D5E3',
  tagLimeBackgroundPrimary: '#4F7F06',
  tagLimeBackgroundSecondary: '#1B2D00',
  tagLimeContentPrimary: '#FFFFFF',
  tagLimeContentSecondary: '#A6D467',
  tagLimeBackgroundStateDisabled: '#1B2D00',
  tagLimeContentStateDisabled: '#365310',
  tagLimeBorderPrimaryUnselected: '#A6D467',
  tagLimeBorderSecondaryUnselected: '#365310',
  tagLimeBorderSecondarySelected: '#A6D467',

  // Deprecated tokens (for backward compatibility)
  jumpRed400: '#FC7F79',
  backgroundOverlayLight: 'rgba(0, 0, 0, 0.7)',
  backgroundOverlayDark: 'rgba(0, 0, 0, 0.7)',
  backgroundLightAccent: '#002661',
  backgroundLightPositive: '#002F14',
  backgroundLightWarning: '#392300',
  backgroundLightNegative: '#520810',
});
