/*
Copyright (c) 2018-2020 Uber Technologies, Inc.

This source code is licensed under the MIT license found in the
LICENSE file in the root directory of this source tree.
*/
// @flow

export default [
  {
    Name: 'Spotted Hyena',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Carnivora',
    Family: 'Hyaenidae',
  },
  {
    Name: 'Woolly mammoth',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Proboscidea',
    Family: 'Elephantidae',
  },
  {
    Name: 'Nine-banded armadillo',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Cingulata',
    Family: 'Dasypodidae',
  },
  {
    Name: 'Donkey',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Perissodactyla',
    Family: 'Equidae',
  },
  {
    Name: 'American bison',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Artiodactyla',
    Family: 'Bovidae',
  },
  {
    Name: 'Brown-throated sloth',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Pilosa',
    Family: 'Bradypodidae',
  },
  {
    Name: 'Dog',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Carnivora',
    Family: 'Canidae',
  },
  {
    Name: 'Eastern grey kangaroo',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Diprotodontia',
    Family: 'Macropodidae',
  },
  {
    Name: 'Goat',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Artiodactyla',
    Family: 'Bovidae',
  },
  {
    Name: 'Little Owl',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Aves',
    Order: 'Strigiformes',
    Family: 'Strigidae',
  },
  {
    Name: 'Arctic hare',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Lagomorpha',
    Family: 'Leporidae',
  },
  {
    Name: 'European rabbit',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Lagomorpha',
    Family: 'Leporidae',
  },
  {
    Name: 'Roborovski hamster',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Rodentia',
    Family: 'Cricetidae',
  },
  {
    Name: 'Common bottlenose dolphin',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Cetacea',
    Family: 'Delphinidae',
  },
  {
    Name: 'Dodo',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Aves',
    Order: 'Columbiformes',
    Family: 'Columbidae',
  },
  {
    Name: 'Dugong',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Sirenia',
    Family: 'Dugongidae',
  },
  {
    Name: 'Harbor seal',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Carnivora',
    Family: 'Phocidae',
  },
  {
    Name: 'Weaver ant',
    Kingdom: 'Animalia',
    Phylum: 'Arthropoda',
    Class: 'Insecta',
    Order: 'Hymenoptera',
    Family: 'Formicidae',
  },
  {
    Name: 'Giraffe',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Artiodactyla',
    Family: 'Giraffidae',
  },
  {
    Name: 'Koala',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Diprotodontia',
    Family: 'Phascolarctidae',
  },
  {
    Name: 'Llama',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Artiodactyla',
    Family: 'Camelidae',
  },
  {
    Name: 'Lion',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Carnivora',
    Family: 'Felidae',
  },
  {
    Name: 'Narwhal',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Cetacea',
    Family: 'Monodontidae',
  },
  {
    Name: 'Platypus',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Monotremata',
    Family: 'Ornithorhynchidae',
  },
  {
    Name: 'Brown Bear',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Carnivora',
    Family: 'Ursidae',
  },
  {
    Name: 'Hairy Hermit Crab',
    Kingdom: 'Animalia',
    Phylum: 'Arthropoda',
    Class: 'Malacostraca',
    Order: 'Decapoda',
    Family: 'Paguridae',
  },
  {
    Name: 'Giant Panda',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Carnivora',
    Family: 'Ursidae',
  },
  {
    Name: 'Black Rat',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Rodentia',
    Family: 'Muridae',
  },
  {
    Name: 'Alligator',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Reptilia',
    Order: 'Crocodylia',
    Family: 'Alligatoridae',
  },
  {
    Name: 'Alligator snapping turtle',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Reptilia',
    Order: 'Testudines',
    Family: 'Chelydridae',
  },
  {
    Name: 'House Sparrow',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Aves',
    Order: 'Passeriformes',
    Family: 'Passeridae',
  },
  {
    Name: 'Mediterranean mussel',
    Kingdom: 'Animalia',
    Phylum: 'Mollusca',
    Class: 'Bivalvia',
    Order: 'Mytiloida',
    Family: 'Mytilidae',
  },
  {
    Name: 'Pacific Gull',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Aves',
    Order: 'Charadriiformes',
    Family: 'Laridae',
  },
  {
    Name: 'Common Magpie',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Aves',
    Order: 'Passeriformes',
    Family: 'Corvidae',
  },
  {
    Name: 'Black Woodpecker',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Aves',
    Order: 'Piciformes',
    Family: 'Picidae',
  },
  {
    Name: 'Great White Pelican',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Aves',
    Order: 'Pelecaniformes',
    Family: 'Pelecanidae',
  },
  {
    Name: 'Boa constrictor',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Reptilia',
    Order: 'Squamata',
    Family: 'Boidae',
  },
  {
    Name: 'Chans megastick',
    Kingdom: 'Animalia',
    Phylum: 'Arthropoda',
    Class: 'Insecta',
    Order: 'Phasmatodea',
    Family: 'Phasmatidae',
  },
  {
    Name: 'Golden Stag Beetle',
    Kingdom: 'Animalia',
    Phylum: 'Arthropoda',
    Class: 'Insecta',
    Order: 'Coleoptera',
    Family: 'Lucanidae',
  },
  {
    Name: 'russet mite',
    Kingdom: 'Animalia',
    Phylum: 'Arthropoda',
    Class: 'Arachnida',
    Order: 'Prostigmata',
    Family: 'Eriophyidae',
  },
  {
    Name: 'Firefly',
    Kingdom: 'Animalia',
    Phylum: 'Arthropoda',
    Class: 'Insecta',
    Order: 'Coleoptera',
    Family: 'Lampyridae',
  },
  {
    Name: 'Ringlet Butterfly',
    Kingdom: 'Animalia',
    Phylum: 'Arthropoda',
    Class: 'Insecta',
    Order: 'Lepidoptera',
    Family: 'Nymphalidae',
  },
  {
    Name: 'European wasp',
    Kingdom: 'Animalia',
    Phylum: 'Arthropoda',
    Class: 'Insecta',
    Order: 'Hymenoptera',
    Family: 'Vespidae',
  },
  {
    Name: 'Ostrich',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Aves',
    Order: 'Struthioniformes',
    Family: 'Struthionidae',
  },
  {
    Name: 'Tarantula',
    Kingdom: 'Animalia',
    Phylum: 'Arthropoda',
    Class: 'Arachnida',
    Order: 'Araneae',
    Family: 'Lycosidae',
  },
  {
    Name: 'giant forest scorpions',
    Kingdom: 'Animalia',
    Phylum: 'Arthropoda',
    Class: 'Chelicerata',
    Order: 'Scorpiones',
    Family: 'Scorpionidae',
  },
  {
    Name: 'Pterodactylus',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Reptilia',
    Order: '†Pterosauria',
    Family: '†Pterodactylidae',
  },
  {
    Name: 'Zebra',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Perissodactyla',
    Family: 'Equidae',
  },
  {
    Name: 'African civet',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Carnivora',
    Family: 'Viverridae',
  },
  {
    Name: 'Mink',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Carnivora',
    Family: 'Mustelidae',
  },
  {
    Name: 'Cynoscion nebulosus',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Actinopterygii',
    Order: 'Perciformes',
    Family: 'Sciaenidae',
  },
  {
    Name: 'Walrus',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Carnivora',
    Family: 'Odobenidae',
  },
  {
    Name: 'Tiger',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Carnivora',
    Family: 'Felidae',
  },
  {
    Name: 'Tortoise',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Reptilia',
    Order: 'Chelonii',
    Family: 'Testudinidae',
  },
  {
    Name: 'Scorpionfish',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Actinopterygii',
    Order: 'Scorpaeniformes',
    Family: 'Scorpaenidae',
  },
  {
    Name: 'Hedgehog',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Erinaceomorpha',
    Family: 'Erinaceidae',
  },
  {
    Name: 'Reindeer',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Artiodactyla',
    Family: 'Cervidae',
  },
  {
    Name: 'Lophius piscatorius',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Actinopterygii',
    Order: 'Lophiiformes',
    Family: 'Lophiidae',
  },
  {
    Name: 'Guinea pig',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Rodentia',
    Family: 'Caviidae',
  },
  {
    Name: 'Penguin',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Aves',
    Order: 'Sphenisciformes',
    Family: 'Spheniscidae',
  },
  {
    Name: 'Blowfish',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Actinopterygii',
    Order: 'Tetraodontiformes',
    Family: 'Tetraodontidae',
  },
  {
    Name: 'Cockatoo',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Aves',
    Order: 'Psittaciformes',
    Family: 'Cacatuidae',
  },
  {
    Name: 'Leopard',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Carnivora',
    Family: 'Felidae',
  },
  {
    Name: 'Killer whale',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Cetacea',
    Family: 'Delphinidae',
  },
  {
    Name: 'Bowhead Whale',
    Kingdom: 'Animalia',
    Phylum: 'Chordata',
    Class: 'Mammalia',
    Order: 'Cetacea',
    Family: 'Balaenidae',
  },
];
