// flow-typed signature: 511ec1368a11361b2ff3c681829da807
// flow-typed version: <<STUB>>/@storybook/addon-links_v^3.3.15/flow_v0.67.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-links'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-links' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-links/dist/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/react/components/link' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/dist/react/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/react' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/src/index' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/src/manager' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/src/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/src/preview.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/src/react/components/link' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/src/react/components/link.test' {
  declare module.exports: any;
}

declare module '@storybook/addon-links/src/react/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-links/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/index'>;
}
declare module '@storybook/addon-links/dist/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/manager'>;
}
declare module '@storybook/addon-links/dist/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/preview'>;
}
declare module '@storybook/addon-links/dist/react/components/link.js' {
  declare module.exports: $Exports<
    '@storybook/addon-links/dist/react/components/link'
  >;
}
declare module '@storybook/addon-links/dist/react/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/dist/react/index'>;
}
declare module '@storybook/addon-links/react.js' {
  declare module.exports: $Exports<'@storybook/addon-links/react'>;
}
declare module '@storybook/addon-links/register.js' {
  declare module.exports: $Exports<'@storybook/addon-links/register'>;
}
declare module '@storybook/addon-links/src/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/src/index'>;
}
declare module '@storybook/addon-links/src/manager.js' {
  declare module.exports: $Exports<'@storybook/addon-links/src/manager'>;
}
declare module '@storybook/addon-links/src/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-links/src/preview'>;
}
declare module '@storybook/addon-links/src/preview.test.js' {
  declare module.exports: $Exports<'@storybook/addon-links/src/preview.test'>;
}
declare module '@storybook/addon-links/src/react/components/link.js' {
  declare module.exports: $Exports<
    '@storybook/addon-links/src/react/components/link'
  >;
}
declare module '@storybook/addon-links/src/react/components/link.test.js' {
  declare module.exports: $Exports<
    '@storybook/addon-links/src/react/components/link.test'
  >;
}
declare module '@storybook/addon-links/src/react/index.js' {
  declare module.exports: $Exports<'@storybook/addon-links/src/react/index'>;
}
